Create Tables

In [ ]:
import sqlite3

conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()
c.execute('''
    CREATE TABLE IF NOT EXISTS all_works (
    id TEXT PRIMARY KEY,
    published TEXT,
    link TEXT,
    status TEXT,
    title TEXT,
    author TEXT,
    rating TEXT,
    categories TEXT,
    fandoms TEXT,
    relationships TEXT,
    characters TEXT,
    freeform_tags TEXT,
    summary TEXT
    )
''')

conn.commit()
conn.close()

In [ ]:
import sqlite3

conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

c.execute('''
    CREATE TABLE IF NOT EXISTS my_bookmarks (
        work_id TEXT PRIMARY KEY
    )
''')

conn.commit()

c.execute('''
    CREATE TABLE IF NOT EXISTS public_bookmarks (
        user_id TEXT,
        work_id TEXT,
        PRIMARY KEY (user_id, work_id)
    )
''')

conn.commit()
conn.close()

print("SQLite table 'my_bookmarks' and 'public_bookmarks' created successfully in ao3_works.db")

SQLite table 'my_bookmarks' and 'public_bookmarks' created successfully in ao3_works.db

Scrape Pages and Insert Data to the DB

In [ ]:
import time
import re
import math
from collections import Counter
from urllib.parse import urljoin

import requests
import pandas as pd
from bs4 import BeautifulSoup

import sqlite3

In [ ]:
BASE_URL = "https://archiveofourown.org"

HEADERS = {
    "User-Agent": "AO3 recommender student project - small-scale metadata parser"
}

In [ ]:
import time
import requests

def get_html(
    url: str,
    delay: float = 2.0,
    retries: int = 3,
    backoff: float = 2.0
) -> str:
    """
    Fetch a page slowly and politely, retrying temporary failures.
    """
    last_error = None

    for attempt in range(1, retries + 1):
        time.sleep(delay)

        try:
            response = requests.get(
                url,
                headers=HEADERS,
                timeout=(10, 20)  # connect timeout, read timeout
            )

            if response.status_code == 200:
                print(f"Fetch successful for {url}.")
                return response.text

            last_error = Exception(
                f"Failed to fetch {url}. Status code: {response.status_code}"
            )

        except requests.exceptions.Timeout as e:
            last_error = e

        except requests.exceptions.ConnectionError as e:
            last_error = e

        if attempt < retries:
            wait = backoff * attempt
            print(f"Fetch failed for {url}. Retrying in {wait:.1f}s...")
            time.sleep(wait)

    raise Exception(f"Failed to fetch {url} after {retries} attempts: {last_error}")

In [ ]:
def extract_work_id(url: str) -> str | None:
    """
    Returns a work ID string from URLs like:
    https://archiveofourown.org/works/33023536
    """
    match = re.search(r"/works/(\d+)", url)

    if match:
        return match.group(1)

    return None

In [ ]:
def clean_number(value: str):
    """
    Returns a string from '104,439' into 104439.
    """
    if not value:
        return None

    value = value.replace(",", "").strip()

    if value.isdigit():
        return int(value)

    return value

In [ ]:
def extract_tag_texts(soup: BeautifulSoup, dd_class: str) -> list[str]:
    """
    Returns tag text from a dd section, e.g.
    dd.rating, dd.fandom, dd.relationship, dd.character, dd.freeform.
    """
    section = soup.select_one(f"dd.{dd_class}")

    if not section:
        return []

    return [tag.get_text(strip=True) for tag in section.select("a.tag")]

In [ ]:
def extract_stats_text(soup: BeautifulSoup) -> dict:
    """
    Parses the stats section:
    Published, Updated, Words, Chapters, Comments, Kudos, Bookmarks, Hits.
    """
    stats = {}

    stats_dl = soup.select_one("dl.stats")

    if not stats_dl:
        return stats

    current_key = None

    for element in stats_dl.find_all(["dt", "dd"], recursive=False):
        if element.name == "dt":
            current_key = element.get_text(strip=True).replace(":", "").lower()
        elif element.name == "dd" and current_key:
            stats[current_key] = clean_number(element.get_text(strip=True))
            current_key = None

    return stats

In [ ]:
import re
def parse_work_page(html: str, url: str) -> dict:
    """
    Parses one AO3 work page and returns metadata.
    """
    soup = BeautifulSoup(html, "html.parser")

    title_element = soup.select_one("h2.title")
    author_element = soup.select_one("h3.byline")

    rating = extract_tag_texts(soup, "rating")
    # warnings = extract_tag_texts(soup, "warning")
    categories = extract_tag_texts(soup, "category")
    fandoms = extract_tag_texts(soup, "fandom")
    relationships = extract_tag_texts(soup, "relationship")
    characters = extract_tag_texts(soup, "character")
    freeform_tags = extract_tag_texts(soup, "freeform")

    language_element = soup.select_one("dd.language")
    summary_element = soup.select_one("div.summary blockquote")

    stats = extract_stats_text(soup)

    work_id = extract_work_id(url)

    for relationship in relationships:
      split_relationship = re.split(r'[/|&]', relationship)
      # split_relationship = relationship.split('/')
      # print(split_relationship)
      for character in split_relationship:
        if character not in characters:
          characters.append(character)

    work_data = {
        "work_id": work_id,
        "url": url,
        "title": title_element.get_text(" ", strip=True) if title_element else None,
        "author": author_element.get_text(" ", strip=True) if author_element else None,
        "rating": rating,
        # "warnings": warnings,
        "categories": categories,
        "fandoms": fandoms,
        "relationships": relationships,
        "characters": characters,
        "freeform_tags": freeform_tags,
        "language": language_element.get_text(strip=True) if language_element else None,
        "summary": summary_element.get_text(" ", strip=True) if summary_element else None,
        "published": stats.get("published"),
        # "updated": stats.get("updated") or stats.get("status"),
        "words": stats.get("words"),
        "chapters": stats.get("chapters"),
        "comments": stats.get("comments"),
        "kudos": stats.get("kudos"),
        "bookmarks_count": stats.get("bookmarks"),
        "hits": stats.get("hits"),
    }

    return work_data

In [ ]:
def get_total_bookmark_pages(bookmarks_count, per_page=20):
    """
    Returns an int of the estimated number of bookmark user pages.
    AO3 bookmark pages usually show 20 bookmarks per page.
    Example: 832 bookmarks -> ceil(832 / 20) = 42 pages.
    """
    if not bookmarks_count:
        return 0

    try:
        bookmarks_count = int(bookmarks_count)
    except ValueError:
        return 0

    return math.ceil(bookmarks_count / per_page)

In [ ]:
def get_bookmarks_page_url(work_url: str, page: int) -> str:
    """
    Returns a work URL with a bookmarks page number.
    Example:
    https://archiveofourown.org/works/33023536
    ->
    https://archiveofourown.org/works/33023536/bookmarks?page=1
    """
    work_id = extract_work_id(work_url)

    if not work_id:
        raise ValueError(f"Could not extract work ID from {work_url}")

    return f"{BASE_URL}/works/{work_id}/bookmarks?page={page}"

In [ ]:


def parse_bookmark_users(html: str) -> list[str]:
    soup = BeautifulSoup(html, "html.parser")
    users = set()

    for link in soup.select('a[href*="/pseuds/"]'):
        href = link.get("href", "")

        match = re.match(r"^/users/([^/]+)/pseuds/([^/?#]+)", href)

        if match:
            users.add(match.group(2))

    return list(users)

In [ ]:
def collect_all_bookmark_users(work_url: str, bookmarks_count: int, delay: float = 3.0) -> list[str]:
    """
    Returns all users that bookmarked a work.
    """
    total_pages = get_total_bookmark_pages(bookmarks_count)

    # print(f"Bookmark count: {bookmarks_count}")
    # print(f"Estimated bookmark pages: {total_pages}")

    all_users = set()

    for page in range(1, total_pages + 1):
        bookmarks_url = get_bookmarks_page_url(work_url, page)
        print(f"Fetching bookmarks page {page}/{total_pages}: {bookmarks_url}")

        try:
            bookmarks_html = get_html(bookmarks_url, delay=delay)
            page_users = parse_bookmark_users(bookmarks_html)
            all_users.update(page_users)

        except Exception as e:
            print(f"Could not fetch bookmark page {page} for {work_url}: {e}")

    return list(all_users)

In [ ]:
def update_my_interactions_table(c, work_id):
    c.execute(
        "INSERT OR IGNORE INTO my_bookmarks (work_id) VALUES (?)",
        (work_id,)
    )


def update_public_interactions_table(c, user_id, work_id):
    c.execute(
        "INSERT OR IGNORE INTO public_bookmarks (user_id, work_id) VALUES (?, ?)",
        (user_id, work_id)
    )

In [ ]:
def update_all_works_table_status(c, work_id, new_status):
    c.execute(
        "UPDATE all_works SET status = ? WHERE id = ?",
        (new_status, work_id)
    )
    print(f"Work {work_id} status updated to {new_status}.")

In [ ]:


def update_all_works_table_tags(
    c, work_id, rating, categories, fandoms,
    relationships, characters, freeform_tags, summary
):
    c.execute(
        '''UPDATE all_works
           SET
               rating = ?,
               categories = ?,
               fandoms = ?,
               relationships = ?,
               characters = ?,
               freeform_tags = ?,
               summary = ?
           WHERE id = ?''',
        (
            rating, categories, fandoms, relationships,
            characters, freeform_tags, summary, work_id
        )
    )
    print(f"Work {work_id} updated with tags.")

In [ ]:
def collect_work_data_and_bookmark_usernames_from_a_link(work_url: str) -> tuple[dict, list[str]]:
    """
    Main function:
    - Takes AO3 work URLs
    - Parses work metadata
    - Parses public bookmark users
    """
    # works = []
    # bookmark_rows = []

    print(f"Fetching work: {work_url}")

    try:
        work_html = get_html(work_url)
    except requests.exceptions.ReadTimeout as e:
        print(f"Read timeout fetching work {work_url}: {e}. Skipping this work.")
        return None, []
    except Exception as e:
        print(f"Error fetching work {work_url}: {e}. Skipping this work.")
        return None, []

    work_data = parse_work_page(work_html, work_url)

    # Portfolio-safe default: skip Explicit works
    ratings = work_data.get("rating", [])
    if "Explicit" in ratings:
        print(f"Skipping explicit work: {work_url}")
        return None, []

    # works.append(work_data)
    bookmarks_count = work_data.get("bookmarks_count", 0)

    try:
        bookmark_users = collect_all_bookmark_users(
            work_url=work_url,
            bookmarks_count=bookmarks_count,
            delay=3.0
        )
        if len(bookmark_users) == 0:
            bookmark_users = [work_data.get('author')]

    except Exception as e:
        print(f"Could not fetch bookmarks for {work_url}: {e}")
        bookmark_users = [work_data.get('author')]

    return work_data, bookmark_users

In [ ]:
import json

def collect_and_update_with_new_works(links_list, update_my_interactions):
    conn = sqlite3.connect('ao3_works.db')
    c = conn.cursor()

    try:
        for link in links_list:
            work_data, bookmark_users = collect_work_data_and_bookmark_usernames_from_a_link(link)

            if work_data is None:
                # add to another table [link, rss/mine], so it can be tried again
                continue

            work_id = work_data.get('work_id')

            try:
                if update_my_interactions:
                    add_work_to_db(
                        c,
                        work_id,
                        work_data.get('published'),
                        work_data.get('url'),
                        'New',
                        work_data.get('title'),
                        work_data.get('author')
                    )
                    update_my_interactions_table(c, work_id)

                for username in bookmark_users:
                    update_public_interactions_table(c, username, work_id)

                update_all_works_table_tags(
                    c,
                    work_id,
                    json.dumps(work_data.get('rating')),
                    json.dumps(work_data.get('categories')),
                    json.dumps(work_data.get('fandoms')),
                    json.dumps(work_data.get('relationships')),
                    json.dumps(work_data.get('characters')),
                    json.dumps(work_data.get('freeform_tags')),
                    work_data.get('summary')
                )

                update_all_works_table_status(
                    c,
                    work_id,
                    'Scraped'
                )

                conn.commit()

            except Exception as e:
                conn.rollback()
                print(f"Error adding work {work_id}: {e}")

    finally:
        conn.close()

In [ ]:
if __name__ == "__main__":
    ao3_links = [
        # Put your AO3 work links here
        # "https://archiveofourown.org/works/83067686",
        # "https://archiveofourown.org/works/33023536",
        "https://archiveofourown.org/works/75267501",
        'https://archiveofourown.org/works/56181721',
        'https://archiveofourown.org/works/81993896',
        'https://archiveofourown.org/works/76423276',
        'https://archiveofourown.org/works/55165036',
        'https://archiveofourown.org/works/50992918',
        'https://archiveofourown.org/works/73894251',
        'https://archiveofourown.org/works/62910172'

    ]

    collect_and_update_with_new_works(ao3_links,True)

Fetching work: https://archiveofourown.org/works/75267501
Fetch successful for https://archiveofourown.org/works/75267501.
Fetching bookmarks page 1/8: https://archiveofourown.org/works/75267501/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=1.
Fetching bookmarks page 2/8: https://archiveofourown.org/works/75267501/bookmarks?page=2
Fetch failed for https://archiveofourown.org/works/75267501/bookmarks?page=2. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=2.
Fetching bookmarks page 3/8: https://archiveofourown.org/works/75267501/bookmarks?page=3
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=3.
Fetching bookmarks page 4/8: https://archiveofourown.org/works/75267501/bookmarks?page=4
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=4.
Fetching bookmarks page 5/8: https://archiveofourown.org/works/75267501/bookmarks?page=5
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=5.
Fetching bookmarks page 6/8: https://archiveofourown.org/works/75267501/bookmarks?page=6
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=6.
Fetching bookmarks page 7/8: https://archiveofourown.org/works/75267501/bookmarks?page=7
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=7.
Fetching bookmarks page 8/8: https://archiveofourown.org/works/75267501/bookmarks?page=8
Fetch successful for https://archiveofourown.org/works/75267501/bookmarks?page=8.
Successfully added work 75267501 to the database.
Work 75267501 updated with tags.
Work 75267501 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/56181721
Fetch successful for https://archiveofourown.org/works/56181721.
Fetching bookmarks page 1/16: https://archiveofourown.org/works/56181721/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=1.
Fetching bookmarks page 2/16: https://archiveofourown.org/works/56181721/bookmarks?page=2
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=2.
Fetching bookmarks page 3/16: https://archiveofourown.org/works/56181721/bookmarks?page=3
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=3.
Fetching bookmarks page 4/16: https://archiveofourown.org/works/56181721/bookmarks?page=4
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=4. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=4. Retrying in 4.0s...
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=4.
Fetching bookmarks page 5/16: https://archiveofourown.org/works/56181721/bookmarks?page=5
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=5. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=5.
Fetching bookmarks page 6/16: https://archiveofourown.org/works/56181721/bookmarks?page=6
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=6.
Fetching bookmarks page 7/16: https://archiveofourown.org/works/56181721/bookmarks?page=7
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=7. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=7.
Fetching bookmarks page 8/16: https://archiveofourown.org/works/56181721/bookmarks?page=8
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=8.
Fetching bookmarks page 9/16: https://archiveofourown.org/works/56181721/bookmarks?page=9
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=9. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=9.
Fetching bookmarks page 10/16: https://archiveofourown.org/works/56181721/bookmarks?page=10
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=10.
Fetching bookmarks page 11/16: https://archiveofourown.org/works/56181721/bookmarks?page=11
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=11.
Fetching bookmarks page 12/16: https://archiveofourown.org/works/56181721/bookmarks?page=12
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=12.
Fetching bookmarks page 13/16: https://archiveofourown.org/works/56181721/bookmarks?page=13
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=13.
Fetching bookmarks page 14/16: https://archiveofourown.org/works/56181721/bookmarks?page=14
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=14. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=14. Retrying in 4.0s...
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=14.
Fetching bookmarks page 15/16: https://archiveofourown.org/works/56181721/bookmarks?page=15
Fetch failed for https://archiveofourown.org/works/56181721/bookmarks?page=15. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=15.
Fetching bookmarks page 16/16: https://archiveofourown.org/works/56181721/bookmarks?page=16
Fetch successful for https://archiveofourown.org/works/56181721/bookmarks?page=16.
Successfully added work 56181721 to the database.
Work 56181721 updated with tags.
Work 56181721 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/81993896
Fetch failed for https://archiveofourown.org/works/81993896. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/81993896.
Fetching bookmarks page 1/10: https://archiveofourown.org/works/81993896/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=1.
Fetching bookmarks page 2/10: https://archiveofourown.org/works/81993896/bookmarks?page=2
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=2.
Fetching bookmarks page 3/10: https://archiveofourown.org/works/81993896/bookmarks?page=3
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=3.
Fetching bookmarks page 4/10: https://archiveofourown.org/works/81993896/bookmarks?page=4
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=4.
Fetching bookmarks page 5/10: https://archiveofourown.org/works/81993896/bookmarks?page=5
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=5.
Fetching bookmarks page 6/10: https://archiveofourown.org/works/81993896/bookmarks?page=6
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=6.
Fetching bookmarks page 7/10: https://archiveofourown.org/works/81993896/bookmarks?page=7
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=7.
Fetching bookmarks page 8/10: https://archiveofourown.org/works/81993896/bookmarks?page=8
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=8.
Fetching bookmarks page 9/10: https://archiveofourown.org/works/81993896/bookmarks?page=9
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=9.
Fetching bookmarks page 10/10: https://archiveofourown.org/works/81993896/bookmarks?page=10
Fetch successful for https://archiveofourown.org/works/81993896/bookmarks?page=10.
Successfully added work 81993896 to the database.
Work 81993896 updated with tags.
Work 81993896 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/76423276
Fetch successful for https://archiveofourown.org/works/76423276.
Fetching bookmarks page 1/3: https://archiveofourown.org/works/76423276/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/76423276/bookmarks?page=1.
Fetching bookmarks page 2/3: https://archiveofourown.org/works/76423276/bookmarks?page=2
Fetch failed for https://archiveofourown.org/works/76423276/bookmarks?page=2. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/76423276/bookmarks?page=2.
Fetching bookmarks page 3/3: https://archiveofourown.org/works/76423276/bookmarks?page=3
Fetch successful for https://archiveofourown.org/works/76423276/bookmarks?page=3.
Successfully added work 76423276 to the database.
Work 76423276 updated with tags.
Work 76423276 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/55165036
Fetch failed for https://archiveofourown.org/works/55165036. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/55165036.
Fetching bookmarks page 1/2: https://archiveofourown.org/works/55165036/bookmarks?page=1
Fetch failed for https://archiveofourown.org/works/55165036/bookmarks?page=1. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/55165036/bookmarks?page=1. Retrying in 4.0s...
Fetch successful for https://archiveofourown.org/works/55165036/bookmarks?page=1.
Fetching bookmarks page 2/2: https://archiveofourown.org/works/55165036/bookmarks?page=2
Fetch failed for https://archiveofourown.org/works/55165036/bookmarks?page=2. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/55165036/bookmarks?page=2. Retrying in 4.0s...
Could not fetch bookmark page 2 for https://archiveofourown.org/works/55165036: Failed to fetch https://archiveofourown.org/works/55165036/bookmarks?page=2 after 3 attempts: HTTPSConnectionPool(host='archiveofourown.org', port=443): Read timed out. (read timeout=20)
Successfully added work 55165036 to the database.
Work 55165036 updated with tags.
Work 55165036 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/50992918
Fetch failed for https://archiveofourown.org/works/50992918. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/50992918.
Fetching bookmarks page 1/25: https://archiveofourown.org/works/50992918/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=1.
Fetching bookmarks page 2/25: https://archiveofourown.org/works/50992918/bookmarks?page=2
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=2.
Fetching bookmarks page 3/25: https://archiveofourown.org/works/50992918/bookmarks?page=3
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=3.
Fetching bookmarks page 4/25: https://archiveofourown.org/works/50992918/bookmarks?page=4
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=4.
Fetching bookmarks page 5/25: https://archiveofourown.org/works/50992918/bookmarks?page=5
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=5.
Fetching bookmarks page 6/25: https://archiveofourown.org/works/50992918/bookmarks?page=6
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=6.
Fetching bookmarks page 7/25: https://archiveofourown.org/works/50992918/bookmarks?page=7
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=7.
Fetching bookmarks page 8/25: https://archiveofourown.org/works/50992918/bookmarks?page=8
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=8.
Fetching bookmarks page 9/25: https://archiveofourown.org/works/50992918/bookmarks?page=9
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=9.
Fetching bookmarks page 10/25: https://archiveofourown.org/works/50992918/bookmarks?page=10
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=10.
Fetching bookmarks page 11/25: https://archiveofourown.org/works/50992918/bookmarks?page=11
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=11.
Fetching bookmarks page 12/25: https://archiveofourown.org/works/50992918/bookmarks?page=12
Fetch failed for https://archiveofourown.org/works/50992918/bookmarks?page=12. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=12.
Fetching bookmarks page 13/25: https://archiveofourown.org/works/50992918/bookmarks?page=13
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=13.
Fetching bookmarks page 14/25: https://archiveofourown.org/works/50992918/bookmarks?page=14
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=14.
Fetching bookmarks page 15/25: https://archiveofourown.org/works/50992918/bookmarks?page=15
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=15.
Fetching bookmarks page 16/25: https://archiveofourown.org/works/50992918/bookmarks?page=16
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=16.
Fetching bookmarks page 17/25: https://archiveofourown.org/works/50992918/bookmarks?page=17
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=17.
Fetching bookmarks page 18/25: https://archiveofourown.org/works/50992918/bookmarks?page=18
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=18.
Fetching bookmarks page 19/25: https://archiveofourown.org/works/50992918/bookmarks?page=19
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=19.
Fetching bookmarks page 20/25: https://archiveofourown.org/works/50992918/bookmarks?page=20
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=20.
Fetching bookmarks page 21/25: https://archiveofourown.org/works/50992918/bookmarks?page=21
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=21.
Fetching bookmarks page 22/25: https://archiveofourown.org/works/50992918/bookmarks?page=22
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=22.
Fetching bookmarks page 23/25: https://archiveofourown.org/works/50992918/bookmarks?page=23
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=23.
Fetching bookmarks page 24/25: https://archiveofourown.org/works/50992918/bookmarks?page=24
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=24.
Fetching bookmarks page 25/25: https://archiveofourown.org/works/50992918/bookmarks?page=25
Fetch successful for https://archiveofourown.org/works/50992918/bookmarks?page=25.
Successfully added work 50992918 to the database.
Work 50992918 updated with tags.
Work 50992918 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/73894251
Fetch successful for https://archiveofourown.org/works/73894251.
Fetching bookmarks page 1/7: https://archiveofourown.org/works/73894251/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=1.
Fetching bookmarks page 2/7: https://archiveofourown.org/works/73894251/bookmarks?page=2
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=2.
Fetching bookmarks page 3/7: https://archiveofourown.org/works/73894251/bookmarks?page=3
Fetch failed for https://archiveofourown.org/works/73894251/bookmarks?page=3. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/73894251/bookmarks?page=3. Retrying in 4.0s...
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=3.
Fetching bookmarks page 4/7: https://archiveofourown.org/works/73894251/bookmarks?page=4
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=4.
Fetching bookmarks page 5/7: https://archiveofourown.org/works/73894251/bookmarks?page=5
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=5.
Fetching bookmarks page 6/7: https://archiveofourown.org/works/73894251/bookmarks?page=6
Fetch failed for https://archiveofourown.org/works/73894251/bookmarks?page=6. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=6.
Fetching bookmarks page 7/7: https://archiveofourown.org/works/73894251/bookmarks?page=7
Fetch successful for https://archiveofourown.org/works/73894251/bookmarks?page=7.
Successfully added work 73894251 to the database.
Work 73894251 updated with tags.
Work 73894251 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/62910172
Fetch successful for https://archiveofourown.org/works/62910172.
Fetching bookmarks page 1/33: https://archiveofourown.org/works/62910172/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=1.
Fetching bookmarks page 2/33: https://archiveofourown.org/works/62910172/bookmarks?page=2
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=2.
Fetching bookmarks page 3/33: https://archiveofourown.org/works/62910172/bookmarks?page=3
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=3.
Fetching bookmarks page 4/33: https://archiveofourown.org/works/62910172/bookmarks?page=4
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=4.
Fetching bookmarks page 5/33: https://archiveofourown.org/works/62910172/bookmarks?page=5
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=5.
Fetching bookmarks page 6/33: https://archiveofourown.org/works/62910172/bookmarks?page=6
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=6.
Fetching bookmarks page 7/33: https://archiveofourown.org/works/62910172/bookmarks?page=7
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=7.
Fetching bookmarks page 8/33: https://archiveofourown.org/works/62910172/bookmarks?page=8
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=8.
Fetching bookmarks page 9/33: https://archiveofourown.org/works/62910172/bookmarks?page=9
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=9.
Fetching bookmarks page 10/33: https://archiveofourown.org/works/62910172/bookmarks?page=10
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=10.
Fetching bookmarks page 11/33: https://archiveofourown.org/works/62910172/bookmarks?page=11
Fetch failed for https://archiveofourown.org/works/62910172/bookmarks?page=11. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=11.
Fetching bookmarks page 12/33: https://archiveofourown.org/works/62910172/bookmarks?page=12
Fetch failed for https://archiveofourown.org/works/62910172/bookmarks?page=12. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=12.
Fetching bookmarks page 13/33: https://archiveofourown.org/works/62910172/bookmarks?page=13
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=13.
Fetching bookmarks page 14/33: https://archiveofourown.org/works/62910172/bookmarks?page=14
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=14.
Fetching bookmarks page 15/33: https://archiveofourown.org/works/62910172/bookmarks?page=15
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=15.
Fetching bookmarks page 16/33: https://archiveofourown.org/works/62910172/bookmarks?page=16
Fetch failed for https://archiveofourown.org/works/62910172/bookmarks?page=16. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=16.
Fetching bookmarks page 17/33: https://archiveofourown.org/works/62910172/bookmarks?page=17
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=17.
Fetching bookmarks page 18/33: https://archiveofourown.org/works/62910172/bookmarks?page=18
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=18.
Fetching bookmarks page 19/33: https://archiveofourown.org/works/62910172/bookmarks?page=19
Fetch successful for https://archiveofourown.org/works/62910172/bookmarks?page=19.
Fetching bookmarks page 20/33: https://archiveofourown.org/works/62910172/bookmarks?page=20

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

all = c.execute('''
      Select * from all_works
''')

for row in all:
    print(row)

conn.close()

('75267501', '2025-12-21', 'https://archiveofourown.org/works/75267501', 'Scraped', 'the wolf and the fox', 'GoddessOfWriting , TheDauntless (GoddessOfWriting)', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Jon Snow/Original Female Character(s)", "Jon Snow & Original Female Character(s)", "Jon Snow & Arya Stark & Bran Stark & Rickon Stark & Robb Stark & Sansa Stark", "Ghost | Jon Snow\'s Direwolf & Jon Snow", "Catelyn Tully Stark/Ned Stark", "Jon Snow & Ned Stark"]', '["Original Female Character(s)", "Characters From The North (A Song of Ice and Fire)", "Jon Snow", "Ghost | Jon Snow\'s Direwolf", "Arya Stark", "Nymeria | Arya Stark\'s Direwolf", "Sansa Stark", "Robb Stark", "Theon Greyjoy", "Bran Stark", "Rickon Stark", "Summer | Bran Stark\'s Direwolf", "Shaggydog | Rickon Stark\'s Direwolf", "Ned Stark", "Catelyn Tully Stark", "Maester Luwin of Winterfell (A Song of Ice and Fire)", "Rodrik Cassel", "Jory Cassel", "Harwin the Winterfell Guard (A Song of Ice and Fire)", "Robert Baratheon", "Joffrey Baratheon", "Cersei Lannister", "Tyrion Lannister", "Jon Snow ", " Original Female Character(s)", " Arya Stark ", " Bran Stark ", " Rickon Stark ", " Robb Stark ", " Sansa Stark", "Ghost ", " Jon Snow\'s Direwolf ", " Jon Snow", " Ned Stark"]', '["Original Noble House (A Song of Ice and Fire)", "Northern Culture & Customs (A Song of Ice and Fire)", "The North (A Song of Ice and Fire)", "The Wolfswood (A Song of Ice and Fire)", "Winterfell (A Song of Ice and Fire)", "House Stark (A Song of Ice and Fire)", "Author Supports House Stark (A Song of Ice and Fire)", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Jon Snow Doesn\'t Join the Night\'s Watch", "Married Jon Snow", "Childhood Friends to Lovers", "Hunters & Hunting", "Wargs & Warging (A Song of Ice and Fire)", "Ghost | Jon Snow\'s Direwolf is a Good Boy", "Joffrey Baratheon Being an Asshole", "Robert Baratheon Being an Asshole", "Catelyn Tully Stark is Not Nice", "Westerosi Politics (A Song of Ice and Fire)", "The Old Gods (A Song of Ice and Fire)", "Weirwood Trees (A Song of Ice and Fire)", "Skinchangers & Skinchanging (A Song of Ice and Fire)", "Mentioned Rhaegar Targaryen", "Mentioned Lyanna Stark"]', "The first time she met Jon Snow, they were twelve years old and he accidentally walked into her trap. ... From his uncomfortable position suspended in the air, Jon looks down at the girl standing with her hands on her hips. She is around his age, with bark brown hair in two braids, forest green eyes, and dressed in a brown hunting ensemble. “Be quiet, stupid. You scared away the gods themselves!” The indignation of being caught in a trap by a girl catches up to him. “Let me down! You shouldn’t have put your stupid trap there.” “How else are you meant to catch game?” She yells up at him before untangling a rope and Jon falls to the ground with a thud. --- House Rennard of the Wolfswood has long stood by House Stark, joined together by the large stretches of the forest and their inhabitants. They are known for raising excellent hunters, trappers, hawkers and gamekeepers - most of them women, for there has never been a ruling lord in their entire history. Jon Snow walks into Dyana Rennard's trap one day and falls head over heels - literally.")
('56181721', '2026-05-04', 'https://archiveofourown.org/works/56181721', 'Scraped', 'The Prince and the King', 'HimmeltheHero', '["Mature"]', '["Gen", "F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Elia Martell/Rhaegar Targaryen", "Ashara Dayne/Ned Stark", "past Lyanna Stark/Rhaegar Targaryen - Relationship", "Jon Snow/Mya Stone", "Rhaegar Targaryen/Margaery Tyrell"]', '["Rhaegar Targaryen", "Aerys II Targaryen", "Tywin Lannister", "Jon Snow", "Aegon Targaryen (Son of Elia)", "Rhaenys Targaryen (Daughter of Elia)", "Elia Martell", "Oswell Whent", "Richard Lonmouth", "Margaery Tyrell", "Cersei Lannister", "Viserys Targaryen (Brother of Daenerys)", "Daenerys Targaryen", "Ned Stark", "Rickard Stark", "Robert Baratheon", "Rhaella Targaryen (Wife of Aerys II)", "Ashara Dayne", "Arthur Dayne", "Mya Stone", "Myles Mooton", "Jon Connington", "Stannis Baratheon", "past Lyanna Stark", "Rhaegar Targaryen - Relationship"]', '["Alternate Universe - Canon Divergence", "No Robert\'s Rebellion | Robert Baratheon Never Rebels Against the Targaryens", "Canon-Typical Violence", "Jon Snow is a Targaryen", "Politics", "Dragons", "Targaryen-on-Targaryen violence"]', '“Treason and turmoil followed, as night follows day, ending at Summerhall in sorcery, fire and grief.” Aegon the Unlikely and most of his kin died at Summerhall, but not before managing to bring dragons back into the world. With their greatest power restored to them, House Targaryen begins a new era of dominance over the Seven Kingdoms. But with King Aerys slipping into madness and Prince Rhaegar lost in his prophecies the dragons once again dance…')
('81993896', '2026-02-16', 'https://archiveofourown.org/works/81993896', 'Scraped', 'Survive, Endure, Rise', 'An_Anonymous_Writer', '["Mature"]', '["F/M", "Gen"]', '["Game of Thrones (TV)", "A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Jon Snow/Margaery Tyrell", "Ysilla Royce/Robb Stark", "Catelyn Tully Stark/Ned Stark", "Roslin Frey/Edmure Tully", "Sansa Stark/Willas Tyrell", "Garlan Tyrell/Desmera Redwyne"]', '["Jon Snow", "Robb Stark", "Ned Stark", "Catelyn Tully Stark", "Arya Stark", "Sansa Stark", "Brandon Stark", "Rickon Stark", "Arthur Dayne", "Margaery Tyrell", "Olenna Tyrell", "Loras Tyrell", "Mace Tyrell", "House Tyrell Characters (A Song of Ice and Fire)", "House Stark Characters (A Song of Ice and Fire)", "Brynden \\"Blackfish\\" Tully", "Davos Seaworth", "Jorah Mormont", "Jaime Lannister", "Tyrion Lannister", "Cersei Lannister", "Tywin Lannister", "House Lannister Characters (A Song of Ice and Fire)", "Robert Baratheon", "Joffrey Baratheon", "Stannis Baratheon", "Renly Baratheon", "Myrcella Baratheon", "House Baratheon Characters (A Song of Ice and Fire)", "House Martell Characters (A Song of Ice and Fire)", "Edmure Tully", "Hoster Tully", "House Tully Characters (A Song of Ice and Fire)", "Lysa Tully Arryn", "House Arryn Characters (A Song of Ice and Fire)", "Petyr Baelish", "Aurane Waters", "Yohn Royce", "Ysilla Royce", "House Royce Characters (A Song of Ice and Fire)", "Lucas Blackwood", "Randyll Tarly", "Paxter Redwyne", "Monford Velaryon", "Basically ALL A Song of Ice and Fire Characters", "Roslin Frey", "Willas Tyrell", "Garlan Tyrell", "Desmera Redwyne"]', '["Action/Adventure", "Action & Romance", "Canon - A Song of Ice and Fire Series & Game of Thrones (TV) Combination", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Manipulation", "Politics", "Jon Snow is a Targaryen", "Jon Snow is Not Called Aegon", "Jon Snow Knows Something", "Weekly Updates"]', '- Jon Snow is the son of Rhaegar and Lyanna (not that he knows it in beginning) - Bastard who eventually learns the truth of who he is... wants nothing to do with it - Becomes lord of Moat Cailin and begins to grow and deal with many struggles to make the poorest land of the North, since it has been without a lord for so long, to become successful economically - One day, he will no longer be able to hide from his past. - Olenna Tyrell Plots - How the War of the 5 Kings should have happened - If Robb Stark didn’t be a complete political idiot UPDATED EVERY SATURDAY!')
('76423276', '2025-12-31', 'https://archiveofourown.org/works/76423276', 'Scraped', 'A Lioness In A Northern Court', 'Emilie_L_C , Scorpius6689', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Cersei Lannister/Jon Snow", "Ashara Dayne/Jon Snow"]', '["Jon Snow", "Cersei Lannister", "Tyrion Lannister", "Rhaegar Targaryen", "Lyanna Stark", "Rhaella Targaryen (Wife of Aerys II)", "Aerys II Targaryen", "Arthur Dayne", "Ashara Dayne"]', '["Alternate Universe - Canon Divergence", "Jon Snow is a Targaryen", "Seduction", "Fluff and Angst"]', 'While King Rhaegar and Queen Lyanna sit on the Iron Throne, a widowed and childless Cersei Lannister arrives at the Red Keep with a singular ambition: to secure her legacy through the heir, their son Prince Duncan Targaryen.')
('55165036', '2024-04-13', 'https://archiveofourown.org/works/55165036', 'Scraped', 'A Stark and his Ice (RE_WRITE)', 'Intherain487', '["Mature"]', '[]', '["A Song of Ice and Fire & Related Fandoms", "A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)"]', '["Ned Stark/Shaena Targaryen", "Catelyn Tully Stark/Ned Stark", "Robert Baratheon/Lyanna Stark", "Lyanna Stark/Rhaegar Targaryen", "Elia Martell/Rhaegar Targaryen", "Ashara Dayne/Brandon Stark", "Cersei Lannister/Jaime Lannister", "Cersei Lannister/Brandon Stark", "Oberyn Martell/Ellaria Sand", "Shaena Targaryen/Catelyn Tully Stark"]', '["Ned Stark", "Rickard Stark", "Brandon Stark", "Shaena Targaryen", "Robert Baratheon", "Jon Arryn", "Rhaegar Targaryen", "Aerys II Targaryen", "Rhaella Targaryen (Wife of Aerys II)", "Barristan Selmy", "Tywin Lannister", "Jaime Lannister", "Cersei Lannister", "Lyanna Stark", "Benjen Stark", "Arthur Dayne", "Thoros of Myr (A Song of Ice and Fire)", "Original Characters", "Original Catelyn Tully Stark/Ned Stark Child(ren)", "Willam Dustin", "Yohn Royce", "Elys Arryn", "Anya Waynwood", "House Hightower Characters (A Song of Ice and Fire)", "Mace Tyrell", "Leyton Hightower", "Baelor Hightower", "Olenna Tyrell", "House Redwyne Characters (A Song of Ice and Fire)", "Hoster Tully", "Brynden \\"Blackfish\\" Tully", "Catelyn Tully Stark", "Elia Martell", "Ashara Dayne", "Oberyn Martell", "Ellaria Sand"]', '["Ned Stark Needs a Hug", "Alternate Universe - Canon Divergence", "POV Ned Stark", "Pre-Robert\'s Rebellion Against the Targaryens", "The Vale of Arryn (A Song of Ice and Fire)", "Shaena Targaryen Lives"]', "In the icy wilderness of the North, a young Ned Stark discovers he possesses a mysterious power over ice. Terrified of the potential danger it poses to his loved ones, Ned grapples with his newfound abilities in secret. Haunted by guilt and burdened by his icy gift, Ned resolves to journey southward to seek answers and redemption. Along the way, he encounters allies and adversaries, each with their own motives and secrets. Amidst political intrigue and looming threats, Ned must navigate a treacherous path while concealing his true identity. As Ned delves deeper into the mysteries surrounding his powers, he uncovers ancient legends and forgotten truths that challenge his beliefs and shape his destiny. With the fate of the realm hanging in the balance, Ned must confront his fears and embrace his true heritage to fulfill his role in the unfolding saga of ice and fire. But as winter looms on the horizon and darkness gathers, Ned's journey is far from over, and the true test of his strength and honor is yet to come.")
('50992918', '2023-10-21', 'https://archiveofourown.org/works/50992918', 'Scraped', 'A Song of Three (Abandoned Version)', 'orphan_account', '["Mature"]', '["F/F", "F/M", "Gen", "Multi"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)", "A Song of Ice and Fire & Related Fandoms"]', '["Jon Snow/Sansa Stark", "Jon Snow/Daenerys Targaryen", "Sansa Stark/Daenerys Targaryen"]', '["Daenerys Targaryen", "Jon Snow", "Sansa Stark", "Ned Stark", "Robb Stark", "Catelyn Tully Stark", "Bran Stark", "Brynden \\"Bloodraven\\" Rivers", "Young Griff (ASoIaF)"]', '["R Plus L Equals J", "Prophetic dreams sometimes creepy sometimes not", "what is a threesome?", "Sometimes I just steal whole sentences from the book lmao", "Jonsa stuff comes first", "Then comes the threesome", "Its finally getting fun I swear", "jonsa", "Jonerys", "Slow Burn", "Jon does some shady shit", "i love sansa so much", "Soulmates", "Three hearts that beat as one", "Asoiaf lore is so cool", "book canon", "Jon Snow Doesn\'t Join the Night\'s Watch", "Jon Snow is a Targaryen", "Threesome - F/F/M", "but slow burn", "Jon Snow Goes to King\'s Landing", "dragon\'s egg", "High Fantasy", "No Harem", "This is not a Jon Wank fic", "Throuple", "Go read the fixed version", "THIS HAS BEEN ABANDONED", "And rewritten"]', '“Douse your tempers, Ser.” Barristan Selmy reminded him once more. “You swore an oath to the king the day he knighted you. You must honor it. Don’t act rashly just yet, your father would not approve of it.” “What should I do then, Ser Barristan?” Jon asked with despair. “Stand by your family, wait for Lord Stark.” He counseled. “And remember your vows.” Ser Barristan had once been his hero, now not one of his words could bring him any comfort. Unbesought, Jon’s fury flared back to this knight in white, as shining as dawn. “As you stood beside Mad Aerys when he murdered my grandfather? My uncle? How idly did you stand then, ser? How straight was your back?” He might as well have slapped him in the face. Barristan the Bold turned back a step. He spoke flatly, “Still, you and your family are in my prayers.” “You may keep them to yourself,” Jon told him. “I was a bastard before I was a knight. And I remember my vows.”')
('73894251', '2025-11-08', 'https://archiveofourown.org/works/73894251', 'Scraped', 'A Song of Three', 'NotMexicanSven', '["Mature"]', '["F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)"]', '["Jon Snow/Sansa Stark", "Jon Snow/Daenerys Targaryen", "Sansa Stark/Daenerys Targaryen", "Jon Snow/Sansa Stark/Daenerys Targaryen"]', '["Jon Snow", "Daenerys Targaryen", "Sansa Stark", "Ned Stark", "Catelyn Tully Stark", "Brynden \\"Bloodraven\\" Rivers", "Young Griff (ASoIaF)", "Robb Stark"]', '["R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "book canon", "Slow Burn", "Soulmates", "Three hearts that beat as one", "Jon Snow Goes to King\'s Landing", "Jon Snow Doesn\'t Join the Night\'s Watch", "What if dragon egg?", "High Fantasy", "No Harem", "Throuple", "Threesome", "Jon does some shady shit...again", "No Bashing", "rewritten", "I still love Sansa way too much"]', "“Why does he have a statue?” Jon Snow asked in a callow voice, though it made Ned lift an eyebrow. The boy was truly observant. He had realized that, by tradition, only lords and kings had their likenesses sculpted in stone for their eternal vigil. “I do not know, son. But look where he rests. Perhaps Torrhen wanted his brother to lie beside him, even when death comes claim.” “Or maybe Brandon wanted to protect his brother, even after death,” Jon said, as serious as a ten-year-old boy could be. “Father, I no longer wish to join the Watch.” Jon Snow spurns the Night's Watch. Daenerys Targaryen dreams of wolves. Sansa Stark dreams of dragons. Three unaware souls, linked by fate and causality. Somewhere, a song for three has begun to play.")
('62910172', '2025-01-17', 'https://archiveofourown.org/works/62910172', 'Scraped', 'Silver Spoon', 'franzkafkagf', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin"]', '["Jon Snow & Rhaegar Targaryen", "Elia Martell/Rhaegar Targaryen", "Elia Martell & Jon Snow", "Jon Snow & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)", "Benjen Stark & Robb Stark", "Jon Snow & Daenerys Targaryen", "Elia Martell & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)"]', '["Jon Snow", "Daenerys Targaryen", "Rhaenys Targaryen (Daughter of Elia)", "Elia Martell", "Rhaegar Targaryen", "Aegon Targaryen (Son of Elia)", "Margaery Tyrell", "Benjen Stark", "Robb Stark", "Tyrion Lannister", "Cersei Lannister", "Arthur Dayne", "Jaime Lannister", "The Others | White Walker Character(s) (A Song of Ice and Fire)", "Jon Snow ", " Rhaegar Targaryen", "Elia Martell ", " Jon Snow", " Aegon Targaryen (Son of Elia) ", " Rhaenys Targaryen (Daughter of Elia)", "Benjen Stark ", " Robb Stark", " Daenerys Targaryen"]', '["King Rhaegar Targaryen", "Robert\'s Rebellion Fails | Rhaegar Targaryen Wins", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Alternate Universe - Reincarnation", "Post-Book 5: A Dance with Dragons (A Song of Ice and Fire)", "Jon Snow\'s Name is Aemon", "Character Study", "Epic", "House Blackfyre (A Song of Ice and Fire)"]', 'When the third dagger took him between the shoulder blades, he gave a grunt and fell face-first into the snow. He never felt the fourth knife. Only the cold… And then, sunlight touched his face. Warm, unfamiliar, impossibly bright. Jon Snow, Lord Commander of the Night’s Watch, had died in the frozen wastes of the Wall. And yet, he wakes. No longer at Castle Black, no longer bleeding into the snow, he finds himself in a bed of silk, in a city he has never set foot in but knows from stories. ☆ In which Jon Snow dies in the cold and wakes up to find that people call him Aemon and Rhaegar Targaryen is king.')
('84723811', '2026-05-12T13:05:34Z', 'https://archiveofourown.org/works/84723811', 'New', 'The rot was in this house before I dwelled here and it shall be here when I am in the ground.', 'youngjusticewriter', None, None, None, None, None, None, None)
('84723496', '2026-05-12T12:58:30Z', 'https://archiveofourown.org/works/84723496', 'Scraped', 'Beneath the Black Dragon', 'Dorumuk', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Original Blackfyre Character/Ashara Dayne"]', '["Original Blackfyre Character(s)", "Original Male Character(s)", "House Blackfyre Characters (A Song of Ice and Fire)", "Aerys II Targaryen", "Rhaegar Targaryen", "Elia Martell", "Lyanna Stark", "Ned Stark", "Robert Baratheon", "Stannis Baratheon", "Ashara Dayne", "Arthur Dayne", "Brandon Stark", "Rickard Stark", "Original Blackfyre Character"]', '["Alternate Universe - Canon Divergence", "House Blackfyre (A Song of Ice and Fire)", "Targaryen Restoration", "Essos (A Song of Ice and Fire)", "Elia Martell Lives", "Rhaenys Targaryen (Daughter of Elia) Lives", "Aegon Targaryen (Son of Elia) Lives", "Rhaella Targaryen (Wife of Aerys II) Lives", "Lyanna Stark Lives", "Brandon Stark Lives"]', 'Kang Doyun died at his desk in Seoul, crushed beneath deadlines, defect reports, and a life that had long since learned to call exhaustion normal. Valar Blackfyre should have died in Tyrosh, thrown from his horse before the world ever learned his hidden name. Instead, both men wake in the same body. One is a modern engineer with memories of a world where chains are invisible. The other is the secret son of Maelys Blackfyre, raised on old wounds, forbidden names, and the bitter inheritance of the black dragon. Across the Narrow Sea, the Targaryen dynasty has begun to tremble. In Tyrosh, a black ember draws breath. Their first plan is simple. Do not die.')
('84723001', '2026-05-12T12:40:34Z', 'https://archiveofourown.org/works/84723001', 'Scraped', 'Hands do not dream', 'Nessie (Miss_Bowen)', '["General Audiences"]', '["F/M"]', '["Game of Thrones (TV)"]', '["Jaime Lannister/Brienne of Tarth"]', '["Jaime Lannister", "Brienne of Tarth"]', '["Banter", "Mild Hurt/Comfort", "Short", "Permanent Injury"]', 'This is a very short (and kind of irrelevant) short look into Jaime/Brienne. Spoilers for early/mid season 3 GoT.')

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

all = c.execute('''
      Select * from my_bookmarks
''')

for row in all:
    print(row)

conn.close()

('75267501',)
('56181721',)
('81993896',)
('76423276',)
('55165036',)
('50992918',)
('73894251',)
('62910172',)

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

all = c.execute('''
      Select * from public_bookmarks
''')

for row in all:
    print(row)

conn.close()

RSS feed to all works sql

In [ ]:
!pip install feedparser==6.0.12
import feedparser

Collecting feedparser==6.0.12
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting sgmllib3k (from feedparser==6.0.12)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 4.7 MB/s eta 0:00:00
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=eaba131cd6b06ed272357a28c8add425f42860506280d195a1bdd3297cb1c698
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0

In [ ]:
# import sqlite3
# def add_work_to_db(c, work_id, published, link, status, title, author):
#     try:
#         c.execute('''
#             INSERT INTO all_works (id, published, link, status, title, author)
#             VALUES (?, ?, ?, ?, ?, ?)
#         ''', (work_id, published, link, status, title, author))
#         print(f"Successfully added work {work_id} to the database.")
#     except sqlite3.IntegrityError:
#         print(f"Work {work_id} already exists in the database. Skipping.")
#     except Exception as e:
#         print(f"Error adding work {work_id}: {e}")
def add_work_to_db(c, work_id, published, link, status, title, author):
    c.execute('''
        INSERT OR IGNORE INTO all_works
        (id, published, link, status, title, author)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (work_id, published, link, status, title, author))

    if c.rowcount == 0:
        print(f"Work {work_id} already exists in the database. Skipping.")
    else:
        print(f"Successfully added work {work_id} to the database.")

Get new works from RSS feeds to add the DB

In [ ]:
import feedparser
feed_url = "https://archiveofourown.org/tags/2007008/feed.atom"

feed = feedparser.parse(feed_url)

conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()


for entry in feed.entries:
    work_id = extract_work_id(entry.get("link"))
    published = entry.get("published")
    link = entry.get("link")
    title = entry.get("title")
    author = entry.get("author")
    status = "New"

    if work_id:
        add_work_to_db(c, work_id, published, link, status, title, author)
    else:
        print(f"Could not extract work ID for entry: {link}")
conn.commit()
conn.close()

Successfully added work 84825481 to the database.
Successfully added work 84823306 to the database.
Successfully added work 84821151 to the database.
Successfully added work 84819631 to the database.
Successfully added work 84819371 to the database.
Successfully added work 84818236 to the database.
Successfully added work 84817521 to the database.
Successfully added work 84817486 to the database.
Successfully added work 84816756 to the database.
Successfully added work 84814161 to the database.
Successfully added work 84810946 to the database.
Successfully added work 84810556 to the database.
Successfully added work 84808636 to the database.
Successfully added work 84807446 to the database.
Successfully added work 84805866 to the database.
Successfully added work 84805206 to the database.
Successfully added work 84804186 to the database.
Successfully added work 84803571 to the database.
Successfully added work 84802621 to the database.
Successfully added work 84802421 to the database.
Successfully added work 84802046 to the database.
Successfully added work 84802026 to the database.
Successfully added work 84800266 to the database.
Successfully added work 84798981 to the database.

In [ ]:
import sqlite3
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

all = c.execute('''
      Select * from all_works
''')

for row in all:
    print(row)

conn.close()

('75267501', '2025-12-21', 'https://archiveofourown.org/works/75267501', 'Scraped', 'the wolf and the fox', 'GoddessOfWriting , TheDauntless (GoddessOfWriting)', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Jon Snow/Original Female Character(s)", "Jon Snow & Original Female Character(s)", "Jon Snow & Arya Stark & Bran Stark & Rickon Stark & Robb Stark & Sansa Stark", "Ghost | Jon Snow\'s Direwolf & Jon Snow", "Catelyn Tully Stark/Ned Stark", "Jon Snow & Ned Stark"]', '["Original Female Character(s)", "Characters From The North (A Song of Ice and Fire)", "Jon Snow", "Ghost | Jon Snow\'s Direwolf", "Arya Stark", "Nymeria | Arya Stark\'s Direwolf", "Sansa Stark", "Robb Stark", "Theon Greyjoy", "Bran Stark", "Rickon Stark", "Summer | Bran Stark\'s Direwolf", "Shaggydog | Rickon Stark\'s Direwolf", "Ned Stark", "Catelyn Tully Stark", "Maester Luwin of Winterfell (A Song of Ice and Fire)", "Rodrik Cassel", "Jory Cassel", "Harwin the Winterfell Guard (A Song of Ice and Fire)", "Robert Baratheon", "Joffrey Baratheon", "Cersei Lannister", "Tyrion Lannister", "Jon Snow ", " Original Female Character(s)", " Arya Stark ", " Bran Stark ", " Rickon Stark ", " Robb Stark ", " Sansa Stark", "Ghost ", " Jon Snow\'s Direwolf ", " Jon Snow", " Ned Stark"]', '["Original Noble House (A Song of Ice and Fire)", "Northern Culture & Customs (A Song of Ice and Fire)", "The North (A Song of Ice and Fire)", "The Wolfswood (A Song of Ice and Fire)", "Winterfell (A Song of Ice and Fire)", "House Stark (A Song of Ice and Fire)", "Author Supports House Stark (A Song of Ice and Fire)", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Jon Snow Doesn\'t Join the Night\'s Watch", "Married Jon Snow", "Childhood Friends to Lovers", "Hunters & Hunting", "Wargs & Warging (A Song of Ice and Fire)", "Ghost | Jon Snow\'s Direwolf is a Good Boy", "Joffrey Baratheon Being an Asshole", "Robert Baratheon Being an Asshole", "Catelyn Tully Stark is Not Nice", "Westerosi Politics (A Song of Ice and Fire)", "The Old Gods (A Song of Ice and Fire)", "Weirwood Trees (A Song of Ice and Fire)", "Skinchangers & Skinchanging (A Song of Ice and Fire)", "Mentioned Rhaegar Targaryen", "Mentioned Lyanna Stark"]', "The first time she met Jon Snow, they were twelve years old and he accidentally walked into her trap. ... From his uncomfortable position suspended in the air, Jon looks down at the girl standing with her hands on her hips. She is around his age, with bark brown hair in two braids, forest green eyes, and dressed in a brown hunting ensemble. “Be quiet, stupid. You scared away the gods themselves!” The indignation of being caught in a trap by a girl catches up to him. “Let me down! You shouldn’t have put your stupid trap there.” “How else are you meant to catch game?” She yells up at him before untangling a rope and Jon falls to the ground with a thud. --- House Rennard of the Wolfswood has long stood by House Stark, joined together by the large stretches of the forest and their inhabitants. They are known for raising excellent hunters, trappers, hawkers and gamekeepers - most of them women, for there has never been a ruling lord in their entire history. Jon Snow walks into Dyana Rennard's trap one day and falls head over heels - literally.")
('56181721', '2026-05-04', 'https://archiveofourown.org/works/56181721', 'Scraped', 'The Prince and the King', 'HimmeltheHero', '["Mature"]', '["Gen", "F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Elia Martell/Rhaegar Targaryen", "Ashara Dayne/Ned Stark", "past Lyanna Stark/Rhaegar Targaryen - Relationship", "Jon Snow/Mya Stone", "Rhaegar Targaryen/Margaery Tyrell"]', '["Rhaegar Targaryen", "Aerys II Targaryen", "Tywin Lannister", "Jon Snow", "Aegon Targaryen (Son of Elia)", "Rhaenys Targaryen (Daughter of Elia)", "Elia Martell", "Oswell Whent", "Richard Lonmouth", "Margaery Tyrell", "Cersei Lannister", "Viserys Targaryen (Brother of Daenerys)", "Daenerys Targaryen", "Ned Stark", "Rickard Stark", "Robert Baratheon", "Rhaella Targaryen (Wife of Aerys II)", "Ashara Dayne", "Arthur Dayne", "Mya Stone", "Myles Mooton", "Jon Connington", "Stannis Baratheon", "past Lyanna Stark", "Rhaegar Targaryen - Relationship"]', '["Alternate Universe - Canon Divergence", "No Robert\'s Rebellion | Robert Baratheon Never Rebels Against the Targaryens", "Canon-Typical Violence", "Jon Snow is a Targaryen", "Politics", "Dragons", "Targaryen-on-Targaryen violence"]', '“Treason and turmoil followed, as night follows day, ending at Summerhall in sorcery, fire and grief.” Aegon the Unlikely and most of his kin died at Summerhall, but not before managing to bring dragons back into the world. With their greatest power restored to them, House Targaryen begins a new era of dominance over the Seven Kingdoms. But with King Aerys slipping into madness and Prince Rhaegar lost in his prophecies the dragons once again dance…')
('81993896', '2026-02-16', 'https://archiveofourown.org/works/81993896', 'Scraped', 'Survive, Endure, Rise', 'An_Anonymous_Writer', '["Mature"]', '["F/M", "Gen"]', '["Game of Thrones (TV)", "A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Jon Snow/Margaery Tyrell", "Ysilla Royce/Robb Stark", "Catelyn Tully Stark/Ned Stark", "Roslin Frey/Edmure Tully", "Sansa Stark/Willas Tyrell", "Garlan Tyrell/Desmera Redwyne"]', '["Jon Snow", "Robb Stark", "Ned Stark", "Catelyn Tully Stark", "Arya Stark", "Sansa Stark", "Brandon Stark", "Rickon Stark", "Arthur Dayne", "Margaery Tyrell", "Olenna Tyrell", "Loras Tyrell", "Mace Tyrell", "House Tyrell Characters (A Song of Ice and Fire)", "House Stark Characters (A Song of Ice and Fire)", "Brynden \\"Blackfish\\" Tully", "Davos Seaworth", "Jorah Mormont", "Jaime Lannister", "Tyrion Lannister", "Cersei Lannister", "Tywin Lannister", "House Lannister Characters (A Song of Ice and Fire)", "Robert Baratheon", "Joffrey Baratheon", "Stannis Baratheon", "Renly Baratheon", "Myrcella Baratheon", "House Baratheon Characters (A Song of Ice and Fire)", "House Martell Characters (A Song of Ice and Fire)", "Edmure Tully", "Hoster Tully", "House Tully Characters (A Song of Ice and Fire)", "Lysa Tully Arryn", "House Arryn Characters (A Song of Ice and Fire)", "Petyr Baelish", "Aurane Waters", "Yohn Royce", "Ysilla Royce", "House Royce Characters (A Song of Ice and Fire)", "Lucas Blackwood", "Randyll Tarly", "Paxter Redwyne", "Monford Velaryon", "Basically ALL A Song of Ice and Fire Characters", "Roslin Frey", "Willas Tyrell", "Garlan Tyrell", "Desmera Redwyne"]', '["Action/Adventure", "Action & Romance", "Canon - A Song of Ice and Fire Series & Game of Thrones (TV) Combination", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Manipulation", "Politics", "Jon Snow is a Targaryen", "Jon Snow is Not Called Aegon", "Jon Snow Knows Something", "Weekly Updates"]', '- Jon Snow is the son of Rhaegar and Lyanna (not that he knows it in beginning) - Bastard who eventually learns the truth of who he is... wants nothing to do with it - Becomes lord of Moat Cailin and begins to grow and deal with many struggles to make the poorest land of the North, since it has been without a lord for so long, to become successful economically - One day, he will no longer be able to hide from his past. - Olenna Tyrell Plots - How the War of the 5 Kings should have happened - If Robb Stark didn’t be a complete political idiot UPDATED EVERY SATURDAY!')
('76423276', '2025-12-31', 'https://archiveofourown.org/works/76423276', 'Scraped', 'A Lioness In A Northern Court', 'Emilie_L_C , Scorpius6689', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Cersei Lannister/Jon Snow", "Ashara Dayne/Jon Snow"]', '["Jon Snow", "Cersei Lannister", "Tyrion Lannister", "Rhaegar Targaryen", "Lyanna Stark", "Rhaella Targaryen (Wife of Aerys II)", "Aerys II Targaryen", "Arthur Dayne", "Ashara Dayne"]', '["Alternate Universe - Canon Divergence", "Jon Snow is a Targaryen", "Seduction", "Fluff and Angst"]', 'While King Rhaegar and Queen Lyanna sit on the Iron Throne, a widowed and childless Cersei Lannister arrives at the Red Keep with a singular ambition: to secure her legacy through the heir, their son Prince Duncan Targaryen.')
('55165036', '2024-04-13', 'https://archiveofourown.org/works/55165036', 'Scraped', 'A Stark and his Ice (RE_WRITE)', 'Intherain487', '["Mature"]', '[]', '["A Song of Ice and Fire & Related Fandoms", "A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)"]', '["Ned Stark/Shaena Targaryen", "Catelyn Tully Stark/Ned Stark", "Robert Baratheon/Lyanna Stark", "Lyanna Stark/Rhaegar Targaryen", "Elia Martell/Rhaegar Targaryen", "Ashara Dayne/Brandon Stark", "Cersei Lannister/Jaime Lannister", "Cersei Lannister/Brandon Stark", "Oberyn Martell/Ellaria Sand", "Shaena Targaryen/Catelyn Tully Stark"]', '["Ned Stark", "Rickard Stark", "Brandon Stark", "Shaena Targaryen", "Robert Baratheon", "Jon Arryn", "Rhaegar Targaryen", "Aerys II Targaryen", "Rhaella Targaryen (Wife of Aerys II)", "Barristan Selmy", "Tywin Lannister", "Jaime Lannister", "Cersei Lannister", "Lyanna Stark", "Benjen Stark", "Arthur Dayne", "Thoros of Myr (A Song of Ice and Fire)", "Original Characters", "Original Catelyn Tully Stark/Ned Stark Child(ren)", "Willam Dustin", "Yohn Royce", "Elys Arryn", "Anya Waynwood", "House Hightower Characters (A Song of Ice and Fire)", "Mace Tyrell", "Leyton Hightower", "Baelor Hightower", "Olenna Tyrell", "House Redwyne Characters (A Song of Ice and Fire)", "Hoster Tully", "Brynden \\"Blackfish\\" Tully", "Catelyn Tully Stark", "Elia Martell", "Ashara Dayne", "Oberyn Martell", "Ellaria Sand"]', '["Ned Stark Needs a Hug", "Alternate Universe - Canon Divergence", "POV Ned Stark", "Pre-Robert\'s Rebellion Against the Targaryens", "The Vale of Arryn (A Song of Ice and Fire)", "Shaena Targaryen Lives"]', "In the icy wilderness of the North, a young Ned Stark discovers he possesses a mysterious power over ice. Terrified of the potential danger it poses to his loved ones, Ned grapples with his newfound abilities in secret. Haunted by guilt and burdened by his icy gift, Ned resolves to journey southward to seek answers and redemption. Along the way, he encounters allies and adversaries, each with their own motives and secrets. Amidst political intrigue and looming threats, Ned must navigate a treacherous path while concealing his true identity. As Ned delves deeper into the mysteries surrounding his powers, he uncovers ancient legends and forgotten truths that challenge his beliefs and shape his destiny. With the fate of the realm hanging in the balance, Ned must confront his fears and embrace his true heritage to fulfill his role in the unfolding saga of ice and fire. But as winter looms on the horizon and darkness gathers, Ned's journey is far from over, and the true test of his strength and honor is yet to come.")
('50992918', '2023-10-21', 'https://archiveofourown.org/works/50992918', 'Scraped', 'A Song of Three (Abandoned Version)', 'orphan_account', '["Mature"]', '["F/F", "F/M", "Gen", "Multi"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)", "A Song of Ice and Fire & Related Fandoms"]', '["Jon Snow/Sansa Stark", "Jon Snow/Daenerys Targaryen", "Sansa Stark/Daenerys Targaryen"]', '["Daenerys Targaryen", "Jon Snow", "Sansa Stark", "Ned Stark", "Robb Stark", "Catelyn Tully Stark", "Bran Stark", "Brynden \\"Bloodraven\\" Rivers", "Young Griff (ASoIaF)"]', '["R Plus L Equals J", "Prophetic dreams sometimes creepy sometimes not", "what is a threesome?", "Sometimes I just steal whole sentences from the book lmao", "Jonsa stuff comes first", "Then comes the threesome", "Its finally getting fun I swear", "jonsa", "Jonerys", "Slow Burn", "Jon does some shady shit", "i love sansa so much", "Soulmates", "Three hearts that beat as one", "Asoiaf lore is so cool", "book canon", "Jon Snow Doesn\'t Join the Night\'s Watch", "Jon Snow is a Targaryen", "Threesome - F/F/M", "but slow burn", "Jon Snow Goes to King\'s Landing", "dragon\'s egg", "High Fantasy", "No Harem", "This is not a Jon Wank fic", "Throuple", "Go read the fixed version", "THIS HAS BEEN ABANDONED", "And rewritten"]', '“Douse your tempers, Ser.” Barristan Selmy reminded him once more. “You swore an oath to the king the day he knighted you. You must honor it. Don’t act rashly just yet, your father would not approve of it.” “What should I do then, Ser Barristan?” Jon asked with despair. “Stand by your family, wait for Lord Stark.” He counseled. “And remember your vows.” Ser Barristan had once been his hero, now not one of his words could bring him any comfort. Unbesought, Jon’s fury flared back to this knight in white, as shining as dawn. “As you stood beside Mad Aerys when he murdered my grandfather? My uncle? How idly did you stand then, ser? How straight was your back?” He might as well have slapped him in the face. Barristan the Bold turned back a step. He spoke flatly, “Still, you and your family are in my prayers.” “You may keep them to yourself,” Jon told him. “I was a bastard before I was a knight. And I remember my vows.”')
('73894251', '2025-11-08', 'https://archiveofourown.org/works/73894251', 'Scraped', 'A Song of Three', 'NotMexicanSven', '["Mature"]', '["F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)"]', '["Jon Snow/Sansa Stark", "Jon Snow/Daenerys Targaryen", "Sansa Stark/Daenerys Targaryen", "Jon Snow/Sansa Stark/Daenerys Targaryen"]', '["Jon Snow", "Daenerys Targaryen", "Sansa Stark", "Ned Stark", "Catelyn Tully Stark", "Brynden \\"Bloodraven\\" Rivers", "Young Griff (ASoIaF)", "Robb Stark"]', '["R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "book canon", "Slow Burn", "Soulmates", "Three hearts that beat as one", "Jon Snow Goes to King\'s Landing", "Jon Snow Doesn\'t Join the Night\'s Watch", "What if dragon egg?", "High Fantasy", "No Harem", "Throuple", "Threesome", "Jon does some shady shit...again", "No Bashing", "rewritten", "I still love Sansa way too much"]', "“Why does he have a statue?” Jon Snow asked in a callow voice, though it made Ned lift an eyebrow. The boy was truly observant. He had realized that, by tradition, only lords and kings had their likenesses sculpted in stone for their eternal vigil. “I do not know, son. But look where he rests. Perhaps Torrhen wanted his brother to lie beside him, even when death comes claim.” “Or maybe Brandon wanted to protect his brother, even after death,” Jon said, as serious as a ten-year-old boy could be. “Father, I no longer wish to join the Watch.” Jon Snow spurns the Night's Watch. Daenerys Targaryen dreams of wolves. Sansa Stark dreams of dragons. Three unaware souls, linked by fate and causality. Somewhere, a song for three has begun to play.")
('62910172', '2025-01-17', 'https://archiveofourown.org/works/62910172', 'Scraped', 'Silver Spoon', 'franzkafkagf', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin"]', '["Jon Snow & Rhaegar Targaryen", "Elia Martell/Rhaegar Targaryen", "Elia Martell & Jon Snow", "Jon Snow & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)", "Benjen Stark & Robb Stark", "Jon Snow & Daenerys Targaryen", "Elia Martell & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)"]', '["Jon Snow", "Daenerys Targaryen", "Rhaenys Targaryen (Daughter of Elia)", "Elia Martell", "Rhaegar Targaryen", "Aegon Targaryen (Son of Elia)", "Margaery Tyrell", "Benjen Stark", "Robb Stark", "Tyrion Lannister", "Cersei Lannister", "Arthur Dayne", "Jaime Lannister", "The Others | White Walker Character(s) (A Song of Ice and Fire)", "Jon Snow ", " Rhaegar Targaryen", "Elia Martell ", " Jon Snow", " Aegon Targaryen (Son of Elia) ", " Rhaenys Targaryen (Daughter of Elia)", "Benjen Stark ", " Robb Stark", " Daenerys Targaryen"]', '["King Rhaegar Targaryen", "Robert\'s Rebellion Fails | Rhaegar Targaryen Wins", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Alternate Universe - Reincarnation", "Post-Book 5: A Dance with Dragons (A Song of Ice and Fire)", "Jon Snow\'s Name is Aemon", "Character Study", "Epic", "House Blackfyre (A Song of Ice and Fire)"]', 'When the third dagger took him between the shoulder blades, he gave a grunt and fell face-first into the snow. He never felt the fourth knife. Only the cold… And then, sunlight touched his face. Warm, unfamiliar, impossibly bright. Jon Snow, Lord Commander of the Night’s Watch, had died in the frozen wastes of the Wall. And yet, he wakes. No longer at Castle Black, no longer bleeding into the snow, he finds himself in a bed of silk, in a city he has never set foot in but knows from stories. ☆ In which Jon Snow dies in the cold and wakes up to find that people call him Aemon and Rhaegar Targaryen is king.')
('84723811', '2026-05-12T13:05:34Z', 'https://archiveofourown.org/works/84723811', 'New', 'The rot was in this house before I dwelled here and it shall be here when I am in the ground.', 'youngjusticewriter', None, None, None, None, None, None, None)
('84723496', '2026-05-12T12:58:30Z', 'https://archiveofourown.org/works/84723496', 'Scraped', 'Beneath the Black Dragon', 'Dorumuk', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Original Blackfyre Character/Ashara Dayne"]', '["Original Blackfyre Character(s)", "Original Male Character(s)", "House Blackfyre Characters (A Song of Ice and Fire)", "Aerys II Targaryen", "Rhaegar Targaryen", "Elia Martell", "Lyanna Stark", "Ned Stark", "Robert Baratheon", "Stannis Baratheon", "Ashara Dayne", "Arthur Dayne", "Brandon Stark", "Rickard Stark", "Original Blackfyre Character"]', '["Alternate Universe - Canon Divergence", "House Blackfyre (A Song of Ice and Fire)", "Targaryen Restoration", "Essos (A Song of Ice and Fire)", "Elia Martell Lives", "Rhaenys Targaryen (Daughter of Elia) Lives", "Aegon Targaryen (Son of Elia) Lives", "Rhaella Targaryen (Wife of Aerys II) Lives", "Lyanna Stark Lives", "Brandon Stark Lives"]', 'Kang Doyun died at his desk in Seoul, crushed beneath deadlines, defect reports, and a life that had long since learned to call exhaustion normal. Valar Blackfyre should have died in Tyrosh, thrown from his horse before the world ever learned his hidden name. Instead, both men wake in the same body. One is a modern engineer with memories of a world where chains are invisible. The other is the secret son of Maelys Blackfyre, raised on old wounds, forbidden names, and the bitter inheritance of the black dragon. Across the Narrow Sea, the Targaryen dynasty has begun to tremble. In Tyrosh, a black ember draws breath. Their first plan is simple. Do not die.')
('84723001', '2026-05-12T12:40:34Z', 'https://archiveofourown.org/works/84723001', 'Scraped', 'Hands do not dream', 'Nessie (Miss_Bowen)', '["General Audiences"]', '["F/M"]', '["Game of Thrones (TV)"]', '["Jaime Lannister/Brienne of Tarth"]', '["Jaime Lannister", "Brienne of Tarth"]', '["Banter", "Mild Hurt/Comfort", "Short", "Permanent Injury"]', 'This is a very short (and kind of irrelevant) short look into Jaime/Brienne. Spoilers for early/mid season 3 GoT.')

Get 'new' works from 'all_works' that are older than k days to be scraped and enrich the DB

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()



overdue_link_rows = c.execute('''
      Select link from all_works
      where status = 'New'
''').fetchall()

overdue_link_list = [row[0] for row in overdue_link_rows]

conn.close()

In [ ]:
overdue_link_list

['https://archiveofourown.org/works/84723811',
 'https://archiveofourown.org/works/84723496',
 'https://archiveofourown.org/works/84723001',
 'https://archiveofourown.org/works/84722136',
 'https://archiveofourown.org/works/84721256',
 'https://archiveofourown.org/works/84720706',
 'https://archiveofourown.org/works/84719016',
 'https://archiveofourown.org/works/84715966',
 'https://archiveofourown.org/works/84715021',
 'https://archiveofourown.org/works/84714196',
 'https://archiveofourown.org/works/84714186',
 'https://archiveofourown.org/works/84711981',
 'https://archiveofourown.org/works/84711126',
 'https://archiveofourown.org/works/84711101',
 'https://archiveofourown.org/works/84709216',
 'https://archiveofourown.org/works/84708881',
 'https://archiveofourown.org/works/84708701',
 'https://archiveofourown.org/works/84708291',
 'https://archiveofourown.org/works/84705176',
 'https://archiveofourown.org/works/84702331',
 'https://archiveofourown.org/works/84702261',
 'https://archiveofourown.org/works/84701301',
 'https://archiveofourown.org/works/84699031',
 'https://archiveofourown.org/works/84696726',
 'https://archiveofourown.org/works/84769896',
 'https://archiveofourown.org/works/84765921',
 'https://archiveofourown.org/works/84763896',
 'https://archiveofourown.org/works/84762276',
 'https://archiveofourown.org/works/84761826',
 'https://archiveofourown.org/works/84761796',
 'https://archiveofourown.org/works/84761471',
 'https://archiveofourown.org/works/84759696',
 'https://archiveofourown.org/works/84758166',
 'https://archiveofourown.org/works/84757686',
 'https://archiveofourown.org/works/84755856',
 'https://archiveofourown.org/works/84752771',
 'https://archiveofourown.org/works/84751816',
 'https://archiveofourown.org/works/84751086',
 'https://archiveofourown.org/works/84749796',
 'https://archiveofourown.org/works/84748536',
 'https://archiveofourown.org/works/84745361',
 'https://archiveofourown.org/works/84744936',
 'https://archiveofourown.org/works/84744381',
 'https://archiveofourown.org/works/84743746',
 'https://archiveofourown.org/works/84742296',
 'https://archiveofourown.org/works/84741426',
 'https://archiveofourown.org/works/84738976',
 'https://archiveofourown.org/works/84737881',
 'https://archiveofourown.org/works/84737721']

In [ ]:
for link in overdue_link_list:
    print(link)

https://archiveofourown.org/works/84723811
https://archiveofourown.org/works/84723496
https://archiveofourown.org/works/84723001
https://archiveofourown.org/works/84722136
https://archiveofourown.org/works/84721256
https://archiveofourown.org/works/84720706
https://archiveofourown.org/works/84719016
https://archiveofourown.org/works/84715966
https://archiveofourown.org/works/84715021
https://archiveofourown.org/works/84714196
https://archiveofourown.org/works/84714186
https://archiveofourown.org/works/84711981
https://archiveofourown.org/works/84711126
https://archiveofourown.org/works/84711101
https://archiveofourown.org/works/84709216
https://archiveofourown.org/works/84708881
https://archiveofourown.org/works/84708701
https://archiveofourown.org/works/84708291
https://archiveofourown.org/works/84705176
https://archiveofourown.org/works/84702331
https://archiveofourown.org/works/84702261
https://archiveofourown.org/works/84701301
https://archiveofourown.org/works/84699031
https://archiveofourown.org/works/84696726
https://archiveofourown.org/works/84769896
https://archiveofourown.org/works/84765921
https://archiveofourown.org/works/84763896
https://archiveofourown.org/works/84762276
https://archiveofourown.org/works/84761826
https://archiveofourown.org/works/84761796
https://archiveofourown.org/works/84761471
https://archiveofourown.org/works/84759696
https://archiveofourown.org/works/84758166
https://archiveofourown.org/works/84757686
https://archiveofourown.org/works/84755856
https://archiveofourown.org/works/84752771
https://archiveofourown.org/works/84751816
https://archiveofourown.org/works/84751086
https://archiveofourown.org/works/84749796
https://archiveofourown.org/works/84748536
https://archiveofourown.org/works/84745361
https://archiveofourown.org/works/84744936
https://archiveofourown.org/works/84744381
https://archiveofourown.org/works/84743746
https://archiveofourown.org/works/84742296
https://archiveofourown.org/works/84741426
https://archiveofourown.org/works/84738976
https://archiveofourown.org/works/84737881
https://archiveofourown.org/works/84737721

In [ ]:
collect_and_update_with_new_works(overdue_link_list, False)

Fetching work: https://archiveofourown.org/works/84723811
Fetch failed for https://archiveofourown.org/works/84723811. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84723811.
Skipping explicit work: https://archiveofourown.org/works/84723811
Fetching work: https://archiveofourown.org/works/84723496
Fetch successful for https://archiveofourown.org/works/84723496.
Work 84723496 updated with tags.
Work 84723496 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84723001
Fetch failed for https://archiveofourown.org/works/84723001. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84723001.
Work 84723001 updated with tags.
Work 84723001 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84722136
Fetch successful for https://archiveofourown.org/works/84722136.
Work 84722136 updated with tags.
Work 84722136 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84721256
Fetch successful for https://archiveofourown.org/works/84721256.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84721256/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84721256/bookmarks?page=1.
Work 84721256 updated with tags.
Work 84721256 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84720706
Fetch successful for https://archiveofourown.org/works/84720706.
Work 84720706 updated with tags.
Work 84720706 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84719016
Fetch successful for https://archiveofourown.org/works/84719016.
Work 84719016 updated with tags.
Work 84719016 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84715966
Fetch successful for https://archiveofourown.org/works/84715966.
Skipping explicit work: https://archiveofourown.org/works/84715966
Fetching work: https://archiveofourown.org/works/84715021
Fetch failed for https://archiveofourown.org/works/84715021. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/84715021. Retrying in 4.0s...
Fetch successful for https://archiveofourown.org/works/84715021.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84715021/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84715021/bookmarks?page=1.
Work 84715021 updated with tags.
Work 84715021 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84714196
Fetch successful for https://archiveofourown.org/works/84714196.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84714196/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84714196/bookmarks?page=1.
Work 84714196 updated with tags.
Work 84714196 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84714186
Fetch failed for https://archiveofourown.org/works/84714186. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/84714186. Retrying in 4.0s...
Error fetching work https://archiveofourown.org/works/84714186: Failed to fetch https://archiveofourown.org/works/84714186 after 3 attempts: HTTPSConnectionPool(host='archiveofourown.org', port=443): Read timed out. (read timeout=20). Skipping this work.
Fetching work: https://archiveofourown.org/works/84711981
Fetch successful for https://archiveofourown.org/works/84711981.
Skipping explicit work: https://archiveofourown.org/works/84711981
Fetching work: https://archiveofourown.org/works/84711126
Fetch successful for https://archiveofourown.org/works/84711126.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84711126/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84711126/bookmarks?page=1.
Work 84711126 updated with tags.
Work 84711126 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84711101
Fetch successful for https://archiveofourown.org/works/84711101.
Skipping explicit work: https://archiveofourown.org/works/84711101
Fetching work: https://archiveofourown.org/works/84709216
Fetch successful for https://archiveofourown.org/works/84709216.
Work 84709216 updated with tags.
Work 84709216 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84708881
Fetch successful for https://archiveofourown.org/works/84708881.
Work 84708881 updated with tags.
Work 84708881 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84708701
Fetch successful for https://archiveofourown.org/works/84708701.
Work 84708701 updated with tags.
Work 84708701 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84708291
Fetch successful for https://archiveofourown.org/works/84708291.
Work 84708291 updated with tags.
Work 84708291 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84705176
Fetch failed for https://archiveofourown.org/works/84705176. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84705176.
Skipping explicit work: https://archiveofourown.org/works/84705176
Fetching work: https://archiveofourown.org/works/84702331
Fetch failed for https://archiveofourown.org/works/84702331. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/84702331. Retrying in 4.0s...
Error fetching work https://archiveofourown.org/works/84702331: Failed to fetch https://archiveofourown.org/works/84702331 after 3 attempts: HTTPSConnectionPool(host='archiveofourown.org', port=443): Read timed out. (read timeout=20). Skipping this work.
Fetching work: https://archiveofourown.org/works/84702261
Fetch failed for https://archiveofourown.org/works/84702261. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84702261.
Skipping explicit work: https://archiveofourown.org/works/84702261
Fetching work: https://archiveofourown.org/works/84701301
Fetch successful for https://archiveofourown.org/works/84701301.
Work 84701301 updated with tags.
Work 84701301 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84699031
Fetch successful for https://archiveofourown.org/works/84699031.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84699031/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84699031/bookmarks?page=1.
Work 84699031 updated with tags.
Work 84699031 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84696726
Fetch successful for https://archiveofourown.org/works/84696726.
Work 84696726 updated with tags.
Work 84696726 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84769896
Fetch successful for https://archiveofourown.org/works/84769896.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84769896/bookmarks?page=1
Fetch failed for https://archiveofourown.org/works/84769896/bookmarks?page=1. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84769896/bookmarks?page=1.
Work 84769896 updated with tags.
Work 84769896 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84765921
Fetch successful for https://archiveofourown.org/works/84765921.
Work 84765921 updated with tags.
Work 84765921 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84763896
Fetch successful for https://archiveofourown.org/works/84763896.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84763896/bookmarks?page=1
Fetch failed for https://archiveofourown.org/works/84763896/bookmarks?page=1. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84763896/bookmarks?page=1.
Work 84763896 updated with tags.
Work 84763896 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84762276
Fetch failed for https://archiveofourown.org/works/84762276. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84762276.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84762276/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84762276/bookmarks?page=1.
Work 84762276 updated with tags.
Work 84762276 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84761826
Fetch successful for https://archiveofourown.org/works/84761826.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84761826/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84761826/bookmarks?page=1.
Work 84761826 updated with tags.
Work 84761826 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84761796
Fetch successful for https://archiveofourown.org/works/84761796.
Work 84761796 updated with tags.
Work 84761796 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84761471
Fetch failed for https://archiveofourown.org/works/84761471. Retrying in 2.0s...
Fetch failed for https://archiveofourown.org/works/84761471. Retrying in 4.0s...
Fetch successful for https://archiveofourown.org/works/84761471.
Skipping explicit work: https://archiveofourown.org/works/84761471
Fetching work: https://archiveofourown.org/works/84759696
Fetch successful for https://archiveofourown.org/works/84759696.
Skipping explicit work: https://archiveofourown.org/works/84759696
Fetching work: https://archiveofourown.org/works/84758166
Fetch successful for https://archiveofourown.org/works/84758166.
Skipping explicit work: https://archiveofourown.org/works/84758166
Fetching work: https://archiveofourown.org/works/84757686
Fetch successful for https://archiveofourown.org/works/84757686.
Skipping explicit work: https://archiveofourown.org/works/84757686
Fetching work: https://archiveofourown.org/works/84755856
Fetch failed for https://archiveofourown.org/works/84755856. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84755856.
Skipping explicit work: https://archiveofourown.org/works/84755856
Fetching work: https://archiveofourown.org/works/84752771
Fetch successful for https://archiveofourown.org/works/84752771.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84752771/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84752771/bookmarks?page=1.
Work 84752771 updated with tags.
Work 84752771 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84751816
Fetch successful for https://archiveofourown.org/works/84751816.
Skipping explicit work: https://archiveofourown.org/works/84751816
Fetching work: https://archiveofourown.org/works/84751086
Fetch successful for https://archiveofourown.org/works/84751086.
Skipping explicit work: https://archiveofourown.org/works/84751086
Fetching work: https://archiveofourown.org/works/84749796
Fetch successful for https://archiveofourown.org/works/84749796.
Skipping explicit work: https://archiveofourown.org/works/84749796
Fetching work: https://archiveofourown.org/works/84748536
Fetch successful for https://archiveofourown.org/works/84748536.
Work 84748536 updated with tags.
Work 84748536 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84745361
Fetch successful for https://archiveofourown.org/works/84745361.
Work 84745361 updated with tags.
Work 84745361 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84744936
Fetch successful for https://archiveofourown.org/works/84744936.
Work 84744936 updated with tags.
Work 84744936 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84744381
Fetch successful for https://archiveofourown.org/works/84744381.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84744381/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84744381/bookmarks?page=1.
Work 84744381 updated with tags.
Work 84744381 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84743746
Fetch failed for https://archiveofourown.org/works/84743746. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84743746.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84743746/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84743746/bookmarks?page=1.
Work 84743746 updated with tags.
Work 84743746 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84742296
Fetch successful for https://archiveofourown.org/works/84742296.
Work 84742296 updated with tags.
Work 84742296 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84741426
Fetch failed for https://archiveofourown.org/works/84741426. Retrying in 2.0s...
Fetch successful for https://archiveofourown.org/works/84741426.
Skipping explicit work: https://archiveofourown.org/works/84741426
Fetching work: https://archiveofourown.org/works/84738976
Fetch successful for https://archiveofourown.org/works/84738976.
Fetching bookmarks page 1/1: https://archiveofourown.org/works/84738976/bookmarks?page=1
Fetch successful for https://archiveofourown.org/works/84738976/bookmarks?page=1.
Work 84738976 updated with tags.
Work 84738976 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84737881
Fetch successful for https://archiveofourown.org/works/84737881.
Work 84737881 updated with tags.
Work 84737881 status updated to Scraped.
Fetching work: https://archiveofourown.org/works/84737721
Fetch successful for https://archiveofourown.org/works/84737721.
Work 84737721 updated with tags.
Work 84737721 status updated to Scraped.

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

all = c.execute('''
      Select * from all_works
''')

for row in all:
    print(row)

conn.close() # Adding conn.close() after the loop

('75267501', '2025-12-21', 'https://archiveofourown.org/works/75267501', 'Scraped', 'the wolf and the fox', 'GoddessOfWriting , TheDauntless (GoddessOfWriting)', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Jon Snow/Original Female Character(s)", "Jon Snow & Original Female Character(s)", "Jon Snow & Arya Stark & Bran Stark & Rickon Stark & Robb Stark & Sansa Stark", "Ghost | Jon Snow\'s Direwolf & Jon Snow", "Catelyn Tully Stark/Ned Stark", "Jon Snow & Ned Stark"]', '["Original Female Character(s)", "Characters From The North (A Song of Ice and Fire)", "Jon Snow", "Ghost | Jon Snow\'s Direwolf", "Arya Stark", "Nymeria | Arya Stark\'s Direwolf", "Sansa Stark", "Robb Stark", "Theon Greyjoy", "Bran Stark", "Rickon Stark", "Summer | Bran Stark\'s Direwolf", "Shaggydog | Rickon Stark\'s Direwolf", "Ned Stark", "Catelyn Tully Stark", "Maester Luwin of Winterfell (A Song of Ice and Fire)", "Rodrik Cassel", "Jory Cassel", "Harwin the Winterfell Guard (A Song of Ice and Fire)", "Robert Baratheon", "Joffrey Baratheon", "Cersei Lannister", "Tyrion Lannister", "Jon Snow ", " Original Female Character(s)", " Arya Stark ", " Bran Stark ", " Rickon Stark ", " Robb Stark ", " Sansa Stark", "Ghost ", " Jon Snow\'s Direwolf ", " Jon Snow", " Ned Stark"]', '["Original Noble House (A Song of Ice and Fire)", "Northern Culture & Customs (A Song of Ice and Fire)", "The North (A Song of Ice and Fire)", "The Wolfswood (A Song of Ice and Fire)", "Winterfell (A Song of Ice and Fire)", "House Stark (A Song of Ice and Fire)", "Author Supports House Stark (A Song of Ice and Fire)", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Jon Snow Doesn\'t Join the Night\'s Watch", "Married Jon Snow", "Childhood Friends to Lovers", "Hunters & Hunting", "Wargs & Warging (A Song of Ice and Fire)", "Ghost | Jon Snow\'s Direwolf is a Good Boy", "Joffrey Baratheon Being an Asshole", "Robert Baratheon Being an Asshole", "Catelyn Tully Stark is Not Nice", "Westerosi Politics (A Song of Ice and Fire)", "The Old Gods (A Song of Ice and Fire)", "Weirwood Trees (A Song of Ice and Fire)", "Skinchangers & Skinchanging (A Song of Ice and Fire)", "Mentioned Rhaegar Targaryen", "Mentioned Lyanna Stark"]', "The first time she met Jon Snow, they were twelve years old and he accidentally walked into her trap. ... From his uncomfortable position suspended in the air, Jon looks down at the girl standing with her hands on her hips. She is around his age, with bark brown hair in two braids, forest green eyes, and dressed in a brown hunting ensemble. “Be quiet, stupid. You scared away the gods themselves!” The indignation of being caught in a trap by a girl catches up to him. “Let me down! You shouldn’t have put your stupid trap there.” “How else are you meant to catch game?” She yells up at him before untangling a rope and Jon falls to the ground with a thud. --- House Rennard of the Wolfswood has long stood by House Stark, joined together by the large stretches of the forest and their inhabitants. They are known for raising excellent hunters, trappers, hawkers and gamekeepers - most of them women, for there has never been a ruling lord in their entire history. Jon Snow walks into Dyana Rennard's trap one day and falls head over heels - literally.")
('56181721', '2026-05-04', 'https://archiveofourown.org/works/56181721', 'Scraped', 'The Prince and the King', 'HimmeltheHero', '["Mature"]', '["Gen", "F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Elia Martell/Rhaegar Targaryen", "Ashara Dayne/Ned Stark", "past Lyanna Stark/Rhaegar Targaryen - Relationship", "Jon Snow/Mya Stone", "Rhaegar Targaryen/Margaery Tyrell"]', '["Rhaegar Targaryen", "Aerys II Targaryen", "Tywin Lannister", "Jon Snow", "Aegon Targaryen (Son of Elia)", "Rhaenys Targaryen (Daughter of Elia)", "Elia Martell", "Oswell Whent", "Richard Lonmouth", "Margaery Tyrell", "Cersei Lannister", "Viserys Targaryen (Brother of Daenerys)", "Daenerys Targaryen", "Ned Stark", "Rickard Stark", "Robert Baratheon", "Rhaella Targaryen (Wife of Aerys II)", "Ashara Dayne", "Arthur Dayne", "Mya Stone", "Myles Mooton", "Jon Connington", "Stannis Baratheon", "past Lyanna Stark", "Rhaegar Targaryen - Relationship"]', '["Alternate Universe - Canon Divergence", "No Robert\'s Rebellion | Robert Baratheon Never Rebels Against the Targaryens", "Canon-Typical Violence", "Jon Snow is a Targaryen", "Politics", "Dragons", "Targaryen-on-Targaryen violence"]', '“Treason and turmoil followed, as night follows day, ending at Summerhall in sorcery, fire and grief.” Aegon the Unlikely and most of his kin died at Summerhall, but not before managing to bring dragons back into the world. With their greatest power restored to them, House Targaryen begins a new era of dominance over the Seven Kingdoms. But with King Aerys slipping into madness and Prince Rhaegar lost in his prophecies the dragons once again dance…')
('81993896', '2026-02-16', 'https://archiveofourown.org/works/81993896', 'Scraped', 'Survive, Endure, Rise', 'An_Anonymous_Writer', '["Mature"]', '["F/M", "Gen"]', '["Game of Thrones (TV)", "A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Jon Snow/Margaery Tyrell", "Ysilla Royce/Robb Stark", "Catelyn Tully Stark/Ned Stark", "Roslin Frey/Edmure Tully", "Sansa Stark/Willas Tyrell", "Garlan Tyrell/Desmera Redwyne"]', '["Jon Snow", "Robb Stark", "Ned Stark", "Catelyn Tully Stark", "Arya Stark", "Sansa Stark", "Brandon Stark", "Rickon Stark", "Arthur Dayne", "Margaery Tyrell", "Olenna Tyrell", "Loras Tyrell", "Mace Tyrell", "House Tyrell Characters (A Song of Ice and Fire)", "House Stark Characters (A Song of Ice and Fire)", "Brynden \\"Blackfish\\" Tully", "Davos Seaworth", "Jorah Mormont", "Jaime Lannister", "Tyrion Lannister", "Cersei Lannister", "Tywin Lannister", "House Lannister Characters (A Song of Ice and Fire)", "Robert Baratheon", "Joffrey Baratheon", "Stannis Baratheon", "Renly Baratheon", "Myrcella Baratheon", "House Baratheon Characters (A Song of Ice and Fire)", "House Martell Characters (A Song of Ice and Fire)", "Edmure Tully", "Hoster Tully", "House Tully Characters (A Song of Ice and Fire)", "Lysa Tully Arryn", "House Arryn Characters (A Song of Ice and Fire)", "Petyr Baelish", "Aurane Waters", "Yohn Royce", "Ysilla Royce", "House Royce Characters (A Song of Ice and Fire)", "Lucas Blackwood", "Randyll Tarly", "Paxter Redwyne", "Monford Velaryon", "Basically ALL A Song of Ice and Fire Characters", "Roslin Frey", "Willas Tyrell", "Garlan Tyrell", "Desmera Redwyne"]', '["Action/Adventure", "Action & Romance", "Canon - A Song of Ice and Fire Series & Game of Thrones (TV) Combination", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Manipulation", "Politics", "Jon Snow is a Targaryen", "Jon Snow is Not Called Aegon", "Jon Snow Knows Something", "Weekly Updates"]', '- Jon Snow is the son of Rhaegar and Lyanna (not that he knows it in beginning) - Bastard who eventually learns the truth of who he is... wants nothing to do with it - Becomes lord of Moat Cailin and begins to grow and deal with many struggles to make the poorest land of the North, since it has been without a lord for so long, to become successful economically - One day, he will no longer be able to hide from his past. - Olenna Tyrell Plots - How the War of the 5 Kings should have happened - If Robb Stark didn’t be a complete political idiot UPDATED EVERY SATURDAY!')
('76423276', '2025-12-31', 'https://archiveofourown.org/works/76423276', 'Scraped', 'A Lioness In A Northern Court', 'Emilie_L_C , Scorpius6689', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Cersei Lannister/Jon Snow", "Ashara Dayne/Jon Snow"]', '["Jon Snow", "Cersei Lannister", "Tyrion Lannister", "Rhaegar Targaryen", "Lyanna Stark", "Rhaella Targaryen (Wife of Aerys II)", "Aerys II Targaryen", "Arthur Dayne", "Ashara Dayne"]', '["Alternate Universe - Canon Divergence", "Jon Snow is a Targaryen", "Seduction", "Fluff and Angst"]', 'While King Rhaegar and Queen Lyanna sit on the Iron Throne, a widowed and childless Cersei Lannister arrives at the Red Keep with a singular ambition: to secure her legacy through the heir, their son Prince Duncan Targaryen.')
('55165036', '2024-04-13', 'https://archiveofourown.org/works/55165036', 'Scraped', 'A Stark and his Ice (RE_WRITE)', 'Intherain487', '["Mature"]', '[]', '["A Song of Ice and Fire & Related Fandoms", "A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)"]', '["Ned Stark/Shaena Targaryen", "Catelyn Tully Stark/Ned Stark", "Robert Baratheon/Lyanna Stark", "Lyanna Stark/Rhaegar Targaryen", "Elia Martell/Rhaegar Targaryen", "Ashara Dayne/Brandon Stark", "Cersei Lannister/Jaime Lannister", "Cersei Lannister/Brandon Stark", "Oberyn Martell/Ellaria Sand", "Shaena Targaryen/Catelyn Tully Stark"]', '["Ned Stark", "Rickard Stark", "Brandon Stark", "Shaena Targaryen", "Robert Baratheon", "Jon Arryn", "Rhaegar Targaryen", "Aerys II Targaryen", "Rhaella Targaryen (Wife of Aerys II)", "Barristan Selmy", "Tywin Lannister", "Jaime Lannister", "Cersei Lannister", "Lyanna Stark", "Benjen Stark", "Arthur Dayne", "Thoros of Myr (A Song of Ice and Fire)", "Original Characters", "Original Catelyn Tully Stark/Ned Stark Child(ren)", "Willam Dustin", "Yohn Royce", "Elys Arryn", "Anya Waynwood", "House Hightower Characters (A Song of Ice and Fire)", "Mace Tyrell", "Leyton Hightower", "Baelor Hightower", "Olenna Tyrell", "House Redwyne Characters (A Song of Ice and Fire)", "Hoster Tully", "Brynden \\"Blackfish\\" Tully", "Catelyn Tully Stark", "Elia Martell", "Ashara Dayne", "Oberyn Martell", "Ellaria Sand"]', '["Ned Stark Needs a Hug", "Alternate Universe - Canon Divergence", "POV Ned Stark", "Pre-Robert\'s Rebellion Against the Targaryens", "The Vale of Arryn (A Song of Ice and Fire)", "Shaena Targaryen Lives"]', "In the icy wilderness of the North, a young Ned Stark discovers he possesses a mysterious power over ice. Terrified of the potential danger it poses to his loved ones, Ned grapples with his newfound abilities in secret. Haunted by guilt and burdened by his icy gift, Ned resolves to journey southward to seek answers and redemption. Along the way, he encounters allies and adversaries, each with their own motives and secrets. Amidst political intrigue and looming threats, Ned must navigate a treacherous path while concealing his true identity. As Ned delves deeper into the mysteries surrounding his powers, he uncovers ancient legends and forgotten truths that challenge his beliefs and shape his destiny. With the fate of the realm hanging in the balance, Ned must confront his fears and embrace his true heritage to fulfill his role in the unfolding saga of ice and fire. But as winter looms on the horizon and darkness gathers, Ned's journey is far from over, and the true test of his strength and honor is yet to come.")
('50992918', '2023-10-21', 'https://archiveofourown.org/works/50992918', 'Scraped', 'A Song of Three (Abandoned Version)', 'orphan_account', '["Mature"]', '["F/F", "F/M", "Gen", "Multi"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)", "A Song of Ice and Fire & Related Fandoms"]', '["Jon Snow/Sansa Stark", "Jon Snow/Daenerys Targaryen", "Sansa Stark/Daenerys Targaryen"]', '["Daenerys Targaryen", "Jon Snow", "Sansa Stark", "Ned Stark", "Robb Stark", "Catelyn Tully Stark", "Bran Stark", "Brynden \\"Bloodraven\\" Rivers", "Young Griff (ASoIaF)"]', '["R Plus L Equals J", "Prophetic dreams sometimes creepy sometimes not", "what is a threesome?", "Sometimes I just steal whole sentences from the book lmao", "Jonsa stuff comes first", "Then comes the threesome", "Its finally getting fun I swear", "jonsa", "Jonerys", "Slow Burn", "Jon does some shady shit", "i love sansa so much", "Soulmates", "Three hearts that beat as one", "Asoiaf lore is so cool", "book canon", "Jon Snow Doesn\'t Join the Night\'s Watch", "Jon Snow is a Targaryen", "Threesome - F/F/M", "but slow burn", "Jon Snow Goes to King\'s Landing", "dragon\'s egg", "High Fantasy", "No Harem", "This is not a Jon Wank fic", "Throuple", "Go read the fixed version", "THIS HAS BEEN ABANDONED", "And rewritten"]', '“Douse your tempers, Ser.” Barristan Selmy reminded him once more. “You swore an oath to the king the day he knighted you. You must honor it. Don’t act rashly just yet, your father would not approve of it.” “What should I do then, Ser Barristan?” Jon asked with despair. “Stand by your family, wait for Lord Stark.” He counseled. “And remember your vows.” Ser Barristan had once been his hero, now not one of his words could bring him any comfort. Unbesought, Jon’s fury flared back to this knight in white, as shining as dawn. “As you stood beside Mad Aerys when he murdered my grandfather? My uncle? How idly did you stand then, ser? How straight was your back?” He might as well have slapped him in the face. Barristan the Bold turned back a step. He spoke flatly, “Still, you and your family are in my prayers.” “You may keep them to yourself,” Jon told him. “I was a bastard before I was a knight. And I remember my vows.”')
('73894251', '2025-11-08', 'https://archiveofourown.org/works/73894251', 'Scraped', 'A Song of Three', 'NotMexicanSven', '["Mature"]', '["F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)"]', '["Jon Snow/Sansa Stark", "Jon Snow/Daenerys Targaryen", "Sansa Stark/Daenerys Targaryen", "Jon Snow/Sansa Stark/Daenerys Targaryen"]', '["Jon Snow", "Daenerys Targaryen", "Sansa Stark", "Ned Stark", "Catelyn Tully Stark", "Brynden \\"Bloodraven\\" Rivers", "Young Griff (ASoIaF)", "Robb Stark"]', '["R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "book canon", "Slow Burn", "Soulmates", "Three hearts that beat as one", "Jon Snow Goes to King\'s Landing", "Jon Snow Doesn\'t Join the Night\'s Watch", "What if dragon egg?", "High Fantasy", "No Harem", "Throuple", "Threesome", "Jon does some shady shit...again", "No Bashing", "rewritten", "I still love Sansa way too much"]', "“Why does he have a statue?” Jon Snow asked in a callow voice, though it made Ned lift an eyebrow. The boy was truly observant. He had realized that, by tradition, only lords and kings had their likenesses sculpted in stone for their eternal vigil. “I do not know, son. But look where he rests. Perhaps Torrhen wanted his brother to lie beside him, even when death comes claim.” “Or maybe Brandon wanted to protect his brother, even after death,” Jon said, as serious as a ten-year-old boy could be. “Father, I no longer wish to join the Watch.” Jon Snow spurns the Night's Watch. Daenerys Targaryen dreams of wolves. Sansa Stark dreams of dragons. Three unaware souls, linked by fate and causality. Somewhere, a song for three has begun to play.")
('62910172', '2025-01-17', 'https://archiveofourown.org/works/62910172', 'Scraped', 'Silver Spoon', 'franzkafkagf', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire - George R. R. Martin"]', '["Jon Snow & Rhaegar Targaryen", "Elia Martell/Rhaegar Targaryen", "Elia Martell & Jon Snow", "Jon Snow & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)", "Benjen Stark & Robb Stark", "Jon Snow & Daenerys Targaryen", "Elia Martell & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)"]', '["Jon Snow", "Daenerys Targaryen", "Rhaenys Targaryen (Daughter of Elia)", "Elia Martell", "Rhaegar Targaryen", "Aegon Targaryen (Son of Elia)", "Margaery Tyrell", "Benjen Stark", "Robb Stark", "Tyrion Lannister", "Cersei Lannister", "Arthur Dayne", "Jaime Lannister", "The Others | White Walker Character(s) (A Song of Ice and Fire)", "Jon Snow ", " Rhaegar Targaryen", "Elia Martell ", " Jon Snow", " Aegon Targaryen (Son of Elia) ", " Rhaenys Targaryen (Daughter of Elia)", "Benjen Stark ", " Robb Stark", " Daenerys Targaryen"]', '["King Rhaegar Targaryen", "Robert\'s Rebellion Fails | Rhaegar Targaryen Wins", "R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow\'s Parents", "Alternate Universe - Reincarnation", "Post-Book 5: A Dance with Dragons (A Song of Ice and Fire)", "Jon Snow\'s Name is Aemon", "Character Study", "Epic", "House Blackfyre (A Song of Ice and Fire)"]', 'When the third dagger took him between the shoulder blades, he gave a grunt and fell face-first into the snow. He never felt the fourth knife. Only the cold… And then, sunlight touched his face. Warm, unfamiliar, impossibly bright. Jon Snow, Lord Commander of the Night’s Watch, had died in the frozen wastes of the Wall. And yet, he wakes. No longer at Castle Black, no longer bleeding into the snow, he finds himself in a bed of silk, in a city he has never set foot in but knows from stories. ☆ In which Jon Snow dies in the cold and wakes up to find that people call him Aemon and Rhaegar Targaryen is king.')
('84723811', '2026-05-12T13:05:34Z', 'https://archiveofourown.org/works/84723811', 'New', 'The rot was in this house before I dwelled here and it shall be here when I am in the ground.', 'youngjusticewriter', None, None, None, None, None, None, None)
('84723496', '2026-05-12T12:58:30Z', 'https://archiveofourown.org/works/84723496', 'Scraped', 'Beneath the Black Dragon', 'Dorumuk', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Original Blackfyre Character/Ashara Dayne"]', '["Original Blackfyre Character(s)", "Original Male Character(s)", "House Blackfyre Characters (A Song of Ice and Fire)", "Aerys II Targaryen", "Rhaegar Targaryen", "Elia Martell", "Lyanna Stark", "Ned Stark", "Robert Baratheon", "Stannis Baratheon", "Ashara Dayne", "Arthur Dayne", "Brandon Stark", "Rickard Stark", "Original Blackfyre Character"]', '["Alternate Universe - Canon Divergence", "House Blackfyre (A Song of Ice and Fire)", "Targaryen Restoration", "Essos (A Song of Ice and Fire)", "Elia Martell Lives", "Rhaenys Targaryen (Daughter of Elia) Lives", "Aegon Targaryen (Son of Elia) Lives", "Rhaella Targaryen (Wife of Aerys II) Lives", "Lyanna Stark Lives", "Brandon Stark Lives"]', 'Kang Doyun died at his desk in Seoul, crushed beneath deadlines, defect reports, and a life that had long since learned to call exhaustion normal. Valar Blackfyre should have died in Tyrosh, thrown from his horse before the world ever learned his hidden name. Instead, both men wake in the same body. One is a modern engineer with memories of a world where chains are invisible. The other is the secret son of Maelys Blackfyre, raised on old wounds, forbidden names, and the bitter inheritance of the black dragon. Across the Narrow Sea, the Targaryen dynasty has begun to tremble. In Tyrosh, a black ember draws breath. Their first plan is simple. Do not die.')
('84723001', '2026-05-12T12:40:34Z', 'https://archiveofourown.org/works/84723001', 'Scraped', 'Hands do not dream', 'Nessie (Miss_Bowen)', '["General Audiences"]', '["F/M"]', '["Game of Thrones (TV)"]', '["Jaime Lannister/Brienne of Tarth"]', '["Jaime Lannister", "Brienne of Tarth"]', '["Banter", "Mild Hurt/Comfort", "Short", "Permanent Injury"]', 'This is a very short (and kind of irrelevant) short look into Jaime/Brienne. Spoilers for early/mid season 3 GoT.')

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

# overdue_link_rows = c.execute('''
#       Select link from all_works
#       where published < date('now', '-1 days')
#       and status = 'New'
# ''').fetchall()

overdue_link_rows = c.execute('''
      Select link from all_works
      where status = 'New'
''').fetchall()

overdue_link_list = [row[0] for row in overdue_link_rows]

conn.close()
overdue_link_list

['https://archiveofourown.org/works/84723811',
 'https://archiveofourown.org/works/84715966',
 'https://archiveofourown.org/works/84714186',
 'https://archiveofourown.org/works/84711981',
 'https://archiveofourown.org/works/84711101',
 'https://archiveofourown.org/works/84705176',
 'https://archiveofourown.org/works/84702331',
 'https://archiveofourown.org/works/84702261',
 'https://archiveofourown.org/works/84761471',
 'https://archiveofourown.org/works/84759696',
 'https://archiveofourown.org/works/84758166',
 'https://archiveofourown.org/works/84757686',
 'https://archiveofourown.org/works/84755856',
 'https://archiveofourown.org/works/84751816',
 'https://archiveofourown.org/works/84751086',
 'https://archiveofourown.org/works/84749796',
 'https://archiveofourown.org/works/84741426']

In [ ]:
conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

all = c.execute('''
      Select *
      from public_bookmarks
      limit 20
''')

for row in all:
    print(row)

conn.close() # Adding conn.close() after the loop

('AmethystQuil', '75267501')
('waometh', '75267501')
('Prpledinosaur', '75267501')
('Sandy_veiw', '75267501')
('Dragon_of_Thunder', '75267501')
('Plopp00', '75267501')
('Hewn820', '75267501')
('WinterAutumn102', '75267501')
('ch_ch_ch_cherrybomb', '75267501')
('username0020', '75267501')
('Rene7968', '75267501')
('procrasinator', '75267501')
('Sister0Pirate0Queen0Mary0Read', '75267501')
('Hush18', '75267501')
('Cribbit', '75267501')
('Reddfoxx297', '75267501')
('Kiro2001', '75267501')
('marytutor', '75267501')
('Murnix', '75267501')
('Ella05', '75267501')

Collaborative filtering using my_bookmarks and public_bookmarks

In [ ]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("ao3_works.db")

df_my_bookmarks = pd.read_sql_query("SELECT work_id FROM my_bookmarks", conn)
df_public_bookmarks = pd.read_sql_query("SELECT user_id, work_id FROM public_bookmarks", conn)
conn.close()

In [ ]:
df_my_bookmarks

    work_id
0  75267501
1  56181721
2  81993896
3  76423276
4  55165036
5  50992918
6  73894251
7  62910172

In [ ]:
df_public_bookmarks

                user_id   work_id
0          AmethystQuil  75267501
1               waometh  75267501
2         Prpledinosaur  75267501
3            Sandy_veiw  75267501
4     Dragon_of_Thunder  75267501
...                 ...       ...
2086            yilzmff  84738976
2087     ValyrianScribe  84738976
2088     Theunlickystar  84738976
2089            3efirka  84737881
2090         Seren_king  84737721

[2091 rows x 2 columns]

In [ ]:
my_user_id = "-1"

df_my_bookmarks["user_id"] = my_user_id
df_my_bookmarks["interaction_score"] = 1

df_public_bookmarks["interaction_score"] = 1

In [ ]:
df_my_bookmarks = df_my_bookmarks[["user_id", "work_id", "interaction_score"]]
df_my_bookmarks

  user_id   work_id  interaction_score
0      -1  75267501                  1
1      -1  56181721                  1
2      -1  81993896                  1
3      -1  76423276                  1
4      -1  55165036                  1
5      -1  50992918                  1
6      -1  73894251                  1
7      -1  62910172                  1

In [ ]:
df_public_bookmarks = df_public_bookmarks[["user_id", "work_id", "interaction_score"]]
df_public_bookmarks

                user_id   work_id  interaction_score
0          AmethystQuil  75267501                  1
1               waometh  75267501                  1
2         Prpledinosaur  75267501                  1
3            Sandy_veiw  75267501                  1
4     Dragon_of_Thunder  75267501                  1
...                 ...       ...                ...
2086            yilzmff  84738976                  1
2087     ValyrianScribe  84738976                  1
2088     Theunlickystar  84738976                  1
2089            3efirka  84737881                  1
2090         Seren_king  84737721                  1

[2091 rows x 3 columns]

In [ ]:
df_interactions = pd.concat(
    [df_my_bookmarks, df_public_bookmarks],
    ignore_index=True
)
df_interactions

             user_id   work_id  interaction_score
0                 -1  75267501                  1
1                 -1  56181721                  1
2                 -1  81993896                  1
3                 -1  76423276                  1
4                 -1  55165036                  1
...              ...       ...                ...
2094         yilzmff  84738976                  1
2095  ValyrianScribe  84738976                  1
2096  Theunlickystar  84738976                  1
2097         3efirka  84737881                  1
2098      Seren_king  84737721                  1

[2099 rows x 3 columns]

In [ ]:
num_unique_work_ids = df_interactions['work_id'].nunique()
print(f"Number of unique work IDs in df_interactions: {num_unique_work_ids}")

Number of unique work IDs in df_interactions: 40

In [ ]:
import pandas as pd
from scipy.sparse import coo_matrix


def create_user_work_matrix(df: pd.DataFrame):
    """
    Creates a sparse user-work interaction matrix for AO3 bookmarks.

    Rows = users/bookmarkers
    Columns = AO3 works
    Values = interaction_score, usually 1 for bookmarked
    """

    df = df.copy()

    # Make sure IDs are strings
    df["user_id"] = df["user_id"].astype(str)
    df["work_id"] = df["work_id"].astype(str)

    # Make sure score is numeric
    df["interaction_score"] = pd.to_numeric(df["interaction_score"])

    # Remove duplicate user-work pairs
    # If duplicates exist, keep the max score
    df = (
        df.groupby(["user_id", "work_id"], as_index=False)
        ["interaction_score"]
        .max()
    )

    user_mapper = {user_id: i for i, user_id in enumerate(df["user_id"].unique())}
    work_mapper = {work_id: i for i, work_id in enumerate(df["work_id"].unique())}
    print(type(user_mapper))
    print(type(work_mapper))

    user_index = df["user_id"].map(user_mapper).values
    work_index = df["work_id"].map(work_mapper).values
    print(type(user_index))
    print(type(work_index))

    X = coo_matrix(
        (
            df["interaction_score"].values,
            (user_index, work_index)
        ),
        shape=(len(user_mapper), len(work_mapper))
    )

    return X.tocsr(), user_mapper, work_mapper

In [ ]:
X, user_mapper, work_mapper = create_user_work_matrix(df_interactions)

print(X.shape)
print(user_mapper["-1"])

<class 'dict'>
<class 'dict'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(1682, 40)
0

In [ ]:
n_total = X.shape[0]*X.shape[1]
n_ratings = X.nnz
sparsity = n_ratings/n_total
print(f"Matrix percentage filled: {round(sparsity*100,2)}% \nMatrix percentage empty: {100-round(sparsity*100,2)}%")

Matrix percentage filled: 3.12%
Matrix percentage empty: 96.88%

In [ ]:
# find recoommendations using KNN item based collaborative filtering
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors


def recommend_works_item_based(
    user_id,
    X,
    user_mapper,
    work_mapper,
    k=10,
    metric="cosine",
    min_similarity=0.01
):
    """
    Item-based collaborative filtering for AO3.

    X shape:
        users × works

    item_user_matrix shape:
        works × users

    Scores are weighted by actual cosine similarity.
    """

    user_id = str(user_id)

    if user_id not in user_mapper:
        print(f"User ID {user_id} not found.")
        return pd.DataFrame(columns=["work_id", "score"])

    item_user_matrix = X.T

    user_index = user_mapper[user_id]
    user_interactions = X[user_index]

    already_seen = set(user_interactions.indices)

    n_works = item_user_matrix.shape[0]

    if n_works == 0:
        return pd.DataFrame(columns=["work_id", "score"])

    n_neighbors = min(k + 1, n_works)

    kNN = NearestNeighbors(
        n_neighbors=n_neighbors,
        metric=metric
    )

    kNN.fit(item_user_matrix)

    scores = np.zeros(n_works)
    max_similarity = np.zeros(n_works)
    matched_seen_works = {i: [] for i in range(n_works)}

    for seen_work_index in user_interactions.indices:
        seen_work_vec = item_user_matrix[seen_work_index]

        distances, similar_work_indices = kNN.kneighbors(
            seen_work_vec,
            return_distance=True
        )

        distances = distances.flatten()
        similar_work_indices = similar_work_indices.flatten()

        original_score = user_interactions[0, seen_work_index]

        for similar_work_index, distance in zip(similar_work_indices, distances):
            if similar_work_index == seen_work_index:
                continue

            similarity = 1 - distance

            if similarity < min_similarity:
                continue

            scores[similar_work_index] += original_score * similarity
            max_similarity[similar_work_index] = max(
                max_similarity[similar_work_index],
                similarity
            )
            matched_seen_works[similar_work_index].append(seen_work_index)

    recommended_indices = [
        i for i in np.argsort(-scores)
        if i not in already_seen and scores[i] > 0
    ]

    index_to_work = {
        index: work_id
        for work_id, index in work_mapper.items()
    }

    recommendations = [
        {
            "work_id": index_to_work[i],
            "score": scores[i],
            "max_similarity": max_similarity[i],
            "matched_profile_works": [
                index_to_work[j] for j in matched_seen_works[i]
            ]
        }
        for i in recommended_indices
    ]

    return pd.DataFrame(recommendations)

In [ ]:
recommendations = recommend_works_item_based(
    user_id="-1",
    X=X,
    user_mapper=user_mapper,
    work_mapper=work_mapper,
    k=20,
    min_similarity=0.01
)

In [ ]:
recommendations

    work_id     score  max_similarity matched_profile_works
0  84738976  0.086367        0.045644  [75267501, 81993896]
1  84763896  0.027821        0.027821            [62910172]

In [ ]:
# find recoommendations using cosine_similarity item based collaborative filtering
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


def recommend_works_item_based(
    user_id,
    X,
    user_mapper,
    work_mapper,
    min_similarity=0.01
):


    user_id = str(user_id)

    if user_id not in user_mapper:
        print(f"User ID {user_id} not found.")
        return pd.DataFrame(
            columns=[
                "work_id",
                "collab_score",
                "collab_score_sum",
                "max_similarity",
                "matched_profile_work_count",
                "matched_profile_works"
            ]
        )

    # Convert users × works into works × users
    item_user_matrix = X.T

    user_index = user_mapper[user_id]
    user_interactions = X[user_index]

    # Works already bookmarked/read by the user
    bookmarked_work_indices = user_interactions.indices
    bookmarked_work_set = set(bookmarked_work_indices)

    if len(bookmarked_work_indices) == 0:
        return pd.DataFrame(
            columns=[
                "work_id",
                "collab_score",
                "collab_score_sum",
                "max_similarity",
                "matched_profile_work_count",
                "matched_profile_works"
            ]
        )

    # All unread candidate works
    candidate_work_indices = np.array([
        i for i in range(item_user_matrix.shape[0])
        if i not in bookmarked_work_set
    ])

    if len(candidate_work_indices) == 0:
        return pd.DataFrame(
            columns=[
                "work_id",
                "collab_score",
                "collab_score_sum",
                "max_similarity",
                "matched_profile_work_count",
                "matched_profile_works"
            ]
        )

    bookmarked_matrix = item_user_matrix[bookmarked_work_indices]
    candidate_matrix = item_user_matrix[candidate_work_indices]

    # Shape:
    # candidates × bookmarked works
    similarity_matrix = cosine_similarity(
        candidate_matrix,
        bookmarked_matrix
    )

    # Ignore tiny/noisy similarity values
    similarity_matrix[similarity_matrix < min_similarity] = 0

    # Aggregate similarity signals
    collab_score_sum = similarity_matrix.sum(axis=1)

    # Mean score stays on a more comparable 0–1-ish scale
    collab_score_mean = similarity_matrix.mean(axis=1)

    max_similarity = similarity_matrix.max(axis=1)

    matched_profile_work_count = (
        similarity_matrix > 0
    ).sum(axis=1)

    index_to_work = {
        index: work_id
        for work_id, index in work_mapper.items()
    }

    recommendations = []

    for row_idx, candidate_work_index in enumerate(candidate_work_indices):
        matched_indices = np.where(similarity_matrix[row_idx] > 0)[0]

        matched_profile_works = [
            index_to_work[bookmarked_work_indices[j]]
            for j in matched_indices
        ]

        recommendations.append({
            "work_id": index_to_work[candidate_work_index],
            "collab_score": collab_score_mean[row_idx],
            "collab_score_sum": collab_score_sum[row_idx],
            "max_similarity": max_similarity[row_idx],
            "matched_profile_work_count": matched_profile_work_count[row_idx],
            "matched_profile_works": matched_profile_works
        })

    recommendations_df = pd.DataFrame(recommendations)

    recommendations_df = recommendations_df.sort_values(
        by=["collab_score_sum", "max_similarity"],
        ascending=False
    ).reset_index(drop=True)

    return recommendations_df

In [ ]:
collab_recommendations = recommend_works_item_based(
    user_id="-1",
    X=X,
    user_mapper=user_mapper,
    work_mapper=work_mapper,
    min_similarity=0.01
)

collab_recommendations.head(20)

,work_id,collab_score,collab_score_sum,max_similarity,matched_profile_work_count,matched_profile_works
0,84738976,0.010796,0.086367,0.045644,2,"[75267501, 81993896]"
1,84763896,0.003478,0.027821,0.027821,1,[62910172]
2,84737881,0.000000,0.000000,0.000000,0,[]
3,84752771,0.000000,0.000000,0.000000,0,[]
4,84711126,0.000000,0.000000,0.000000,0,[]
5,84721256,0.000000,0.000000,0.000000,0,[]
6,84714196,0.000000,0.000000,0.000000,0,[]
7,84744936,0.000000,0.000000,0.000000,0,[]
8,84745361,0.000000,0.000000,0.000000,0,[]
9,84743746,0.000000,0.000000,0.000000,0,[]
10,84722136,0.000000,0.000000,0.000000,0,[]
11,84765921,0.000000,0.000000,0.000000,0,[]
12,84723496,0.000000,0.000000,0.000000,0,[]
13,84769896,0.000000,0.000000,0.000000,0,[]
14,84762276,0.000000,0.000000,0.000000,0,[]
15,84744381,0.000000,0.000000,0.000000,0,[]
16,84761826,0.000000,0.000000,0.000000,0,[]
17,84699031,0.000000,0.000000,0.000000,0,[]
18,84696726,0.000000,0.000000,0.000000,0,[]
19,84723001,0.000000,0.000000,0.000000,0,[]

In [ ]:
collab_recommendations['collab_score_sum_normalized'] = (
    collab_recommendations["collab_score_sum"]
    / collab_recommendations["collab_score_sum"].max()
)
collab_recommendations

,work_id,collab_score,collab_score_sum,max_similarity,matched_profile_work_count,matched_profile_works,collab_score_sum_normalized
0,84738976,0.010796,0.086367,0.045644,2,"[75267501, 81993896]",1.000000
1,84763896,0.003478,0.027821,0.027821,1,[62910172],0.322124
2,84737881,0.000000,0.000000,0.000000,0,[],0.000000
3,84752771,0.000000,0.000000,0.000000,0,[],0.000000
4,84711126,0.000000,0.000000,0.000000,0,[],0.000000
5,84721256,0.000000,0.000000,0.000000,0,[],0.000000
6,84714196,0.000000,0.000000,0.000000,0,[],0.000000
7,84744936,0.000000,0.000000,0.000000,0,[],0.000000
8,84745361,0.000000,0.000000,0.000000,0,[],0.000000
9,84743746,0.000000,0.000000,0.000000,0,[],0.000000
10,84722136,0.000000,0.000000,0.000000,0,[],0.000000
11,84765921,0.000000,0.000000,0.000000,0,[],0.000000
12,84723496,0.000000,0.000000,0.000000,0,[],0.000000
13,84769896,0.000000,0.000000,0.000000,0,[],0.000000
14,84762276,0.000000,0.000000,0.000000,0,[],0.000000
15,84744381,0.000000,0.000000,0.000000,0,[],0.000000
16,84761826,0.000000,0.000000,0.000000,0,[],0.000000
17,84699031,0.000000,0.000000,0.000000,0,[],0.000000
18,84696726,0.000000,0.000000,0.000000,0,[],0.000000
19,84723001,0.000000,0.000000,0.000000,0,[],0.000000
20,84720706,0.000000,0.000000,0.000000,0,[],0.000000
21,84701301,0.000000,0.000000,0.000000,0,[],0.000000
22,84737721,0.000000,0.000000,0.000000,0,[],0.000000
23,84742296,0.000000,0.000000,0.000000,0,[],0.000000
24,84761796,0.000000,0.000000,0.000000,0,[],0.000000
25,84719016,0.000000,0.000000,0.000000,0,[],0.000000
26,84748536,0.000000,0.000000,0.000000,0,[],0.000000
27,84709216,0.000000,0.000000,0.000000,0,[],0.000000
28,84715021,0.000000,0.000000,0.000000,0,[],0.000000
29,84708291,0.000000,0.000000,0.000000,0,[],0.000000
30,84708701,0.000000,0.000000,0.000000,0,[],0.000000
31,84708881,0.000000,0.000000,0.000000,0,[],0.000000

In [ ]:
import sqlite3

conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

# Get the list of recommended work IDs
recommendation_work_ids = collab_recommendations['work_id'].tolist()

# Create a string of placeholders for the IN clause (e.g., '?,?,?')
placeholders = ','.join('?' * len(recommendation_work_ids))

# Construct the query with dynamic placeholders
query = f"SELECT * FROM all_works WHERE id IN ({placeholders})"

# Execute the query, passing the list of work IDs as parameters
all_works_from_recommendations = c.execute(query, recommendation_work_ids).fetchall()

for row in all_works_from_recommendations:
    print(row)

conn.close()

('84696726', '2026-05-12T00:40:29Z', 'https://archiveofourown.org/works/84696726', 'Scraped', 'HOTD Hogwarts Modern AU', 'Lying_on_floors_12', '["General Audiences"]', '["Gen"]', '["House of the Dragon (TV)"]', '["Aemond \\"One-Eye\\" Targaryen & Helaena Targaryen", "Aegon II Targaryen & Aemond \\"One-Eye\\" Targaryen", "Alicent Hightower & Aemond \\"One-Eye\\" Targaryen", "Otto Hightower & Aemond \\"One-Eye\\" Targaryen"]', '["Aemond \\"One-Eye\\" Targaryen", "Helaena Targaryen", "Aegon II Targaryen", "Alicent Hightower", "Otto Hightower", "Aemond \\"One-Eye\\" Targaryen ", " Helaena Targaryen", "Aegon II Targaryen ", " Aemond \\"One-Eye\\" Targaryen", "Alicent Hightower ", "Otto Hightower "]', '["Alternate Universe - Hogwarts", "Aegon II Targaryen is Not a Rapist", "Family Fluff", "House Targaryen (A Song of Ice and Fire)", "Sibling Bonding", "Quidditch", "Alternate Universe - Modern Setting", "Alternate Universe - Modern with Magic"]', 'A collection of Hogwarts based stories of the Targaryen family...')
('84699031', '2026-05-12T01:29:10Z', 'https://archiveofourown.org/works/84699031', 'Scraped', 'The Path of Wolf and Hound:The Dishonorable Knight', 'LuluoftheEast', '["Mature"]', '[]', '["A Song of Ice and Fire - George R. R. Martin"]', '["Sandor Clegane/Sansa Stark"]', '["Sansa Stark", "Sandor Clegane"]', '["First Kiss", "Sex", "True Love", "Protective Sandor Clegane", "Queen in the North (A Song of Ice and Fire)"]', '我觉得在马丁原著《冰与火之歌》的众生里，珊莎与猎狗最契合“冰与火”的宿命隐喻。 她是北境的冰，狼家血脉，隐忍坚韧； 他是被烈火灼烧的犬，满身伤痕，愤懑却心存良善。 原著的未竟之吻始终是心底意难平。 我不愿接受剧版的安排——让珊莎在无尽摧残与碾碎中，艰难蜕变为女王。 权力应该不止权谋与杀伐，爱本身，亦是一种强大的力量。 这不是爽文但合乎逻辑，有肉（不过我第一次写，不好请见谅） 马丁的故事迟迟未完，我实在等不及啦。 《狼与犬之路：不荣誉骑士》The Path of Wolf and Hound:The Dishonorable Knight前传 《狼与犬之路：不联姻女王》The Path of Wolf and Hound:The Unallied Queen 正传 便由我执笔献丑，续写一个珊莎与猎狗的故事。')
('84701301', '2026-05-12T02:12:05Z', 'https://archiveofourown.org/works/84701301', 'Scraped', 'A Dance of Ice and Fire', 'Roseburn7334', '["Mature"]', '["F/M"]', '["Game of Thrones (TV)"]', '[]', '["Jon Snow", "Ghost | Jon Snow\'s Direwolf", "Nymeria | Arya Stark\'s Direwolf", "Tyrion Lannister", "Sansa Stark", "Bran Stark", "Gendry (A Song of Ice and Fire)"]', '["Westeros (A Song of Ice and Fire)", "Essos (A Song of Ice and Fire)", "Dragons", "War", "Prophecy", "Original Character(s)", "Westerosi Politics (A Song of Ice and Fire)"]', "Naehra Targaryen has lived her life in secrecy within Essos, but when she finds a deceased dragon outside of Volantis along with her little sister's corpse, she’s thrown into the mission to kill the one responsible. But when the mission backfires, she finds herself in a battle to win the votes of the houses of Westeros. Will she accomplish the last words of King Bran? Or will war return to the realm, endangering everyone she calls family?")
('84708291', '2026-05-12T04:39:58Z', 'https://archiveofourown.org/works/84708291', 'Scraped', 'Is this how it is? Is this how it’s always been?', 'serene_moonbow', '["Mature"]', '["F/M"]', '["A Knight of the Seven Kingdoms (TV)", "A Song of Ice and Fire - George R. R. Martin"]', '["Daeron Targaryen (Son of Maekar I)/You"]', '["Daeron Targaryen (Son of Maekar I)", "Maekar I Targaryen", "Aerion Targaryen (Son of Maekar I)", "You"]', '["Character Death", "Alcohol Abuse/Alcoholism", "Depression", "Suicidal Thoughts", "female Tyrell reader", "2nd Person", "Let me know what else to tag I\\u2019m lost", "No beta we die like reader\\u2019s dad"]', 'Never did you think you would see Daeron again, never under these circumstances. You were a little girl, and now you were a woman. And he was a drunkard haunted by dragons that no longer exist.')
('84708701', '2026-05-12T04:50:01Z', 'https://archiveofourown.org/works/84708701', 'Scraped', 'And I am done with my Graceless Heart', 'serene_moonbow', '["Mature"]', '["F/M"]', '["A Knight of the Seven Kingdoms (TV)", "A Song of Ice and Fire - George R. R. Martin"]', '["Daeron Targaryen (Son of Maekar I)/You"]', '["Daeron Targaryen (Son of Maekar I)", "Aerion Targaryen (Son of Maekar I)", "Kiera of Tyrosh (A Song of Ice and Fire)", "Daenora Targaryen", "You"]', '["Character Death", "There is sex scenes but not descriptive", "Married Couple", "Can be read as a stand alone", "there are no happy endings in ba sing se", "Fluff-ish?", "no beta we die like baelor", "Pregnancy and Childbirth", "Timeskips"]', 'Now married, You and Daeron face different challenges in your married life.')
('84708881', '2026-05-12T04:55:06Z', 'https://archiveofourown.org/works/84708881', 'Scraped', 'The Young Wolf', 'serene_moonbow', '["Mature"]', '["F/M"]', '["Game of Thrones (TV)", "A Song of Ice and Fire - George R. R. Martin"]', '["Robb Stark/You"]', '["Robb Stark", "Catelyn Tully Stark", "You"]', '["I miss Robb", "Married Life", "Not even lowkey breeding kink", "this was my first published fic and it sucks", "sorry - Freeform", "no beta we die like the Ned Stark", "a mix of book and show canon"]', 'I honestly didn’t even want to publish this. It’s just a kind of self indulgent fic because I was morning Robb like he’s my dead husband.')
('84709216', '2026-05-12T05:04:46Z', 'https://archiveofourown.org/works/84709216', 'Scraped', "He's My Man", 'hax23', '["Mature"]', '["F/M"]', '["A Knight of the Seven Kingdoms (TV)", "A Song of Ice and Fire - George R. R. Martin"]', '["Aerion Targaryen (Son of Maekar I)/You"]', '["Aerion Targaryen (Son of Maekar I)", "Reader", "You"]', '["Established Relationship", "Fluff and Angst", "Manipulation", "Poisoning", "Wildfire (A Song of Ice and Fire)", "Altered Mental States", "Mild Gore", "Not Beta Read", "reader is the warning"]', 'Your husband had always suffered from dreams about dragons. You want to make them go away, even if it means giving him strange potions and elixirs from the Grand Maester of the Red Keep. Even if it means giving him wildfire. Aerion Targaryen x Baratheon reader')
('84711126', '2026-05-12T05:54:32Z', 'https://archiveofourown.org/works/84711126', 'Scraped', 'The Scarlet Queen from Old Town', 'Aera_Yoo', '["General Audiences"]', '["F/M", "Gen"]', '["House of the Dragon (TV)", "Marvel"]', '["Alicent Hightower & Aegon II Targaryen", "Alicent Hightower & Aemond \\"One-Eye\\" Targaryen", "Alicent Hightower & Helaena Targaryen", "Alicent Hightower & Daeron Targaryen (Son of Viserys I)", "Alicent Hightower & Otto Hightower", "Alicent Hightower & Gwayne Hightower"]', '["Alicent Hightower", "Wanda Maximoff", "Gwayne Hightower", "Otto Hightower", "Aegon II Targaryen", "Aemond \\"One-Eye\\" Targaryen", "Helaena Targaryen", "Viserys I Targaryen", "Rhaenyra Targaryen", "Daemon Targaryen", "Alicent Hightower ", " Aegon II Targaryen", " Aemond \\"One-Eye\\" Targaryen", " Helaena Targaryen", " Daeron Targaryen (Son of Viserys I)", " Otto Hightower", " Gwayne Hightower"]', '["House Hightower (A Song of Ice and Fire)", "Magic", "Golden Age", "BAMF Alicent Hightower", "BAMF Wanda Maximoff", "English Is Not The Author\'s First Language"]', 'Wanda Maximoff awakens as Alicent Hightower.')
('84714196', '2026-05-12T07:31:42Z', 'https://archiveofourown.org/works/84714196', 'Scraped', 'A Squire of the Seven Kingdoms', 'MirandaTook444', '["Teen And Up Audiences"]', '["Gen"]', '["A Song of Ice and Fire - George R. R. Martin", "Game of Thrones (TV)", "A Knight of the Seven Kingdoms (TV)"]', '["Dunk | Duncan the Tall & Aegon V \\"Egg\\" Targaryen"]', '["Dunk | Duncan the Tall (A Song of Ice and Fire)", "Aegon V \\"Egg\\" Targaryen", "Lyonel Baratheon", "Raymun Fossoway", "Baelor \\"Breakspear\\" Targaryen", "Aerion Targaryen (Son of Maekar I)", "Maekar I Targaryen", "Daeron Targaryen (Son of Maekar I)", "Maester Aemon Targaryen", "Dunk ", " Duncan the Tall ", " Aegon V \\"Egg\\" Targaryen"]', '["Retelling", "POV Aegon V \\"Egg\\" Targaryen"]', "The story we know, but from Egg's perspective. I really wanted to read what went down from Aegon's perspective and since no one was writing it (at least I couldn't find it, if anyone knows, tell me. I'd love to read), I decided to write it myself. This was supposed to be a Tumblr one-shot of the first meeting only, but a friend suggested that I continue, I'm going to try to do the whole book.")
('84715021', '2026-05-12T07:58:32Z', 'https://archiveofourown.org/works/84715021', 'Scraped', 'The Silent Bell Knight', 'void--eyes (Captain_Nox)', '["Not Rated"]', '["F/M"]', '["A Knight of the Seven Kingdoms (TV)", "A Song of Ice and Fire & Related Fandoms"]', '["Baelor \\"Breakspear\\" Targaryen/Original Female Character(s)", "Lyonel Baratheon & Original Female Character(s)", "Duncan the Tall & Original Female Character(s)", "Baelor \\"Breakspear\\" Targaryen/Knight"]', '["Baelor \\"Breakspear\\" Targaryen", "Original Female Character(s)", "Original Female Character(s) of Color", "Lyonel Baratheon", "Dunk | Duncan the Tall (A Song of Ice and Fire)", "Valarr Targaryen", "Original Male Character(s)", "Aerion Targaryen (Son of Maekar I)", "Tourney at Ashford attendees", "Maekar I Targaryen", "Daeron Targaryen (Son of Maekar I)", "Aegon V \\"Egg\\" Targaryen", "Raymun Fossoway", "Lyonel Baratheon ", " Original Female Character(s)", "Duncan the Tall ", "Knight"]', '["Female Knight", "False knight", "Mystery knight", "Whatever you want to call them", "female mystery knight", "past established friendship", "~romantic relationship~", "OC is a bastard of the Red Mountains", "First Blackfyre Rebellion | Daemon I Blackfyre vs. Daeron II Targaryen", "Tourney at Ashford Meadow (A Song of Ice and Fire)", "Pre-Tourney at Ashford Meadow (A Song of Ice and Fire)", "OC has elements of PTSD", "Post War", "also a bit of a dive into the racial dynamics of the south", "And Classes", "also do i touch on the old magics? maybe", "Red Mountains", "Prince\'s Pass", "Kingsgrave", "The Greenblood", "i guess..things will get heated between them...", "who am I kidding", "can you tell tags are not my thing", "Dorne (A Song of Ice and Fire)", "my beloved"]', 'She knew him in their youth, and in their differing wars since. Paths twisted as sure as the locks hidden beneath helms, lost love masked as sure as it were coated in plated armours. Forgetting the Prince had become easy enough in the years since; easier when a tilt provided a warming pocket of coin. A melee dry lodgings. Even dealing with her own ghosts gave a well worn distraction. The Tourney at Ashford was the lover she sought, the brutality of the lords a lasting embrace. One that could fade a curse with a kiss of steel, to allow the Silent Bell Knight to finally step into their own— granted, there was no other giving halt.')
('84719016', '2026-05-12T10:29:08Z', 'https://archiveofourown.org/works/84719016', 'Scraped', 'Brightflame, part IV', 'caraxesrider', '["Mature"]', '["F/M"]', '["A Knight of the Seven Kingdoms (TV)"]', '["Aerion Targaryen (Son of Maekar I)/You"]', '["Aerion Targaryen (Son of Maekar I)", "Maegor Targaryen (Son of Aerion)", "You"]', '["Female Reader-Insert", "No Use of Y/N for Reader-Insert", "No Smut", "Wildfire (A Song of Ice and Fire)", "Evil Aerion Targaryen (Son of Maekar I)", "Family Issues", "Married Couple", "Unhealthy Relationships", "Angst", "Hurt No Comfort", "Ambiguous/Open Ending"]', 'Anger was now rooted in your family. Between Maegor wanting to change his life and Aerion trying to maintain a good image, things are difficult.')
('84720706', '2026-05-12T11:32:18Z', 'https://archiveofourown.org/works/84720706', 'Scraped', 'El Destripador de Desembarco del Rey', 'RD_Blanc91', '["Mature"]', '["M/M"]', '["A Knight of the Seven Kingdoms (TV)", "A Song of Ice and Fire & Related Fandoms", "A Song of Ice and Fire - George R. R. Martin"]', '["Dunk | Duncan the Tall/Aerion Targaryen (Son of Maekar I)"]', '["Dunk | Duncan the Tall (A Song of Ice and Fire)", "Aerion Targaryen (Son of Maekar I)", "Tanselle Too-Tall (A Song of Ice and Fire)", "Raymun Fossoway", "Daeron Targaryen (Son of Maekar I)", "Maekar I Targaryen", "Dunk ", " Duncan the Tall"]', '["Murder Mystery", "Police Uniforms", "Alternate Universe - Police", "Brutal Murder", "Assassination", "Anal Sex", "Rough Oral Sex", "Oral Sex", "Falling In Love", "Boys In Love"]', 'La vida amorosa del agente Aerion Targaryen tomó un giro radical cuando conoce a un hombre alto y misterioso. Mientras tanto, en Desembarco del Rey de están cometiendo una serie de crímenes, que tienen intrigada a la policía y temerosa a un sector de la población. ¿Aerion podrá lidiar con el caso y con el hombre que ama?')
('84721256', '2026-05-12T11:52:55Z', 'https://archiveofourown.org/works/84721256', 'Scraped', 'Born Beneath a Dying Star', 'Aine091012', '["Mature"]', '["F/F", "F/M", "M/M"]', '["House of the Dragon (TV)"]', '["Aemond \\"One-Eye\\" Targaryen/Original Female Character(s)", "Helaena Targaryen/Jacaerys Velaryon", "Aegon II Targaryen/Baela Targaryen", "Rhaena Targaryen (Daughter of Daemon)/Lucerys Velaryon (Son of Rhaenyra)", "Daemon Targaryen/Rhaenyra Targaryen", "Harwin Strong/Rhaenyra Targaryen", "Rhaenyra Targaryen/Laenor Velaryon", "Alicent Hightower/Viserys I Targaryen"]', '["Aemond \\"One-Eye\\" Targaryen", "Helaena Targaryen", "Jacaerys Velaryon", "Aegon II Targaryen", "Baela Targaryen", "Rhaena Targaryen (Daughter of Daemon)", "Lucerys Velaryon (Son of Rhaenyra)", "Daemon Targaryen", "Rhaenyra Targaryen", "Laenor Velaryon", "Alicent Hightower", "Viserys I Targaryen", "Harwin Strong", "Larys Strong", "Otto Hightower", "Original Female Character(s)"]', '["Alicent Hightower & Rhaenyra Targaryen Friendship", "Targaryen men have a thing for their nieces", "Targcest | Targaryen Incest (A Song of Ice and Fire)", "Aemond \\"One-Eye\\" Targaryen is Whipped", "Otto Hightower Being an Asshole", "Dragon Dreamers & Dragon Dreams (A Song of Ice and Fire)", "Magic", "Daemon Targaryen is Oc\'s Parent", "Everyone ignores the Warning\'s About the Dance", "The Oc\'s get\'s mad and takes the matter into her own hands", "Arranged Marriage", "Talking To Dead People", "Uncle/Niece Incest", "Possessive Behavior", "Other Additional Tags to Be Added", "The OC would kill for Helaena", "so will helaena"]', "Rhaenyra Targaryen’s firstborn was a girl with a strange dragon. A girl who saw the past, lived in the present, and dreamt of the future. A girl raised by both the living and the dead; by those remembered in history and those long since forgotten. She would later be remembered as the most powerful queen Westeros had ever known— a dreamer, a conqueror, and the last lingering ghost of Old Valyria. Or: Years later, Daemon Targaryen finally understands why his brother had never wanted him near Rhaenyra—because now he wants to kill his nephew's for looking at his daughter's the same way he once looked at Viserys’ heir. Viserys, surely, is laughing in his grave.")
('84722136', '2026-05-12T12:19:21Z', 'https://archiveofourown.org/works/84722136', 'Scraped', '--Insert Something Dragon Related-- (Rhaenyra SI)', 'ChaosSpartan575', '["Mature"]', '["F/F", "F/M"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '[]', '[]', '[]', 'Sometimes, the right person at the wrong time, can make an even bigger mess than what supposed to be or completely sidestep the whole mess before it starts. Either way, the tidal wave arrives all the same.')
('84723001', '2026-05-12T12:40:34Z', 'https://archiveofourown.org/works/84723001', 'Scraped', 'Hands do not dream', 'Nessie (Miss_Bowen)', '["General Audiences"]', '["F/M"]', '["Game of Thrones (TV)"]', '["Jaime Lannister/Brienne of Tarth"]', '["Jaime Lannister", "Brienne of Tarth"]', '["Banter", "Mild Hurt/Comfort", "Short", "Permanent Injury"]', 'This is a very short (and kind of irrelevant) short look into Jaime/Brienne. Spoilers for early/mid season 3 GoT.')
('84723496', '2026-05-12T12:58:30Z', 'https://archiveofourown.org/works/84723496', 'Scraped', 'Beneath the Black Dragon', 'Dorumuk', '["Mature"]', '["F/M"]', '["A Song of Ice and Fire & Related Fandoms", "Game of Thrones (TV)"]', '["Original Blackfyre Character/Ashara Dayne"]', '["Original Blackfyre Character(s)", "Original Male Character(s)", "House Blackfyre Characters (A Song of Ice and Fire)", "Aerys II Targaryen", "Rhaegar Targaryen", "Elia Martell", "Lyanna Stark", "Ned Stark", "Robert Baratheon", "Stannis Baratheon", "Ashara Dayne", "Arthur Dayne", "Brandon Stark", "Rickard Stark", "Original Blackfyre Character"]', '["Alternate Universe - Canon Divergence", "House Blackfyre (A Song of Ice and Fire)", "Targaryen Restoration", "Essos (A Song of Ice and Fire)", "Elia Martell Lives", "Rhaenys Targaryen (Daughter of Elia) Lives", "Aegon Targaryen (Son of Elia) Lives", "Rhaella Targaryen (Wife of Aerys II) Lives", "Lyanna Stark Lives", "Brandon Stark Lives"]', 'Kang Doyun died at his desk in Seoul, crushed beneath deadlines, defect reports, and a life that had long since learned to call exhaustion normal. Valar Blackfyre should have died in Tyrosh, thrown from his horse before the world ever learned his hidden name. Instead, both men wake in the same body. One is a modern engineer with memories of a world where chains are invisible. The other is the secret son of Maelys Blackfyre, raised on old wounds, forbidden names, and the bitter inheritance of the black dragon. Across the Narrow Sea, the Targaryen dynasty has begun to tremble. In Tyrosh, a black ember draws breath. Their first plan is simple. Do not die.')
('84737721', '2026-05-12T18:17:14Z', 'https://archiveofourown.org/works/84737721', 'Scraped', 'The Life of a Woman', 'Seren_king', '["Mature"]', '["F/M", "Gen", "Other"]', '["A Song of Ice and Fire - George R. R. Martin", "A Song of Ice and Fire & Related Fandoms"]', '["Rhaegar Targaryen/Original Female Character"]', '["Rhaegar Targaryen", "Ned Stark", "Sansa Stark", "Arya Stark", "Jon Snow", "Catelyn Tully Stark", "Robert Baratheon", "Tywin Lannister", "Rhaella Targaryen (Wife of Aerys II)", "Original Female Character(s)", "Original Male Character(s)", "Wildling | Free Folk Characters (A Song of Ice and Fire)", "House Stark Characters (A Song of Ice and Fire)", "House Targaryen Characters (A Song of Ice and Fire)", "Original Female Character"]', '["Hurt/Comfort", "Angst", "Sex", "Whimsical", "Robert Baratheon\'s Rebellion", "Women in ASOIAF tragedy", "Pre-Book 1: A Game of Thrones (A Song of Ice and Fire)", "Westeros (A Song of Ice and Fire)", "proof reading is for the weak", "Graphic Description", "Kingslanding"]', None)
('84737881', '2026-05-12T18:21:27Z', 'https://archiveofourown.org/works/84737881', 'Scraped', 'Эшфордский турнир', '3efirka', '["General Audiences"]', '["Gen"]', '["A Knight of the Seven Kingdoms (TV)", "A Song of Ice and Fire - George R. R. Martin"]', '[]', '["Daella Targaryen (Daughter of Maekar I)", "Aerion Targaryen (Son of Maekar I)", "Maekar I Targaryen", "Baelor \\"Breakspear\\" Targaryen", "Valarr Targaryen", "Daeron Targaryen (Son of Maekar I)", "Aegon V \\"Egg\\" Targaryen", "Dunk | Duncan the Tall (A Song of Ice and Fire)", "Original Male Character(s)"]', '[]', 'Эшфордский турнир глазами принцессы Дейллы Таргариен, дочери Мейкара.')

Content based filtering using tags of my bookmarked works and all works

In [ ]:
import sqlite3

conn = sqlite3.connect('ao3_works.db')
c = conn.cursor()

bookmarked_works_df = pd.read_sql_query('''
          Select id, rating, categories, fandoms, relationships, characters, freeform_tags
          from all_works
          where id in (
                            Select work_id
                            from my_bookmarks
                      )
          and status = "Scraped"
          ''',
          conn)


not_bookmarked_works_df = pd.read_sql_query('''
          Select id, rating, categories, fandoms, relationships, characters, freeform_tags
          from all_works
          where id not in (
                            Select work_id
                            from my_bookmarks
                      )
          and status = "Scraped"
          ''',
          conn)

conn.close()

In [ ]:
bookmarked_works_df

,id,rating,categories,fandoms,relationships,characters,freeform_tags
0,50992918,"[""Mature""]","[""F/F"", ""F/M"", ""Gen"", ""Multi""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Jon Snow/Sansa Stark"", ""Jon Snow/Daenerys Ta...","[""Daenerys Targaryen"", ""Jon Snow"", ""Sansa Star...","[""R Plus L Equals J"", ""Prophetic dreams someti..."
1,55165036,"[""Mature""]",[],"[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Ned Stark/Shaena Targaryen"", ""Catelyn Tully ...","[""Ned Stark"", ""Rickard Stark"", ""Brandon Stark""...","[""Ned Stark Needs a Hug"", ""Alternate Universe ..."
2,56181721,"[""Mature""]","[""Gen"", ""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Elia Martell/Rhaegar Targaryen"", ""Ashara Day...","[""Rhaegar Targaryen"", ""Aerys II Targaryen"", ""T...","[""Alternate Universe - Canon Divergence"", ""No ..."
3,62910172,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire - George R. R. Martin""]","[""Jon Snow & Rhaegar Targaryen"", ""Elia Martell...","[""Jon Snow"", ""Daenerys Targaryen"", ""Rhaenys Ta...","[""King Rhaegar Targaryen"", ""Robert's Rebellion..."
4,73894251,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Jon Snow/Sansa Stark"", ""Jon Snow/Daenerys Ta...","[""Jon Snow"", ""Daenerys Targaryen"", ""Sansa Star...","[""R Plus L Equals J | Lyanna Stark and Rhaegar..."
5,75267501,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Jon Snow/Original Female Character(s)"", ""Jon...","[""Original Female Character(s)"", ""Characters F...","[""Original Noble House (A Song of Ice and Fire..."
6,76423276,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Cersei Lannister/Jon Snow"", ""Ashara Dayne/Jo...","[""Jon Snow"", ""Cersei Lannister"", ""Tyrion Lanni...","[""Alternate Universe - Canon Divergence"", ""Jon..."
7,81993896,"[""Mature""]","[""F/M"", ""Gen""]","[""Game of Thrones (TV)"", ""A Song of Ice and Fi...","[""Jon Snow/Margaery Tyrell"", ""Ysilla Royce/Rob...","[""Jon Snow"", ""Robb Stark"", ""Ned Stark"", ""Catel...","[""Action/Adventure"", ""Action & Romance"", ""Cano..."

In [ ]:
not_bookmarked_works_df

,id,rating,categories,fandoms,relationships,characters,freeform_tags
0,84723496,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Original Blackfyre Character/Ashara Dayne""]","[""Original Blackfyre Character(s)"", ""Original ...","[""Alternate Universe - Canon Divergence"", ""Hou..."
1,84723001,"[""General Audiences""]","[""F/M""]","[""Game of Thrones (TV)""]","[""Jaime Lannister/Brienne of Tarth""]","[""Jaime Lannister"", ""Brienne of Tarth""]","[""Banter"", ""Mild Hurt/Comfort"", ""Short"", ""Perm..."
2,84722136,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...",[],[],[]
3,84721256,"[""Mature""]","[""F/F"", ""F/M"", ""M/M""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen/Original Female...","[""Aemond \""One-Eye\"" Targaryen"", ""Helaena Targ...","[""Alicent Hightower & Rhaenyra Targaryen Frien..."
4,84720706,"[""Mature""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall/Aerion Targaryen (Son...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Murder Mystery"", ""Police Uniforms"", ""Alterna..."
5,84719016,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)""]","[""Aerion Targaryen (Son of Maekar I)/You""]","[""Aerion Targaryen (Son of Maekar I)"", ""Maegor...","[""Female Reader-Insert"", ""No Use of Y/N for Re..."
6,84715021,"[""Not Rated""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Baelor \""Breakspear\"" Targaryen/Original Fem...","[""Baelor \""Breakspear\"" Targaryen"", ""Original ...","[""Female Knight"", ""False knight"", ""Mystery kni..."
7,84714196,"[""Teen And Up Audiences""]","[""Gen""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Dunk | Duncan the Tall & Aegon V \""Egg\"" Tar...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Retelling"", ""POV Aegon V \""Egg\"" Targaryen""]"
8,84711126,"[""General Audiences""]","[""F/M"", ""Gen""]","[""House of the Dragon (TV)"", ""Marvel""]","[""Alicent Hightower & Aegon II Targaryen"", ""Al...","[""Alicent Hightower"", ""Wanda Maximoff"", ""Gwayn...","[""House Hightower (A Song of Ice and Fire)"", ""..."
9,84709216,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Aerion Targaryen (Son of Maekar I)/You""]","[""Aerion Targaryen (Son of Maekar I)"", ""Reader...","[""Established Relationship"", ""Fluff and Angst""..."
10,84708881,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)"", ""A Song of Ice and Fi...","[""Robb Stark/You""]","[""Robb Stark"", ""Catelyn Tully Stark"", ""You""]","[""I miss Robb"", ""Married Life"", ""Not even lowk..."
11,84708701,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Daeron Targaryen (Son of Maekar I)/You""]","[""Daeron Targaryen (Son of Maekar I)"", ""Aerion...","[""Character Death"", ""There is sex scenes but n..."
12,84708291,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Daeron Targaryen (Son of Maekar I)/You""]","[""Daeron Targaryen (Son of Maekar I)"", ""Maekar...","[""Character Death"", ""Alcohol Abuse/Alcoholism""..."
13,84701301,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)""]",[],"[""Jon Snow"", ""Ghost | Jon Snow's Direwolf"", ""N...","[""Westeros (A Song of Ice and Fire)"", ""Essos (..."
14,84699031,"[""Mature""]",[],"[""A Song of Ice and Fire - George R. R. Martin""]","[""Sandor Clegane/Sansa Stark""]","[""Sansa Stark"", ""Sandor Clegane""]","[""First Kiss"", ""Sex"", ""True Love"", ""Protective..."
15,84696726,"[""General Audiences""]","[""Gen""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen & Helaena Targa...","[""Aemond \""One-Eye\"" Targaryen"", ""Helaena Targ...","[""Alternate Universe - Hogwarts"", ""Aegon II Ta..."
16,84769896,"[""Not Rated""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)""]","[""Dunk | Duncan the Tall/Baelor \""Breakspear\""...","[""Baelor \""Breakspear\"" Targaryen"", ""Dunk | Du...","[""Alternate Universe - Modern Setting"", ""Medie..."
17,84765921,"[""Teen And Up Audiences""]","[""F/M""]","[""House of the Dragon (TV)""]","[""Daemon Targaryen/Rhaenyra Targaryen"", ""Daemo...","[""Daemon Targaryen"", ""Rhaenyra Targaryen"", ""Ae...",[]
18,84763896,"[""Mature""]","[""F/M"", ""Gen"", ""M/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Lyonel Baratheon/Dunk | Duncan the Tall"", ""O...","[""Aerys II Targaryen"", ""Jaime Lannister"", ""Dun...","[""Parallels"", ""Character Study"", ""Parallels be..."
19,84762276,"[""Mature""]","[""Gen""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall & Rafe of Flea Bottom...","[""Original Female Character(s)"", ""Dunk | Dunca...","[""Alternate Universe - Canon Divergence"", ""Raf..."
20,84761826,"[""Not Rated""]",[],"[""House of the Dragon (TV)""]","[""Aemma Arryn/Viserys I Targaryen""]","[""Aemma Arryn"", ""Viserys I Targaryen""]",[]
21,84761796,"[""Not Rated""]",[],"[""Game of Thrones (TV)"", ""A Song of Ice and Fi...",[],"[""Sansa Stark"", ""Arya Stark"", ""Robb Stark"", ""J...","[""Magic"", ""shortstory"", ""Oneshot"", ""magicmirro..."
22,84752771,"[""Teen And Up Audiences""]","[""M/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Jon Snow/Robb Stark""]","[""Robb Stark"", ""Jon Snow"", ""Grey Wind | Robb S...","[""Drunk Jon Snow"", ""Love Confessions"", ""Drunke..."
23,84748536,"[""Teen And Up Audiences""]","[""F/M""]","[""Game of Thrones (TV)""]","[""Jorah Mormont/Daenerys Targaryen""]","[""Jorah Mormont"", ""Daenerys Targaryen""]",[]
24,84745361,"[""Not Rated""]",[],"[""Game of Thrones (TV)""]",[],[],[]
25,84744936,"[""Not Rated""]",[],"[""game of thrones""]",[],[],[]
26,84744381,"[""Teen And Up Audiences""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall/Aerion Targaryen (Son...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Alternate Universe"", ""Modern Era"", ""study ab..."
27,84743746,"[""Mature""]","[""F/F"", ""M/M"", ""Multi""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen/Lucerys Velaryo...","[""Lucerys Velaryon (Son of Rhaenyra)"", ""Aemond...","[""Questionable Consent"", ""Secret Identity"", ""P..."
28,84742296,"[""Teen And Up Audiences""]","[""Other""]","[""Game of Thrones (TV)""]","[""Sansa stark/vengence"", ""Sansa Stark & Lady S...","[""Sansa Stark"", ""Lady Stoneheart"", ""Joffrey Ba...","[""Gun Violence"", ""Revenge"", ""based off of a so..."
29,84738976,"[""Teen And Up Audiences""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Maekar I Targaryen/You""]","[""Maekar I Targaryen"", ""Aegon V \""Egg\"" Targar...","[""Fluff"", ""Angst"", ""Grief/Mourning"", ""nerd rea..."
30,84737881,"[""General Audiences""]","[""Gen""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...",[],"[""Daella Targaryen (Daughter of Maekar I)"", ""A...",[]
31,84737721,"[""Mature""]","[""F/M"", ""Gen"", ""Other""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Rhaegar Targaryen/Original Female Character""]","[""Rhaegar Targaryen"", ""Ned Stark"", ""Sansa Star...","[""Hurt/Comfort"", ""Angst"", ""Sex"", ""Whimsical"", ..."

In [ ]:
import json
import pandas as pd

# Weight for each tag type in the similarity calculation
tag_cols = {
    "rating": 0.5,
    "categories": 0.6,
    "fandoms": 0.4,
    "relationships": 1,
    "characters": 0.9,
    "freeform_tags": 0.9
}

def parse_json_list(value):
    if pd.isna(value) or value == "":
        return []

    values = json.loads(value)

    # clean whitespace + remove duplicates within that same cell
    cleaned = [str(v).strip() for v in values if str(v).strip()]
    return list(dict.fromkeys(cleaned))

In [ ]:
not_bookmarked_works_df

copy_of_not_bookmarked_works_df = not_bookmarked_works_df.copy()

for col in tag_cols.keys():
    copy_of_not_bookmarked_works_df[col] = copy_of_not_bookmarked_works_df[col].apply(parse_json_list)
copy_of_not_bookmarked_works_df

,id,rating,categories,fandoms,relationships,characters,freeform_tags
0,84723496,[Mature],[F/M],"[A Song of Ice and Fire & Related Fandoms, Gam...",[Original Blackfyre Character/Ashara Dayne],"[Original Blackfyre Character(s), Original Mal...","[Alternate Universe - Canon Divergence, House ..."
1,84723001,[General Audiences],[F/M],[Game of Thrones (TV)],[Jaime Lannister/Brienne of Tarth],"[Jaime Lannister, Brienne of Tarth]","[Banter, Mild Hurt/Comfort, Short, Permanent I..."
2,84722136,[Mature],"[F/F, F/M]","[A Song of Ice and Fire - George R. R. Martin,...",[],[],[]
3,84721256,[Mature],"[F/F, F/M, M/M]",[House of the Dragon (TV)],"[Aemond ""One-Eye"" Targaryen/Original Female Ch...","[Aemond ""One-Eye"" Targaryen, Helaena Targaryen...",[Alicent Hightower & Rhaenyra Targaryen Friend...
4,84720706,[Mature],[M/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Dunk | Duncan the Tall/Aerion Targaryen (Son ...,[Dunk | Duncan the Tall (A Song of Ice and Fir...,"[Murder Mystery, Police Uniforms, Alternate Un..."
5,84719016,[Mature],[F/M],[A Knight of the Seven Kingdoms (TV)],[Aerion Targaryen (Son of Maekar I)/You],"[Aerion Targaryen (Son of Maekar I), Maegor Ta...","[Female Reader-Insert, No Use of Y/N for Reade..."
6,84715021,[Not Rated],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...","[Baelor ""Breakspear"" Targaryen/Original Female...","[Baelor ""Breakspear"" Targaryen, Original Femal...","[Female Knight, False knight, Mystery knight, ..."
7,84714196,[Teen And Up Audiences],[Gen],"[A Song of Ice and Fire - George R. R. Martin,...","[Dunk | Duncan the Tall & Aegon V ""Egg"" Targar...",[Dunk | Duncan the Tall (A Song of Ice and Fir...,"[Retelling, POV Aegon V ""Egg"" Targaryen]"
8,84711126,[General Audiences],"[F/M, Gen]","[House of the Dragon (TV), Marvel]","[Alicent Hightower & Aegon II Targaryen, Alice...","[Alicent Hightower, Wanda Maximoff, Gwayne Hig...","[House Hightower (A Song of Ice and Fire), Mag..."
9,84709216,[Mature],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Aerion Targaryen (Son of Maekar I)/You],"[Aerion Targaryen (Son of Maekar I), Reader, You]","[Established Relationship, Fluff and Angst, Ma..."
10,84708881,[Mature],[F/M],"[Game of Thrones (TV), A Song of Ice and Fire ...",[Robb Stark/You],"[Robb Stark, Catelyn Tully Stark, You]","[I miss Robb, Married Life, Not even lowkey br..."
11,84708701,[Mature],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Daeron Targaryen (Son of Maekar I)/You],"[Daeron Targaryen (Son of Maekar I), Aerion Ta...","[Character Death, There is sex scenes but not ..."
12,84708291,[Mature],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Daeron Targaryen (Son of Maekar I)/You],"[Daeron Targaryen (Son of Maekar I), Maekar I ...","[Character Death, Alcohol Abuse/Alcoholism, De..."
13,84701301,[Mature],[F/M],[Game of Thrones (TV)],[],"[Jon Snow, Ghost | Jon Snow's Direwolf, Nymeri...","[Westeros (A Song of Ice and Fire), Essos (A S..."
14,84699031,[Mature],[],[A Song of Ice and Fire - George R. R. Martin],[Sandor Clegane/Sansa Stark],"[Sansa Stark, Sandor Clegane]","[First Kiss, Sex, True Love, Protective Sandor..."
15,84696726,[General Audiences],[Gen],[House of the Dragon (TV)],"[Aemond ""One-Eye"" Targaryen & Helaena Targarye...","[Aemond ""One-Eye"" Targaryen, Helaena Targaryen...","[Alternate Universe - Hogwarts, Aegon II Targa..."
16,84769896,[Not Rated],[M/M],[A Knight of the Seven Kingdoms (TV)],"[Dunk | Duncan the Tall/Baelor ""Breakspear"" Ta...","[Baelor ""Breakspear"" Targaryen, Dunk | Duncan ...","[Alternate Universe - Modern Setting, Medieval..."
17,84765921,[Teen And Up Audiences],[F/M],[House of the Dragon (TV)],"[Daemon Targaryen/Rhaenyra Targaryen, Daemon T...","[Daemon Targaryen, Rhaenyra Targaryen, Aegon I...",[]
18,84763896,[Mature],"[F/M, Gen, M/M]","[A Song of Ice and Fire & Related Fandoms, A S...","[Lyonel Baratheon/Dunk | Duncan the Tall, Orys...","[Aerys II Targaryen, Jaime Lannister, Dunk | D...","[Parallels, Character Study, Parallels between..."
19,84762276,[Mature],[Gen],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Dunk | Duncan the Tall & Rafe of Flea Bottom ...,"[Original Female Character(s), Dunk | Duncan t...","[Alternate Universe - Canon Divergence, Rafe o..."
20,84761826,[Not Rated],[],[House of the Dragon (TV)],[Aemma Arryn/Viserys I Targaryen],"[Aemma Arryn, Viserys I Targaryen]",[]
21,84761796,[Not Rated],[],"[Game of Thrones (TV), A Song of Ice and Fire ...",[],"[Sansa Stark, Arya Stark, Robb Stark, Jon Snow...","[Magic, shortstory, Oneshot, magicmirror, Fant..."
22,84752771,[Teen And Up Audiences],[M/M],"[A Song of Ice and Fire - George R. R. Martin,...",[Jon Snow/Robb Stark],"[Robb Stark, Jon Snow, Grey Wind | Robb Stark'...","[Drunk Jon Snow, Love Confessions, Drunken Con..."
23,84748536,[Teen And Up Audiences],[F/M],[Game of Thrones (TV)],[Jorah Mormont/Daenerys Targaryen],"[Jorah Mormont, Daenerys Targaryen]",[]
24,84745361,[Not Rated],[],[Game of Thrones (TV)],[],[],[]
25,84744936,[Not Rated],[],[game of thrones],[],[],[]
26,84744381,[Teen And Up Audiences],[M/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Dunk | Duncan the Tall/Aerion Targaryen (Son ...,[Dunk | Duncan the Tall (A Song of Ice and Fir...,"[Alternate Universe, Modern Era, study abroad,..."
27,84743746,[Mature],"[F/F, M/M, Multi]",[House of the Dragon (TV)],"[Aemond ""One-Eye"" Targaryen/Lucerys Velaryon (...","[Lucerys Velaryon (Son of Rhaenyra), Aemond ""O...","[Questionable Consent, Secret Identity, Prosti..."
28,84742296,[Teen And Up Audiences],[Other],[Game of Thrones (TV)],"[Sansa stark/vengence, Sansa Stark & Lady Ston...","[Sansa Stark, Lady Stoneheart, Joffrey Barathe...","[Gun Violence, Revenge, based off of a song, N..."
29,84738976,[Teen And Up Audiences],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Maekar I Targaryen/You],"[Maekar I Targaryen, Aegon V ""Egg"" Targaryen, ...","[Fluff, Angst, Grief/Mourning, nerd reader, Ma..."
30,84737881,[General Audiences],[Gen],"[A Knight of the Seven Kingdoms (TV), A Song o...",[],"[Daella Targaryen (Daughter of Maekar I), Aeri...",[]
31,84737721,[Mature],"[F/M, Gen, Other]","[A Song of Ice and Fire - George R. R. Martin,...",[Rhaegar Targaryen/Original Female Character],"[Rhaegar Targaryen, Ned Stark, Sansa Stark, Ar...","[Hurt/Comfort, Angst, Sex, Whimsical, Robert B..."

In [ ]:
copy_of_bookmarked_works_df = bookmarked_works_df.copy()

for col in tag_cols.keys():
    copy_of_bookmarked_works_df[col] = copy_of_bookmarked_works_df[col].apply(parse_json_list)
copy_of_bookmarked_works_df

,id,rating,categories,fandoms,relationships,characters,freeform_tags
0,50992918,[Mature],"[F/F, F/M, Gen, Multi]","[A Song of Ice and Fire - George R. R. Martin,...","[Jon Snow/Sansa Stark, Jon Snow/Daenerys Targa...","[Daenerys Targaryen, Jon Snow, Sansa Stark, Ne...","[R Plus L Equals J, Prophetic dreams sometimes..."
1,55165036,[Mature],[],"[A Song of Ice and Fire & Related Fandoms, A S...","[Ned Stark/Shaena Targaryen, Catelyn Tully Sta...","[Ned Stark, Rickard Stark, Brandon Stark, Shae...","[Ned Stark Needs a Hug, Alternate Universe - C..."
2,56181721,[Mature],"[Gen, F/F, F/M]","[A Song of Ice and Fire - George R. R. Martin,...","[Elia Martell/Rhaegar Targaryen, Ashara Dayne/...","[Rhaegar Targaryen, Aerys II Targaryen, Tywin ...","[Alternate Universe - Canon Divergence, No Rob..."
3,62910172,[Mature],[F/M],[A Song of Ice and Fire - George R. R. Martin],"[Jon Snow & Rhaegar Targaryen, Elia Martell/Rh...","[Jon Snow, Daenerys Targaryen, Rhaenys Targary...","[King Rhaegar Targaryen, Robert's Rebellion Fa..."
4,73894251,[Mature],"[F/F, F/M]","[A Song of Ice and Fire - George R. R. Martin,...","[Jon Snow/Sansa Stark, Jon Snow/Daenerys Targa...","[Jon Snow, Daenerys Targaryen, Sansa Stark, Ne...",[R Plus L Equals J | Lyanna Stark and Rhaegar ...
5,75267501,[Mature],[F/M],"[A Song of Ice and Fire - George R. R. Martin,...","[Jon Snow/Original Female Character(s), Jon Sn...","[Original Female Character(s), Characters From...",[Original Noble House (A Song of Ice and Fire)...
6,76423276,[Mature],[F/M],"[A Song of Ice and Fire - George R. R. Martin,...","[Cersei Lannister/Jon Snow, Ashara Dayne/Jon S...","[Jon Snow, Cersei Lannister, Tyrion Lannister,...","[Alternate Universe - Canon Divergence, Jon Sn..."
7,81993896,[Mature],"[F/M, Gen]","[Game of Thrones (TV), A Song of Ice and Fire ...","[Jon Snow/Margaery Tyrell, Ysilla Royce/Robb S...","[Jon Snow, Robb Stark, Ned Stark, Catelyn Tull...","[Action/Adventure, Action & Romance, Canon - A..."

In [ ]:
copy_of_bookmarked_works_df["is_bookmarked"] = 1
copy_of_not_bookmarked_works_df["is_bookmarked"] = 0

In [ ]:
all_works_df = pd.concat(
    [copy_of_bookmarked_works_df, copy_of_not_bookmarked_works_df],
    ignore_index=True
)
all_works_df

,id,rating,categories,fandoms,relationships,characters,freeform_tags,is_bookmarked
0,50992918,[Mature],"[F/F, F/M, Gen, Multi]","[A Song of Ice and Fire - George R. R. Martin,...","[Jon Snow/Sansa Stark, Jon Snow/Daenerys Targa...","[Daenerys Targaryen, Jon Snow, Sansa Stark, Ne...","[R Plus L Equals J, Prophetic dreams sometimes...",1
1,55165036,[Mature],[],"[A Song of Ice and Fire & Related Fandoms, A S...","[Ned Stark/Shaena Targaryen, Catelyn Tully Sta...","[Ned Stark, Rickard Stark, Brandon Stark, Shae...","[Ned Stark Needs a Hug, Alternate Universe - C...",1
2,56181721,[Mature],"[Gen, F/F, F/M]","[A Song of Ice and Fire - George R. R. Martin,...","[Elia Martell/Rhaegar Targaryen, Ashara Dayne/...","[Rhaegar Targaryen, Aerys II Targaryen, Tywin ...","[Alternate Universe - Canon Divergence, No Rob...",1
3,62910172,[Mature],[F/M],[A Song of Ice and Fire - George R. R. Martin],"[Jon Snow & Rhaegar Targaryen, Elia Martell/Rh...","[Jon Snow, Daenerys Targaryen, Rhaenys Targary...","[King Rhaegar Targaryen, Robert's Rebellion Fa...",1
4,73894251,[Mature],"[F/F, F/M]","[A Song of Ice and Fire - George R. R. Martin,...","[Jon Snow/Sansa Stark, Jon Snow/Daenerys Targa...","[Jon Snow, Daenerys Targaryen, Sansa Stark, Ne...",[R Plus L Equals J | Lyanna Stark and Rhaegar ...,1
5,75267501,[Mature],[F/M],"[A Song of Ice and Fire - George R. R. Martin,...","[Jon Snow/Original Female Character(s), Jon Sn...","[Original Female Character(s), Characters From...",[Original Noble House (A Song of Ice and Fire)...,1
6,76423276,[Mature],[F/M],"[A Song of Ice and Fire - George R. R. Martin,...","[Cersei Lannister/Jon Snow, Ashara Dayne/Jon S...","[Jon Snow, Cersei Lannister, Tyrion Lannister,...","[Alternate Universe - Canon Divergence, Jon Sn...",1
7,81993896,[Mature],"[F/M, Gen]","[Game of Thrones (TV), A Song of Ice and Fire ...","[Jon Snow/Margaery Tyrell, Ysilla Royce/Robb S...","[Jon Snow, Robb Stark, Ned Stark, Catelyn Tull...","[Action/Adventure, Action & Romance, Canon - A...",1
8,84723496,[Mature],[F/M],"[A Song of Ice and Fire & Related Fandoms, Gam...",[Original Blackfyre Character/Ashara Dayne],"[Original Blackfyre Character(s), Original Mal...","[Alternate Universe - Canon Divergence, House ...",0
9,84723001,[General Audiences],[F/M],[Game of Thrones (TV)],[Jaime Lannister/Brienne of Tarth],"[Jaime Lannister, Brienne of Tarth]","[Banter, Mild Hurt/Comfort, Short, Permanent I...",0
10,84722136,[Mature],"[F/F, F/M]","[A Song of Ice and Fire - George R. R. Martin,...",[],[],[],0
11,84721256,[Mature],"[F/F, F/M, M/M]",[House of the Dragon (TV)],"[Aemond ""One-Eye"" Targaryen/Original Female Ch...","[Aemond ""One-Eye"" Targaryen, Helaena Targaryen...",[Alicent Hightower & Rhaenyra Targaryen Friend...,0
12,84720706,[Mature],[M/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Dunk | Duncan the Tall/Aerion Targaryen (Son ...,[Dunk | Duncan the Tall (A Song of Ice and Fir...,"[Murder Mystery, Police Uniforms, Alternate Un...",0
13,84719016,[Mature],[F/M],[A Knight of the Seven Kingdoms (TV)],[Aerion Targaryen (Son of Maekar I)/You],"[Aerion Targaryen (Son of Maekar I), Maegor Ta...","[Female Reader-Insert, No Use of Y/N for Reade...",0
14,84715021,[Not Rated],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...","[Baelor ""Breakspear"" Targaryen/Original Female...","[Baelor ""Breakspear"" Targaryen, Original Femal...","[Female Knight, False knight, Mystery knight, ...",0
15,84714196,[Teen And Up Audiences],[Gen],"[A Song of Ice and Fire - George R. R. Martin,...","[Dunk | Duncan the Tall & Aegon V ""Egg"" Targar...",[Dunk | Duncan the Tall (A Song of Ice and Fir...,"[Retelling, POV Aegon V ""Egg"" Targaryen]",0
16,84711126,[General Audiences],"[F/M, Gen]","[House of the Dragon (TV), Marvel]","[Alicent Hightower & Aegon II Targaryen, Alice...","[Alicent Hightower, Wanda Maximoff, Gwayne Hig...","[House Hightower (A Song of Ice and Fire), Mag...",0
17,84709216,[Mature],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Aerion Targaryen (Son of Maekar I)/You],"[Aerion Targaryen (Son of Maekar I), Reader, You]","[Established Relationship, Fluff and Angst, Ma...",0
18,84708881,[Mature],[F/M],"[Game of Thrones (TV), A Song of Ice and Fire ...",[Robb Stark/You],"[Robb Stark, Catelyn Tully Stark, You]","[I miss Robb, Married Life, Not even lowkey br...",0
19,84708701,[Mature],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Daeron Targaryen (Son of Maekar I)/You],"[Daeron Targaryen (Son of Maekar I), Aerion Ta...","[Character Death, There is sex scenes but not ...",0
20,84708291,[Mature],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Daeron Targaryen (Son of Maekar I)/You],"[Daeron Targaryen (Son of Maekar I), Maekar I ...","[Character Death, Alcohol Abuse/Alcoholism, De...",0
21,84701301,[Mature],[F/M],[Game of Thrones (TV)],[],"[Jon Snow, Ghost | Jon Snow's Direwolf, Nymeri...","[Westeros (A Song of Ice and Fire), Essos (A S...",0
22,84699031,[Mature],[],[A Song of Ice and Fire - George R. R. Martin],[Sandor Clegane/Sansa Stark],"[Sansa Stark, Sandor Clegane]","[First Kiss, Sex, True Love, Protective Sandor...",0
23,84696726,[General Audiences],[Gen],[House of the Dragon (TV)],"[Aemond ""One-Eye"" Targaryen & Helaena Targarye...","[Aemond ""One-Eye"" Targaryen, Helaena Targaryen...","[Alternate Universe - Hogwarts, Aegon II Targa...",0
24,84769896,[Not Rated],[M/M],[A Knight of the Seven Kingdoms (TV)],"[Dunk | Duncan the Tall/Baelor ""Breakspear"" Ta...","[Baelor ""Breakspear"" Targaryen, Dunk | Duncan ...","[Alternate Universe - Modern Setting, Medieval...",0
25,84765921,[Teen And Up Audiences],[F/M],[House of the Dragon (TV)],"[Daemon Targaryen/Rhaenyra Targaryen, Daemon T...","[Daemon Targaryen, Rhaenyra Targaryen, Aegon I...",[],0
26,84763896,[Mature],"[F/M, Gen, M/M]","[A Song of Ice and Fire & Related Fandoms, A S...","[Lyonel Baratheon/Dunk | Duncan the Tall, Orys...","[Aerys II Targaryen, Jaime Lannister, Dunk | D...","[Parallels, Character Study, Parallels between...",0
27,84762276,[Mature],[Gen],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Dunk | Duncan the Tall & Rafe of Flea Bottom ...,"[Original Female Character(s), Dunk | Duncan t...","[Alternate Universe - Canon Divergence, Rafe o...",0
28,84761826,[Not Rated],[],[House of the Dragon (TV)],[Aemma Arryn/Viserys I Targaryen],"[Aemma Arryn, Viserys I Targaryen]",[],0
29,84761796,[Not Rated],[],"[Game of Thrones (TV), A Song of Ice and Fire ...",[],"[Sansa Stark, Arya Stark, Robb Stark, Jon Snow...","[Magic, shortstory, Oneshot, magicmirror, Fant...",0
30,84752771,[Teen And Up Audiences],[M/M],"[A Song of Ice and Fire - George R. R. Martin,...",[Jon Snow/Robb Stark],"[Robb Stark, Jon Snow, Grey Wind | Robb Stark'...","[Drunk Jon Snow, Love Confessions, Drunken Con...",0
31,84748536,[Teen And Up Audiences],[F/M],[Game of Thrones (TV)],[Jorah Mormont/Daenerys Targaryen],"[Jorah Mormont, Daenerys Targaryen]",[],0
32,84745361,[Not Rated],[],[Game of Thrones (TV)],[],[],[],0
33,84744936,[Not Rated],[],[game of thrones],[],[],[],0
34,84744381,[Teen And Up Audiences],[M/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Dunk | Duncan the Tall/Aerion Targaryen (Son ...,[Dunk | Duncan the Tall (A Song of Ice and Fir...,"[Alternate Universe, Modern Era, study abroad,...",0
35,84743746,[Mature],"[F/F, M/M, Multi]",[House of the Dragon (TV)],"[Aemond ""One-Eye"" Targaryen/Lucerys Velaryon (...","[Lucerys Velaryon (Son of Rhaenyra), Aemond ""O...","[Questionable Consent, Secret Identity, Prosti...",0
36,84742296,[Teen And Up Audiences],[Other],[Game of Thrones (TV)],"[Sansa stark/vengence, Sansa Stark & Lady Ston...","[Sansa Stark, Lady Stoneheart, Joffrey Barathe...","[Gun Violence, Revenge, based off of a song, N...",0
37,84738976,[Teen And Up Audiences],[F/M],"[A Knight of the Seven Kingdoms (TV), A Song o...",[Maekar I Targaryen/You],"[Maekar I Targaryen, Aegon V ""Egg"" Targaryen, ...","[Fluff, Angst, Grief/Mourning, nerd reader, Ma...",0
38,84737881,[General Audiences],[Gen],"[A Knight of the Seven Kingdoms (TV), A Song o...",[],"[Daella Targaryen (Daughter of Maekar I), Aeri...",[],0
39,84737721,[Mature],"[F/M, Gen, Other]","[A Song of Ice and Fire - George R. R. Martin,...",[Rhaegar Targaryen/Original Female Character],"[Rhaegar Targaryen, Ned Stark, Sansa Stark, Ar...","[Hurt/Comfort, Angst, Sex, Whimsical, Robert B...",0

In [ ]:
work_mapper = {work_id: i for i, work_id in enumerate(all_works_df["id"].unique())}
work_index = all_works_df["id"].map(work_mapper).values

In [ ]:
rows = []
cols = []
data = []

tag_mapper = {}
next_tag_idx = 0

for _, row in all_works_df.iterrows():
    work_idx = work_mapper[row["id"]]

    for col_name, weight in tag_cols.items():
        for tag in row[col_name]:
            feature_name = f"{col_name}::{tag}"

            if feature_name not in tag_mapper:
                tag_mapper[feature_name] = next_tag_idx
                next_tag_idx += 1

            tag_idx = tag_mapper[feature_name]

            rows.append(work_idx)
            cols.append(tag_idx)
            data.append(weight)

In [ ]:
tag_mapper

{'rating::Mature': 0,
 'categories::F/F': 1,
 'categories::F/M': 2,
 'categories::Gen': 3,
 'categories::Multi': 4,
 'fandoms::A Song of Ice and Fire - George R. R. Martin': 5,
 'fandoms::Game of Thrones (TV)': 6,
 'fandoms::A Song of Ice and Fire & Related Fandoms': 7,
 'relationships::Jon Snow/Sansa Stark': 8,
 'relationships::Jon Snow/Daenerys Targaryen': 9,
 'relationships::Sansa Stark/Daenerys Targaryen': 10,
 'characters::Daenerys Targaryen': 11,
 'characters::Jon Snow': 12,
 'characters::Sansa Stark': 13,
 'characters::Ned Stark': 14,
 'characters::Robb Stark': 15,
 'characters::Catelyn Tully Stark': 16,
 'characters::Bran Stark': 17,
 'characters::Brynden "Bloodraven" Rivers': 18,
 'characters::Young Griff (ASoIaF)': 19,
 'freeform_tags::R Plus L Equals J': 20,
 'freeform_tags::Prophetic dreams sometimes creepy sometimes not': 21,
 'freeform_tags::what is a threesome?': 22,
 'freeform_tags::Sometimes I just steal whole sentences from the book lmao': 23,
 'freeform_tags::Jonsa stuff comes first': 24,
 'freeform_tags::Then comes the threesome': 25,
 'freeform_tags::Its finally getting fun I swear': 26,
 'freeform_tags::jonsa': 27,
 'freeform_tags::Jonerys': 28,
 'freeform_tags::Slow Burn': 29,
 'freeform_tags::Jon does some shady shit': 30,
 'freeform_tags::i love sansa so much': 31,
 'freeform_tags::Soulmates': 32,
 'freeform_tags::Three hearts that beat as one': 33,
 'freeform_tags::Asoiaf lore is so cool': 34,
 'freeform_tags::book canon': 35,
 "freeform_tags::Jon Snow Doesn't Join the Night's Watch": 36,
 'freeform_tags::Jon Snow is a Targaryen': 37,
 'freeform_tags::Threesome - F/F/M': 38,
 'freeform_tags::but slow burn': 39,
 "freeform_tags::Jon Snow Goes to King's Landing": 40,
 "freeform_tags::dragon's egg": 41,
 'freeform_tags::High Fantasy': 42,
 'freeform_tags::No Harem': 43,
 'freeform_tags::This is not a Jon Wank fic': 44,
 'freeform_tags::Throuple': 45,
 'freeform_tags::Go read the fixed version': 46,
 'freeform_tags::THIS HAS BEEN ABANDONED': 47,
 'freeform_tags::And rewritten': 48,
 'relationships::Ned Stark/Shaena Targaryen': 49,
 'relationships::Catelyn Tully Stark/Ned Stark': 50,
 'relationships::Robert Baratheon/Lyanna Stark': 51,
 'relationships::Lyanna Stark/Rhaegar Targaryen': 52,
 'relationships::Elia Martell/Rhaegar Targaryen': 53,
 'relationships::Ashara Dayne/Brandon Stark': 54,
 'relationships::Cersei Lannister/Jaime Lannister': 55,
 'relationships::Cersei Lannister/Brandon Stark': 56,
 'relationships::Oberyn Martell/Ellaria Sand': 57,
 'relationships::Shaena Targaryen/Catelyn Tully Stark': 58,
 'characters::Rickard Stark': 59,
 'characters::Brandon Stark': 60,
 'characters::Shaena Targaryen': 61,
 'characters::Robert Baratheon': 62,
 'characters::Jon Arryn': 63,
 'characters::Rhaegar Targaryen': 64,
 'characters::Aerys II Targaryen': 65,
 'characters::Rhaella Targaryen (Wife of Aerys II)': 66,
 'characters::Barristan Selmy': 67,
 'characters::Tywin Lannister': 68,
 'characters::Jaime Lannister': 69,
 'characters::Cersei Lannister': 70,
 'characters::Lyanna Stark': 71,
 'characters::Benjen Stark': 72,
 'characters::Arthur Dayne': 73,
 'characters::Thoros of Myr (A Song of Ice and Fire)': 74,
 'characters::Original Characters': 75,
 'characters::Original Catelyn Tully Stark/Ned Stark Child(ren)': 76,
 'characters::Willam Dustin': 77,
 'characters::Yohn Royce': 78,
 'characters::Elys Arryn': 79,
 'characters::Anya Waynwood': 80,
 'characters::House Hightower Characters (A Song of Ice and Fire)': 81,
 'characters::Mace Tyrell': 82,
 'characters::Leyton Hightower': 83,
 'characters::Baelor Hightower': 84,
 'characters::Olenna Tyrell': 85,
 'characters::House Redwyne Characters (A Song of Ice and Fire)': 86,
 'characters::Hoster Tully': 87,
 'characters::Brynden "Blackfish" Tully': 88,
 'characters::Elia Martell': 89,
 'characters::Ashara Dayne': 90,
 'characters::Oberyn Martell': 91,
 'characters::Ellaria Sand': 92,
 'freeform_tags::Ned Stark Needs a Hug': 93,
 'freeform_tags::Alternate Universe - Canon Divergence': 94,
 'freeform_tags::POV Ned Stark': 95,
 "freeform_tags::Pre-Robert's Rebellion Against the Targaryens": 96,
 'freeform_tags::The Vale of Arryn (A Song of Ice and Fire)': 97,
 'freeform_tags::Shaena Targaryen Lives': 98,
 'relationships::Ashara Dayne/Ned Stark': 99,
 'relationships::past Lyanna Stark/Rhaegar Targaryen - Relationship': 100,
 'relationships::Jon Snow/Mya Stone': 101,
 'relationships::Rhaegar Targaryen/Margaery Tyrell': 102,
 'characters::Aegon Targaryen (Son of Elia)': 103,
 'characters::Rhaenys Targaryen (Daughter of Elia)': 104,
 'characters::Oswell Whent': 105,
 'characters::Richard Lonmouth': 106,
 'characters::Margaery Tyrell': 107,
 'characters::Viserys Targaryen (Brother of Daenerys)': 108,
 'characters::Mya Stone': 109,
 'characters::Myles Mooton': 110,
 'characters::Jon Connington': 111,
 'characters::Stannis Baratheon': 112,
 'characters::past Lyanna Stark': 113,
 'characters::Rhaegar Targaryen - Relationship': 114,
 "freeform_tags::No Robert's Rebellion | Robert Baratheon Never Rebels Against the Targaryens": 115,
 'freeform_tags::Canon-Typical Violence': 116,
 'freeform_tags::Politics': 117,
 'freeform_tags::Dragons': 118,
 'freeform_tags::Targaryen-on-Targaryen violence': 119,
 'relationships::Jon Snow & Rhaegar Targaryen': 120,
 'relationships::Elia Martell & Jon Snow': 121,
 'relationships::Jon Snow & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)': 122,
 'relationships::Benjen Stark & Robb Stark': 123,
 'relationships::Jon Snow & Daenerys Targaryen': 124,
 'relationships::Elia Martell & Aegon Targaryen (Son of Elia) & Rhaenys Targaryen (Daughter of Elia)': 125,
 'characters::Tyrion Lannister': 126,
 'characters::The Others | White Walker Character(s) (A Song of Ice and Fire)': 127,
 'freeform_tags::King Rhaegar Targaryen': 128,
 "freeform_tags::Robert's Rebellion Fails | Rhaegar Targaryen Wins": 129,
 "freeform_tags::R Plus L Equals J | Lyanna Stark and Rhaegar Targaryen are Jon Snow's Parents": 130,
 'freeform_tags::Alternate Universe - Reincarnation': 131,
 'freeform_tags::Post-Book 5: A Dance with Dragons (A Song of Ice and Fire)': 132,
 "freeform_tags::Jon Snow's Name is Aemon": 133,
 'freeform_tags::Character Study': 134,
 'freeform_tags::Epic': 135,
 'freeform_tags::House Blackfyre (A Song of Ice and Fire)': 136,
 'relationships::Jon Snow/Sansa Stark/Daenerys Targaryen': 137,
 'freeform_tags::What if dragon egg?': 138,
 'freeform_tags::Threesome': 139,
 'freeform_tags::Jon does some shady shit...again': 140,
 'freeform_tags::No Bashing': 141,
 'freeform_tags::rewritten': 142,
 'freeform_tags::I still love Sansa way too much': 143,
 'relationships::Jon Snow/Original Female Character(s)': 144,
 'relationships::Jon Snow & Original Female Character(s)': 145,
 'relationships::Jon Snow & Arya Stark & Bran Stark & Rickon Stark & Robb Stark & Sansa Stark': 146,
 "relationships::Ghost | Jon Snow's Direwolf & Jon Snow": 147,
 'relationships::Jon Snow & Ned Stark': 148,
 'characters::Original Female Character(s)': 149,
 'characters::Characters From The North (A Song of Ice and Fire)': 150,
 "characters::Ghost | Jon Snow's Direwolf": 151,
 'characters::Arya Stark': 152,
 "characters::Nymeria | Arya Stark's Direwolf": 153,
 'characters::Theon Greyjoy': 154,
 'characters::Rickon Stark': 155,
 "characters::Summer | Bran Stark's Direwolf": 156,
 "characters::Shaggydog | Rickon Stark's Direwolf": 157,
 'characters::Maester Luwin of Winterfell (A Song of Ice and Fire)': 158,
 'characters::Rodrik Cassel': 159,
 'characters::Jory Cassel': 160,
 'characters::Harwin the Winterfell Guard (A Song of Ice and Fire)': 161,
 'characters::Joffrey Baratheon': 162,
 'characters::Ghost': 163,
 "characters::Jon Snow's Direwolf": 164,
 'freeform_tags::Original Noble House (A Song of Ice and Fire)': 165,
 'freeform_tags::Northern Culture & Customs (A Song of Ice and Fire)': 166,
 'freeform_tags::The North (A Song of Ice and Fire)': 167,
 'freeform_tags::The Wolfswood (A Song of Ice and Fire)': 168,
 'freeform_tags::Winterfell (A Song of Ice and Fire)': 169,
 'freeform_tags::House Stark (A Song of Ice and Fire)': 170,
 'freeform_tags::Author Supports House Stark (A Song of Ice and Fire)': 171,
 'freeform_tags::Married Jon Snow': 172,
 'freeform_tags::Childhood Friends to Lovers': 173,
 'freeform_tags::Hunters & Hunting': 174,
 'freeform_tags::Wargs & Warging (A Song of Ice and Fire)': 175,
 "freeform_tags::Ghost | Jon Snow's Direwolf is a Good Boy": 176,
 'freeform_tags::Joffrey Baratheon Being an Asshole': 177,
 'freeform_tags::Robert Baratheon Being an Asshole': 178,
 'freeform_tags::Catelyn Tully Stark is Not Nice': 179,
 'freeform_tags::Westerosi Politics (A Song of Ice and Fire)': 180,
 'freeform_tags::The Old Gods (A Song of Ice and Fire)': 181,
 'freeform_tags::Weirwood Trees (A Song of Ice and Fire)': 182,
 'freeform_tags::Skinchangers & Skinchanging (A Song of Ice and Fire)': 183,
 'freeform_tags::Mentioned Rhaegar Targaryen': 184,
 'freeform_tags::Mentioned Lyanna Stark': 185,
 'relationships::Cersei Lannister/Jon Snow': 186,
 'relationships::Ashara Dayne/Jon Snow': 187,
 'freeform_tags::Seduction': 188,
 'freeform_tags::Fluff and Angst': 189,
 'relationships::Jon Snow/Margaery Tyrell': 190,
 'relationships::Ysilla Royce/Robb Stark': 191,
 'relationships::Roslin Frey/Edmure Tully': 192,
 'relationships::Sansa Stark/Willas Tyrell': 193,
 'relationships::Garlan Tyrell/Desmera Redwyne': 194,
 'characters::Loras Tyrell': 195,
 'characters::House Tyrell Characters (A Song of Ice and Fire)': 196,
 'characters::House Stark Characters (A Song of Ice and Fire)': 197,
 'characters::Davos Seaworth': 198,
 'characters::Jorah Mormont': 199,
 'characters::House Lannister Characters (A Song of Ice and Fire)': 200,
 'characters::Renly Baratheon': 201,
 'characters::Myrcella Baratheon': 202,
 'characters::House Baratheon Characters (A Song of Ice and Fire)': 203,
 'characters::House Martell Characters (A Song of Ice and Fire)': 204,
 'characters::Edmure Tully': 205,
 'characters::House Tully Characters (A Song of Ice and Fire)': 206,
 'characters::Lysa Tully Arryn': 207,
 'characters::House Arryn Characters (A Song of Ice and Fire)': 208,
 'characters::Petyr Baelish': 209,
 'characters::Aurane Waters': 210,
 'characters::Ysilla Royce': 211,
 'characters::House Royce Characters (A Song of Ice and Fire)': 212,
 'characters::Lucas Blackwood': 213,
 'characters::Randyll Tarly': 214,
 'characters::Paxter Redwyne': 215,
 'characters::Monford Velaryon': 216,
 'characters::Basically ALL A Song of Ice and Fire Characters': 217,
 'characters::Roslin Frey': 218,
 'characters::Willas Tyrell': 219,
 'characters::Garlan Tyrell': 220,
 'characters::Desmera Redwyne': 221,
 'freeform_tags::Action/Adventure': 222,
 'freeform_tags::Action & Romance': 223,
 'freeform_tags::Canon - A Song of Ice and Fire Series & Game of Thrones (TV) Combination': 224,
 'freeform_tags::Manipulation': 225,
 'freeform_tags::Jon Snow is Not Called Aegon': 226,
 'freeform_tags::Jon Snow Knows Something': 227,
 'freeform_tags::Weekly Updates': 228,
 'relationships::Original Blackfyre Character/Ashara Dayne': 229,
 'characters::Original Blackfyre Character(s)': 230,
 'characters::Original Male Character(s)': 231,
 'characters::House Blackfyre Characters (A Song of Ice and Fire)': 232,
 'characters::Original Blackfyre Character': 233,
 'freeform_tags::Targaryen Restoration': 234,
 'freeform_tags::Essos (A Song of Ice and Fire)': 235,
 'freeform_tags::Elia Martell Lives': 236,
 'freeform_tags::Rhaenys Targaryen (Daughter of Elia) Lives': 237,
 'freeform_tags::Aegon Targaryen (Son of Elia) Lives': 238,
 'freeform_tags::Rhaella Targaryen (Wife of Aerys II) Lives': 239,
 'freeform_tags::Lyanna Stark Lives': 240,
 'freeform_tags::Brandon Stark Lives': 241,
 'rating::General Audiences': 242,
 'relationships::Jaime Lannister/Brienne of Tarth': 243,
 'characters::Brienne of Tarth': 244,
 'freeform_tags::Banter': 245,
 'freeform_tags::Mild Hurt/Comfort': 246,
 'freeform_tags::Short': 247,
 'freeform_tags::Permanent Injury': 248,
 'categories::M/M': 249,
 'fandoms::House of the Dragon (TV)': 250,
 'relationships::Aemond "One-Eye" Targaryen/Original Female Character(s)': 251,
 'relationships::Helaena Targaryen/Jacaerys Velaryon': 252,
 'relationships::Aegon II Targaryen/Baela Targaryen': 253,
 'relationships::Rhaena Targaryen (Daughter of Daemon)/Lucerys Velaryon (Son of Rhaenyra)': 254,
 'relationships::Daemon Targaryen/Rhaenyra Targaryen': 255,
 'relationships::Harwin Strong/Rhaenyra Targaryen': 256,
 'relationships::Rhaenyra Targaryen/Laenor Velaryon': 257,
 'relationships::Alicent Hightower/Viserys I Targaryen': 258,
 'characters::Aemond "One-Eye" Targaryen': 259,
 'characters::Helaena Targaryen': 260,
 'characters::Jacaerys Velaryon': 261,
 'characters::Aegon II Targaryen': 262,
 'characters::Baela Targaryen': 263,
 'characters::Rhaena Targaryen (Daughter of Daemon)': 264,
 'characters::Lucerys Velaryon (Son of Rhaenyra)': 265,
 'characters::Daemon Targaryen': 266,
 'characters::Rhaenyra Targaryen': 267,
 'characters::Laenor Velaryon': 268,
 'characters::Alicent Hightower': 269,
 'characters::Viserys I Targaryen': 270,
 'characters::Harwin Strong': 271,
 'characters::Larys Strong': 272,
 'characters::Otto Hightower': 273,
 'freeform_tags::Alicent Hightower & Rhaenyra Targaryen Friendship': 274,
 'freeform_tags::Targaryen men have a thing for their nieces': 275,
 'freeform_tags::Targcest | Targaryen Incest (A Song of Ice and Fire)': 276,
 'freeform_tags::Aemond "One-Eye" Targaryen is Whipped': 277,
 'freeform_tags::Otto Hightower Being an Asshole': 278,
 'freeform_tags::Dragon Dreamers & Dragon Dreams (A Song of Ice and Fire)': 279,
 'freeform_tags::Magic': 280,
 "freeform_tags::Daemon Targaryen is Oc's Parent": 281,
 "freeform_tags::Everyone ignores the Warning's About the Dance": 282,
 "freeform_tags::The Oc's get's mad and takes the matter into her own hands": 283,
 'freeform_tags::Arranged Marriage': 284,
 'freeform_tags::Talking To Dead People': 285,
 'freeform_tags::Uncle/Niece Incest': 286,
 'freeform_tags::Possessive Behavior': 287,
 'freeform_tags::Other Additional Tags to Be Added': 288,
 'freeform_tags::The OC would kill for Helaena': 289,
 'freeform_tags::so will helaena': 290,
 'fandoms::A Knight of the Seven Kingdoms (TV)': 291,
 'relationships::Dunk | Duncan the Tall/Aerion Targaryen (Son of Maekar I)': 292,
 'characters::Dunk | Duncan the Tall (A Song of Ice and Fire)': 293,
 'characters::Aerion Targaryen (Son of Maekar I)': 294,
 'characters::Tanselle Too-Tall (A Song of Ice and Fire)': 295,
 'characters::Raymun Fossoway': 296,
 'characters::Daeron Targaryen (Son of Maekar I)': 297,
 'characters::Maekar I Targaryen': 298,
 'characters::Dunk': 299,
 'characters::Duncan the Tall': 300,
 'freeform_tags::Murder Mystery': 301,
 'freeform_tags::Police Uniforms': 302,
 'freeform_tags::Alternate Universe - Police': 303,
 'freeform_tags::Brutal Murder': 304,
 'freeform_tags::Assassination': 305,
 'freeform_tags::Anal Sex': 306,
 'freeform_tags::Rough Oral Sex': 307,
 'freeform_tags::Oral Sex': 308,
 'freeform_tags::Falling In Love': 309,
 'freeform_tags::Boys In Love': 310,
 'relationships::Aerion Targaryen (Son of Maekar I)/You': 311,
 'characters::Maegor Targaryen (Son of Aerion)': 312,
 'characters::You': 313,
 'freeform_tags::Female Reader-Insert': 314,
 'freeform_tags::No Use of Y/N for Reader-Insert': 315,
 'freeform_tags::No Smut': 316,
 'freeform_tags::Wildfire (A Song of Ice and Fire)': 317,
 'freeform_tags::Evil Aerion Targaryen (Son of Maekar I)': 318,
 'freeform_tags::Family Issues': 319,
 'freeform_tags::Married Couple': 320,
 'freeform_tags::Unhealthy Relationships': 321,
 'freeform_tags::Angst': 322,
 'freeform_tags::Hurt No Comfort': 323,
 'freeform_tags::Ambiguous/Open Ending': 324,
 'rating::Not Rated': 325,
 'relationships::Baelor "Breakspear" Targaryen/Original Female Character(s)': 326,
 'relationships::Lyonel Baratheon & Original Female Character(s)': 327,
 'relationships::Duncan the Tall & Original Female Character(s)': 328,
 'relationships::Baelor "Breakspear" Targaryen/Knight': 329,
 'characters::Baelor "Breakspear" Targaryen': 330,
 'characters::Original Female Character(s) of Color': 331,
 'characters::Lyonel Baratheon': 332,
 'characters::Valarr Targaryen': 333,
 'characters::Tourney at Ashford attendees': 334,
 'characters::Aegon V "Egg" Targaryen': 335,
 'characters::Knight': 336,
 'freeform_tags::Female Knight': 337,
 'freeform_tags::False knight': 338,
 'freeform_tags::Mystery knight': 339,
 'freeform_tags::Whatever you want to call them': 340,
 'freeform_tags::female mystery knight': 341,
 'freeform_tags::past established friendship': 342,
 'freeform_tags::~romantic relationship~': 343,
 'freeform_tags::OC is a bastard of the Red Mountains': 344,
 'freeform_tags::First Blackfyre Rebellion | Daemon I Blackfyre vs. Daeron II Targaryen': 345,
 'freeform_tags::Tourney at Ashford Meadow (A Song of Ice and Fire)': 346,
 'freeform_tags::Pre-Tourney at Ashford Meadow (A Song of Ice and Fire)': 347,
 'freeform_tags::OC has elements of PTSD': 348,
 'freeform_tags::Post War': 349,
 'freeform_tags::also a bit of a dive into the racial dynamics of the south': 350,
 'freeform_tags::And Classes': 351,
 'freeform_tags::also do i touch on the old magics? maybe': 352,
 'freeform_tags::Red Mountains': 353,
 "freeform_tags::Prince's Pass": 354,
 'freeform_tags::Kingsgrave': 355,
 'freeform_tags::The Greenblood': 356,
 'freeform_tags::i guess..things will get heated between them...': 357,
 'freeform_tags::who am I kidding': 358,
 'freeform_tags::can you tell tags are not my thing': 359,
 'freeform_tags::Dorne (A Song of Ice and Fire)': 360,
 'freeform_tags::my beloved': 361,
 'rating::Teen And Up Audiences': 362,
 'relationships::Dunk | Duncan the Tall & Aegon V "Egg" Targaryen': 363,
 'characters::Maester Aemon Targaryen': 364,
 'freeform_tags::Retelling': 365,
 'freeform_tags::POV Aegon V "Egg" Targaryen': 366,
 'fandoms::Marvel': 367,
 'relationships::Alicent Hightower & Aegon II Targaryen': 368,
 'relationships::Alicent Hightower & Aemond "One-Eye" Targaryen': 369,
 'relationships::Alicent Hightower & Helaena Targaryen': 370,
 'relationships::Alicent Hightower & Daeron Targaryen (Son of Viserys I)': 371,
 'relationships::Alicent Hightower & Otto Hightower': 372,
 'relationships::Alicent Hightower & Gwayne Hightower': 373,
 'characters::Wanda Maximoff': 374,
 'characters::Gwayne Hightower': 375,
 'characters::Daeron Targaryen (Son of Viserys I)': 376,
 'freeform_tags::House Hightower (A Song of Ice and Fire)': 377,
 'freeform_tags::Golden Age': 378,
 'freeform_tags::BAMF Alicent Hightower': 379,
 'freeform_tags::BAMF Wanda Maximoff': 380,
 "freeform_tags::English Is Not The Author's First Language": 381,
 'characters::Reader': 382,
 'freeform_tags::Established Relationship': 383,
 'freeform_tags::Poisoning': 384,
 'freeform_tags::Altered Mental States': 385,
 'freeform_tags::Mild Gore': 386,
 'freeform_tags::Not Beta Read': 387,
 'freeform_tags::reader is the warning': 388,
 'relationships::Robb Stark/You': 389,
 'freeform_tags::I miss Robb': 390,
 'freeform_tags::Married Life': 391,
 'freeform_tags::Not even lowkey breeding kink': 392,
 'freeform_tags::this was my first published fic and it sucks': 393,
 'freeform_tags::sorry - Freeform': 394,
 'freeform_tags::no beta we die like the Ned Stark': 395,
 'freeform_tags::a mix of book and show canon': 396,
 'relationships::Daeron Targaryen (Son of Maekar I)/You': 397,
 'characters::Kiera of Tyrosh (A Song of Ice and Fire)': 398,
 'characters::Daenora Targaryen': 399,
 'freeform_tags::Character Death': 400,
 'freeform_tags::There is sex scenes but not descriptive': 401,
 'freeform_tags::Can be read as a stand alone': 402,
 'freeform_tags::there are no happy endings in ba sing se': 403,
 'freeform_tags::Fluff-ish?': 404,
 'freeform_tags::no beta we die like baelor': 405,
 'freeform_tags::Pregnancy and Childbirth': 406,

In [ ]:
from scipy.sparse import coo_matrix
work_tag_matrix = coo_matrix(
    (data, (rows, cols)),
    shape=(len(work_mapper), len(tag_mapper))
)
work_tag_matrix = work_tag_matrix.tocsr()

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

bookmark_mask = all_works_df["is_bookmarked"].to_numpy() == 1
candidate_mask = all_works_df["is_bookmarked"].to_numpy() == 0

bookmarked_matrix = work_tag_matrix[bookmark_mask]
candidate_matrix = work_tag_matrix[candidate_mask]

In [ ]:
user_profile = np.asarray(bookmarked_matrix.mean(axis=0))

In [ ]:
similarities = cosine_similarity(candidate_matrix, user_profile).ravel()

In [ ]:
recommendations = all_works_df.loc[candidate_mask, ["id"]].copy()
recommendations["similarity_score"] = similarities

recommendations = recommendations.sort_values(
    "similarity_score",
    ascending=False
)

In [ ]:
recommendations

          id  similarity_score
39  84737721          0.327698
8   84723496          0.327024
29  84761796          0.280035
10  84722136          0.273718
21  84701301          0.256271
18  84708881          0.186059
31  84748536          0.162172
30  84752771          0.159890
36  84742296          0.147097
26  84763896          0.146643
22  84699031          0.097166
9   84723001          0.091015
27  84762276          0.088063
17  84709216          0.086203
20  84708291          0.067382
19  84708701          0.063136
32  84745361          0.059451
13  84719016          0.049502
25  84765921          0.043821
37  84738976          0.043189
11  84721256          0.042234
12  84720706          0.041179
15  84714196          0.037059
38  84737881          0.032641
16  84711126          0.031107
14  84715021          0.027843
34  84744381          0.027674
35  84743746          0.025339
23  84696726          0.010949
24  84769896          0.000000
28  84761826          0.000000
33  84744936          0.000000

In [ ]:
merged_recommendations = pd.merge(recommendations, not_bookmarked_works_df, on='id', how='left')
merged_recommendations.head()

,id,similarity_score,rating,categories,fandoms,relationships,characters,freeform_tags
0,84737721,0.327698,"[""Mature""]","[""F/M"", ""Gen"", ""Other""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Rhaegar Targaryen/Original Female Character""]","[""Rhaegar Targaryen"", ""Ned Stark"", ""Sansa Star...","[""Hurt/Comfort"", ""Angst"", ""Sex"", ""Whimsical"", ..."
1,84723496,0.327024,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Original Blackfyre Character/Ashara Dayne""]","[""Original Blackfyre Character(s)"", ""Original ...","[""Alternate Universe - Canon Divergence"", ""Hou..."
2,84761796,0.280035,"[""Not Rated""]",[],"[""Game of Thrones (TV)"", ""A Song of Ice and Fi...",[],"[""Sansa Stark"", ""Arya Stark"", ""Robb Stark"", ""J...","[""Magic"", ""shortstory"", ""Oneshot"", ""magicmirro..."
3,84722136,0.273718,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...",[],[],[]
4,84701301,0.256271,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)""]",[],"[""Jon Snow"", ""Ghost | Jon Snow's Direwolf"", ""N...","[""Westeros (A Song of Ice and Fire)"", ""Essos (..."

In [ ]:
merged_recommendations

,id,similarity_score,rating,categories,fandoms,relationships,characters,freeform_tags
0,84737721,0.327698,"[""Mature""]","[""F/M"", ""Gen"", ""Other""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Rhaegar Targaryen/Original Female Character""]","[""Rhaegar Targaryen"", ""Ned Stark"", ""Sansa Star...","[""Hurt/Comfort"", ""Angst"", ""Sex"", ""Whimsical"", ..."
1,84723496,0.327024,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Original Blackfyre Character/Ashara Dayne""]","[""Original Blackfyre Character(s)"", ""Original ...","[""Alternate Universe - Canon Divergence"", ""Hou..."
2,84761796,0.280035,"[""Not Rated""]",[],"[""Game of Thrones (TV)"", ""A Song of Ice and Fi...",[],"[""Sansa Stark"", ""Arya Stark"", ""Robb Stark"", ""J...","[""Magic"", ""shortstory"", ""Oneshot"", ""magicmirro..."
3,84722136,0.273718,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...",[],[],[]
4,84701301,0.256271,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)""]",[],"[""Jon Snow"", ""Ghost | Jon Snow's Direwolf"", ""N...","[""Westeros (A Song of Ice and Fire)"", ""Essos (..."
5,84708881,0.186059,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)"", ""A Song of Ice and Fi...","[""Robb Stark/You""]","[""Robb Stark"", ""Catelyn Tully Stark"", ""You""]","[""I miss Robb"", ""Married Life"", ""Not even lowk..."
6,84748536,0.162172,"[""Teen And Up Audiences""]","[""F/M""]","[""Game of Thrones (TV)""]","[""Jorah Mormont/Daenerys Targaryen""]","[""Jorah Mormont"", ""Daenerys Targaryen""]",[]
7,84752771,0.159890,"[""Teen And Up Audiences""]","[""M/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Jon Snow/Robb Stark""]","[""Robb Stark"", ""Jon Snow"", ""Grey Wind | Robb S...","[""Drunk Jon Snow"", ""Love Confessions"", ""Drunke..."
8,84742296,0.147097,"[""Teen And Up Audiences""]","[""Other""]","[""Game of Thrones (TV)""]","[""Sansa stark/vengence"", ""Sansa Stark & Lady S...","[""Sansa Stark"", ""Lady Stoneheart"", ""Joffrey Ba...","[""Gun Violence"", ""Revenge"", ""based off of a so..."
9,84763896,0.146643,"[""Mature""]","[""F/M"", ""Gen"", ""M/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Lyonel Baratheon/Dunk | Duncan the Tall"", ""O...","[""Aerys II Targaryen"", ""Jaime Lannister"", ""Dun...","[""Parallels"", ""Character Study"", ""Parallels be..."
10,84699031,0.097166,"[""Mature""]",[],"[""A Song of Ice and Fire - George R. R. Martin""]","[""Sandor Clegane/Sansa Stark""]","[""Sansa Stark"", ""Sandor Clegane""]","[""First Kiss"", ""Sex"", ""True Love"", ""Protective..."
11,84723001,0.091015,"[""General Audiences""]","[""F/M""]","[""Game of Thrones (TV)""]","[""Jaime Lannister/Brienne of Tarth""]","[""Jaime Lannister"", ""Brienne of Tarth""]","[""Banter"", ""Mild Hurt/Comfort"", ""Short"", ""Perm..."
12,84762276,0.088063,"[""Mature""]","[""Gen""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall & Rafe of Flea Bottom...","[""Original Female Character(s)"", ""Dunk | Dunca...","[""Alternate Universe - Canon Divergence"", ""Raf..."
13,84709216,0.086203,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Aerion Targaryen (Son of Maekar I)/You""]","[""Aerion Targaryen (Son of Maekar I)"", ""Reader...","[""Established Relationship"", ""Fluff and Angst""..."
14,84708291,0.067382,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Daeron Targaryen (Son of Maekar I)/You""]","[""Daeron Targaryen (Son of Maekar I)"", ""Maekar...","[""Character Death"", ""Alcohol Abuse/Alcoholism""..."
15,84708701,0.063136,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Daeron Targaryen (Son of Maekar I)/You""]","[""Daeron Targaryen (Son of Maekar I)"", ""Aerion...","[""Character Death"", ""There is sex scenes but n..."
16,84745361,0.059451,"[""Not Rated""]",[],"[""Game of Thrones (TV)""]",[],[],[]
17,84719016,0.049502,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)""]","[""Aerion Targaryen (Son of Maekar I)/You""]","[""Aerion Targaryen (Son of Maekar I)"", ""Maegor...","[""Female Reader-Insert"", ""No Use of Y/N for Re..."
18,84765921,0.043821,"[""Teen And Up Audiences""]","[""F/M""]","[""House of the Dragon (TV)""]","[""Daemon Targaryen/Rhaenyra Targaryen"", ""Daemo...","[""Daemon Targaryen"", ""Rhaenyra Targaryen"", ""Ae...",[]
19,84738976,0.043189,"[""Teen And Up Audiences""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Maekar I Targaryen/You""]","[""Maekar I Targaryen"", ""Aegon V \""Egg\"" Targar...","[""Fluff"", ""Angst"", ""Grief/Mourning"", ""nerd rea..."
20,84721256,0.042234,"[""Mature""]","[""F/F"", ""F/M"", ""M/M""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen/Original Female...","[""Aemond \""One-Eye\"" Targaryen"", ""Helaena Targ...","[""Alicent Hightower & Rhaenyra Targaryen Frien..."
21,84720706,0.041179,"[""Mature""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall/Aerion Targaryen (Son...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Murder Mystery"", ""Police Uniforms"", ""Alterna..."
22,84714196,0.037059,"[""Teen And Up Audiences""]","[""Gen""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Dunk | Duncan the Tall & Aegon V \""Egg\"" Tar...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Retelling"", ""POV Aegon V \""Egg\"" Targaryen""]"
23,84737881,0.032641,"[""General Audiences""]","[""Gen""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...",[],"[""Daella Targaryen (Daughter of Maekar I)"", ""A...",[]
24,84711126,0.031107,"[""General Audiences""]","[""F/M"", ""Gen""]","[""House of the Dragon (TV)"", ""Marvel""]","[""Alicent Hightower & Aegon II Targaryen"", ""Al...","[""Alicent Hightower"", ""Wanda Maximoff"", ""Gwayn...","[""House Hightower (A Song of Ice and Fire)"", ""..."
25,84715021,0.027843,"[""Not Rated""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Baelor \""Breakspear\"" Targaryen/Original Fem...","[""Baelor \""Breakspear\"" Targaryen"", ""Original ...","[""Female Knight"", ""False knight"", ""Mystery kni..."
26,84744381,0.027674,"[""Teen And Up Audiences""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall/Aerion Targaryen (Son...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Alternate Universe"", ""Modern Era"", ""study ab..."
27,84743746,0.025339,"[""Mature""]","[""F/F"", ""M/M"", ""Multi""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen/Lucerys Velaryo...","[""Lucerys Velaryon (Son of Rhaenyra)"", ""Aemond...","[""Questionable Consent"", ""Secret Identity"", ""P..."
28,84696726,0.010949,"[""General Audiences""]","[""Gen""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen & Helaena Targa...","[""Aemond \""One-Eye\"" Targaryen"", ""Helaena Targ...","[""Alternate Universe - Hogwarts"", ""Aegon II Ta..."
29,84769896,0.000000,"[""Not Rated""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)""]","[""Dunk | Duncan the Tall/Baelor \""Breakspear\""...","[""Baelor \""Breakspear\"" Targaryen"", ""Dunk | Du...","[""Alternate Universe - Modern Setting"", ""Medie..."
30,84761826,0.000000,"[""Not Rated""]",[],"[""House of the Dragon (TV)""]","[""Aemma Arryn/Viserys I Targaryen""]","[""Aemma Arryn"", ""Viserys I Targaryen""]",[]
31,84744936,0.000000,"[""Not Rated""]",[],"[""game of thrones""]",[],[],[]

Final recommendations from tag and collab filters

In [ ]:
final_recommendations = pd.merge(
    merged_recommendations,
    collab_recommendations,
    left_on='id',
    right_on='work_id',
    how='left'
)


# final_recommendations = final_recommendations.sort_values(
#     by=["similarity_score", "collab_score_sum_normalized"],
#     ascending=False
# ).reset_index(drop=True)

final_recommendations.head()

,id,similarity_score,rating,categories,fandoms,relationships,characters,freeform_tags,work_id,collab_score,collab_score_sum,max_similarity,matched_profile_work_count,matched_profile_works,collab_score_sum_normalized
0,84737721,0.327698,"[""Mature""]","[""F/M"", ""Gen"", ""Other""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Rhaegar Targaryen/Original Female Character""]","[""Rhaegar Targaryen"", ""Ned Stark"", ""Sansa Star...","[""Hurt/Comfort"", ""Angst"", ""Sex"", ""Whimsical"", ...",84737721,0.0,0.0,0.0,0,[],0.0
1,84723496,0.327024,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Original Blackfyre Character/Ashara Dayne""]","[""Original Blackfyre Character(s)"", ""Original ...","[""Alternate Universe - Canon Divergence"", ""Hou...",84723496,0.0,0.0,0.0,0,[],0.0
2,84761796,0.280035,"[""Not Rated""]",[],"[""Game of Thrones (TV)"", ""A Song of Ice and Fi...",[],"[""Sansa Stark"", ""Arya Stark"", ""Robb Stark"", ""J...","[""Magic"", ""shortstory"", ""Oneshot"", ""magicmirro...",84761796,0.0,0.0,0.0,0,[],0.0
3,84722136,0.273718,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...",[],[],[],84722136,0.0,0.0,0.0,0,[],0.0
4,84701301,0.256271,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)""]",[],"[""Jon Snow"", ""Ghost | Jon Snow's Direwolf"", ""N...","[""Westeros (A Song of Ice and Fire)"", ""Essos (...",84701301,0.0,0.0,0.0,0,[],0.0

In [ ]:
final_recommendations['final_score'] = final_recommendations['similarity_score'] * 0.6 + final_recommendations['collab_score_sum_normalized'] * 0.4
final_recommendations.head()

,id,similarity_score,rating,categories,fandoms,relationships,characters,freeform_tags,work_id,collab_score,collab_score_sum,max_similarity,matched_profile_work_count,matched_profile_works,collab_score_sum_normalized,final_score
0,84737721,0.327698,"[""Mature""]","[""F/M"", ""Gen"", ""Other""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Rhaegar Targaryen/Original Female Character""]","[""Rhaegar Targaryen"", ""Ned Stark"", ""Sansa Star...","[""Hurt/Comfort"", ""Angst"", ""Sex"", ""Whimsical"", ...",84737721,0.0,0.0,0.0,0,[],0.0,0.196619
1,84723496,0.327024,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Original Blackfyre Character/Ashara Dayne""]","[""Original Blackfyre Character(s)"", ""Original ...","[""Alternate Universe - Canon Divergence"", ""Hou...",84723496,0.0,0.0,0.0,0,[],0.0,0.196215
2,84761796,0.280035,"[""Not Rated""]",[],"[""Game of Thrones (TV)"", ""A Song of Ice and Fi...",[],"[""Sansa Stark"", ""Arya Stark"", ""Robb Stark"", ""J...","[""Magic"", ""shortstory"", ""Oneshot"", ""magicmirro...",84761796,0.0,0.0,0.0,0,[],0.0,0.168021
3,84722136,0.273718,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...",[],[],[],84722136,0.0,0.0,0.0,0,[],0.0,0.164231
4,84701301,0.256271,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)""]",[],"[""Jon Snow"", ""Ghost | Jon Snow's Direwolf"", ""N...","[""Westeros (A Song of Ice and Fire)"", ""Essos (...",84701301,0.0,0.0,0.0,0,[],0.0,0.153762

In [ ]:
final_recommendations = final_recommendations.sort_values(
    by=["final_score"],
    ascending=False
).reset_index(drop=True)
final_recommendations

,id,similarity_score,rating,categories,fandoms,relationships,characters,freeform_tags,work_id,collab_score,collab_score_sum,max_similarity,matched_profile_work_count,matched_profile_works,collab_score_sum_normalized,final_score
0,84738976,0.043189,"[""Teen And Up Audiences""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Maekar I Targaryen/You""]","[""Maekar I Targaryen"", ""Aegon V \""Egg\"" Targar...","[""Fluff"", ""Angst"", ""Grief/Mourning"", ""nerd rea...",84738976,0.010796,0.086367,0.045644,2,"[75267501, 81993896]",1.000000,0.425913
1,84763896,0.146643,"[""Mature""]","[""F/M"", ""Gen"", ""M/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Lyonel Baratheon/Dunk | Duncan the Tall"", ""O...","[""Aerys II Targaryen"", ""Jaime Lannister"", ""Dun...","[""Parallels"", ""Character Study"", ""Parallels be...",84763896,0.003478,0.027821,0.027821,1,[62910172],0.322124,0.216835
2,84737721,0.327698,"[""Mature""]","[""F/M"", ""Gen"", ""Other""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Rhaegar Targaryen/Original Female Character""]","[""Rhaegar Targaryen"", ""Ned Stark"", ""Sansa Star...","[""Hurt/Comfort"", ""Angst"", ""Sex"", ""Whimsical"", ...",84737721,0.000000,0.000000,0.000000,0,[],0.000000,0.196619
3,84723496,0.327024,"[""Mature""]","[""F/M""]","[""A Song of Ice and Fire & Related Fandoms"", ""...","[""Original Blackfyre Character/Ashara Dayne""]","[""Original Blackfyre Character(s)"", ""Original ...","[""Alternate Universe - Canon Divergence"", ""Hou...",84723496,0.000000,0.000000,0.000000,0,[],0.000000,0.196215
4,84761796,0.280035,"[""Not Rated""]",[],"[""Game of Thrones (TV)"", ""A Song of Ice and Fi...",[],"[""Sansa Stark"", ""Arya Stark"", ""Robb Stark"", ""J...","[""Magic"", ""shortstory"", ""Oneshot"", ""magicmirro...",84761796,0.000000,0.000000,0.000000,0,[],0.000000,0.168021
5,84722136,0.273718,"[""Mature""]","[""F/F"", ""F/M""]","[""A Song of Ice and Fire - George R. R. Martin...",[],[],[],84722136,0.000000,0.000000,0.000000,0,[],0.000000,0.164231
6,84701301,0.256271,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)""]",[],"[""Jon Snow"", ""Ghost | Jon Snow's Direwolf"", ""N...","[""Westeros (A Song of Ice and Fire)"", ""Essos (...",84701301,0.000000,0.000000,0.000000,0,[],0.000000,0.153762
7,84708881,0.186059,"[""Mature""]","[""F/M""]","[""Game of Thrones (TV)"", ""A Song of Ice and Fi...","[""Robb Stark/You""]","[""Robb Stark"", ""Catelyn Tully Stark"", ""You""]","[""I miss Robb"", ""Married Life"", ""Not even lowk...",84708881,0.000000,0.000000,0.000000,0,[],0.000000,0.111635
8,84748536,0.162172,"[""Teen And Up Audiences""]","[""F/M""]","[""Game of Thrones (TV)""]","[""Jorah Mormont/Daenerys Targaryen""]","[""Jorah Mormont"", ""Daenerys Targaryen""]",[],84748536,0.000000,0.000000,0.000000,0,[],0.000000,0.097303
9,84752771,0.159890,"[""Teen And Up Audiences""]","[""M/M""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Jon Snow/Robb Stark""]","[""Robb Stark"", ""Jon Snow"", ""Grey Wind | Robb S...","[""Drunk Jon Snow"", ""Love Confessions"", ""Drunke...",84752771,0.000000,0.000000,0.000000,0,[],0.000000,0.095934
10,84742296,0.147097,"[""Teen And Up Audiences""]","[""Other""]","[""Game of Thrones (TV)""]","[""Sansa stark/vengence"", ""Sansa Stark & Lady S...","[""Sansa Stark"", ""Lady Stoneheart"", ""Joffrey Ba...","[""Gun Violence"", ""Revenge"", ""based off of a so...",84742296,0.000000,0.000000,0.000000,0,[],0.000000,0.088258
11,84699031,0.097166,"[""Mature""]",[],"[""A Song of Ice and Fire - George R. R. Martin""]","[""Sandor Clegane/Sansa Stark""]","[""Sansa Stark"", ""Sandor Clegane""]","[""First Kiss"", ""Sex"", ""True Love"", ""Protective...",84699031,0.000000,0.000000,0.000000,0,[],0.000000,0.058299
12,84723001,0.091015,"[""General Audiences""]","[""F/M""]","[""Game of Thrones (TV)""]","[""Jaime Lannister/Brienne of Tarth""]","[""Jaime Lannister"", ""Brienne of Tarth""]","[""Banter"", ""Mild Hurt/Comfort"", ""Short"", ""Perm...",84723001,0.000000,0.000000,0.000000,0,[],0.000000,0.054609
13,84762276,0.088063,"[""Mature""]","[""Gen""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall & Rafe of Flea Bottom...","[""Original Female Character(s)"", ""Dunk | Dunca...","[""Alternate Universe - Canon Divergence"", ""Raf...",84762276,0.000000,0.000000,0.000000,0,[],0.000000,0.052838
14,84709216,0.086203,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Aerion Targaryen (Son of Maekar I)/You""]","[""Aerion Targaryen (Son of Maekar I)"", ""Reader...","[""Established Relationship"", ""Fluff and Angst""...",84709216,0.000000,0.000000,0.000000,0,[],0.000000,0.051722
15,84708291,0.067382,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Daeron Targaryen (Son of Maekar I)/You""]","[""Daeron Targaryen (Son of Maekar I)"", ""Maekar...","[""Character Death"", ""Alcohol Abuse/Alcoholism""...",84708291,0.000000,0.000000,0.000000,0,[],0.000000,0.040429
16,84708701,0.063136,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Daeron Targaryen (Son of Maekar I)/You""]","[""Daeron Targaryen (Son of Maekar I)"", ""Aerion...","[""Character Death"", ""There is sex scenes but n...",84708701,0.000000,0.000000,0.000000,0,[],0.000000,0.037881
17,84745361,0.059451,"[""Not Rated""]",[],"[""Game of Thrones (TV)""]",[],[],[],84745361,0.000000,0.000000,0.000000,0,[],0.000000,0.035671
18,84719016,0.049502,"[""Mature""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)""]","[""Aerion Targaryen (Son of Maekar I)/You""]","[""Aerion Targaryen (Son of Maekar I)"", ""Maegor...","[""Female Reader-Insert"", ""No Use of Y/N for Re...",84719016,0.000000,0.000000,0.000000,0,[],0.000000,0.029701
19,84765921,0.043821,"[""Teen And Up Audiences""]","[""F/M""]","[""House of the Dragon (TV)""]","[""Daemon Targaryen/Rhaenyra Targaryen"", ""Daemo...","[""Daemon Targaryen"", ""Rhaenyra Targaryen"", ""Ae...",[],84765921,0.000000,0.000000,0.000000,0,[],0.000000,0.026292
20,84721256,0.042234,"[""Mature""]","[""F/F"", ""F/M"", ""M/M""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen/Original Female...","[""Aemond \""One-Eye\"" Targaryen"", ""Helaena Targ...","[""Alicent Hightower & Rhaenyra Targaryen Frien...",84721256,0.000000,0.000000,0.000000,0,[],0.000000,0.025341
21,84720706,0.041179,"[""Mature""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall/Aerion Targaryen (Son...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Murder Mystery"", ""Police Uniforms"", ""Alterna...",84720706,0.000000,0.000000,0.000000,0,[],0.000000,0.024708
22,84714196,0.037059,"[""Teen And Up Audiences""]","[""Gen""]","[""A Song of Ice and Fire - George R. R. Martin...","[""Dunk | Duncan the Tall & Aegon V \""Egg\"" Tar...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Retelling"", ""POV Aegon V \""Egg\"" Targaryen""]",84714196,0.000000,0.000000,0.000000,0,[],0.000000,0.022235
23,84737881,0.032641,"[""General Audiences""]","[""Gen""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...",[],"[""Daella Targaryen (Daughter of Maekar I)"", ""A...",[],84737881,0.000000,0.000000,0.000000,0,[],0.000000,0.019584
24,84711126,0.031107,"[""General Audiences""]","[""F/M"", ""Gen""]","[""House of the Dragon (TV)"", ""Marvel""]","[""Alicent Hightower & Aegon II Targaryen"", ""Al...","[""Alicent Hightower"", ""Wanda Maximoff"", ""Gwayn...","[""House Hightower (A Song of Ice and Fire)"", ""...",84711126,0.000000,0.000000,0.000000,0,[],0.000000,0.018664
25,84715021,0.027843,"[""Not Rated""]","[""F/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Baelor \""Breakspear\"" Targaryen/Original Fem...","[""Baelor \""Breakspear\"" Targaryen"", ""Original ...","[""Female Knight"", ""False knight"", ""Mystery kni...",84715021,0.000000,0.000000,0.000000,0,[],0.000000,0.016706
26,84744381,0.027674,"[""Teen And Up Audiences""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)"", ""A Son...","[""Dunk | Duncan the Tall/Aerion Targaryen (Son...","[""Dunk | Duncan the Tall (A Song of Ice and Fi...","[""Alternate Universe"", ""Modern Era"", ""study ab...",84744381,0.000000,0.000000,0.000000,0,[],0.000000,0.016604
27,84743746,0.025339,"[""Mature""]","[""F/F"", ""M/M"", ""Multi""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen/Lucerys Velaryo...","[""Lucerys Velaryon (Son of Rhaenyra)"", ""Aemond...","[""Questionable Consent"", ""Secret Identity"", ""P...",84743746,0.000000,0.000000,0.000000,0,[],0.000000,0.015203
28,84696726,0.010949,"[""General Audiences""]","[""Gen""]","[""House of the Dragon (TV)""]","[""Aemond \""One-Eye\"" Targaryen & Helaena Targa...","[""Aemond \""One-Eye\"" Targaryen"", ""Helaena Targ...","[""Alternate Universe - Hogwarts"", ""Aegon II Ta...",84696726,0.000000,0.000000,0.000000,0,[],0.000000,0.006569
29,84769896,0.000000,"[""Not Rated""]","[""M/M""]","[""A Knight of the Seven Kingdoms (TV)""]","[""Dunk | Duncan the Tall/Baelor \""Breakspear\""...","[""Baelor \""Breakspear\"" Targaryen"", ""Dunk | Du...","[""Alternate Universe - Modern Setting"", ""Medie...",84769896,0.000000,0.000000,0.000000,0,[],0.000000,0.000000
30,84761826,0.000000,"[""Not Rated""]",[],"[""House of the Dragon (TV)""]","[""Aemma Arryn/Viserys I Targaryen""]","[""Aemma Arryn"", ""Viserys I Targaryen""]",[],84761826,0.000000,0.000000,0.000000,0,[],0.000000,0.000000
31,84744936,0.000000,"[""Not Rated""]",[],"[""game of thrones""]",[],[],[],84744936,0.000000,0.000000,0.000000,0,[],0.000000,0.000000